nics = Nic.create([{name:'Presentación de Estados Financieros', number: 1, text: 'OBJETIVO 
1 Esta Norma establece las bases para la presentación de los estados financieros de propósito general para asegurar que los mismos sean comparables, tanto con los estados financieros de la misma entidad correspondientes a periodos anteriores, como con los de otras entidades. Esta Norma establece requerimientos generales para la presentación de los estados financieros, guías para determinar su estructura y requisitos mínimos sobre su contenido. 
ALCANCE 
2 Una entidad aplicará esta Norma al preparar y presentar estados financieros de propósito de información general conforme a las Normas Internacionales de Información Financiera (NIIF). 
3 En otras NIIF se establecen los requerimientos de reconocimiento, medición e información a revelar para transacciones y otros sucesos. 
4 Esta Norma no será de aplicación a la estructura y contenido de los estados financieros intermedios condensados que se elaboren de acuerdo con la NIC 34 Información Financiera Intermedia. Sin embargo, los párrafos 15 a 35 se aplicarán a estos estados financieros. Esta Norma se aplicará de la misma forma a todas las entidades, incluyendo las que presentan estados financieros consolidados de acuerdo con la NIIF 10 Estados Financieros Consolidados y las que presentan estados financieros separados, de acuerdo con la NIC 27 Estados Financieros Separados. 
5 Esta Norma utiliza terminología propia de las entidades con ánimo de lucro, incluyendo las pertenecientes al sector público. Si las entidades con actividades sin fines de lucro del sector privado o del sector público aplican esta Norma, podrían verse obligadas a modificar las descripciones utilizadas para partidas específicas de los estados financieros, e incluso para éstos. 
6 Similarmente, las entidades que carecen de patrimonio, tal como se define en la NIC 32 Instrumentos Financieros: Presentación (por ejemplo, algunos fondos de inversión colectiva), y las entidades cuyo capital en acciones no es patrimonio (por ejemplo, algunas entidades cooperativas) podrían tener la necesidad de adaptar la presentación en los estados financieros de las participaciones de sus miembros o participantes. 
DEFINICIONES 
7 Los términos siguientes se usan, en esta Norma, con los significados que a continuación se especifican: 
Los estados financieros con propósito general (denominados “estados financieros”) son aquellos que pretenden cubrir las necesidades de usuarios que no están en condiciones de exigir informes a la medida de sus necesidades específicas de información. 
Impracticable La aplicación de un requisito será impracticable cuando la entidad no pueda aplicarlo tras efectuar todos los esfuerzos razonables para hacerlo.
Las Normas Internacionales de Información Financiera (NIIF) son las Normas e Interpretaciones emitidas por el Consejo de Normas Internacionales de Contabilidad (IASB). Esas Normas comprenden: 
(a) las Normas Internacionales de Información Financiera; 
(b) las Normas Internacionales de Contabilidad; 
(c) las Interpretaciones CINIIF; y 
(d) Interpretaciones SIC.1
 Material o con importancia relativa: 
La información es material o tiene importancia relativa si su omisión, expresión inadecuada o ensombrecimiento podría esperarse razonablemente que influya sobre las decisiones que los usuarios principales de los estados financieros con propósito general toman a partir de los estados financieros, que proporcionan información financiera sobre una entidad que informa específica. 
La materialidad o importancia relativa depende de la naturaleza o magnitud de la información, o de ambas. Una entidad evalúa si la información, individualmente o en combinación con otra información, es material o con importancia relativa en el contexto de sus estados financieros tomados como un todo. 
La información se ensombrece si se comunica de forma que hubiera tenido un efecto similar para los usuarios principales de los estados financieros que la omisión o expresión inadecuada de esa información. Ejemplos de circunstancias que pueden dar lugar a que información material o con importancia relativa esté siendo ensombrecida son los siguientes: 
(a) la información con respecto a una partida material o con importancia relativa u otro suceso se revela en los estados financieros, pero el lenguaje usado es vago o poco claro; 
(b) la información con respecto a una partida material o con importancia relativa, transacción u otro suceso está dispersa por los estados financieros; 
(c) partidas diferentes, transacciones u otros sucesos se agregan inapropiadamente; 
(d) partidas similares, transacciones u otros sucesos se desagregan inapropiadamente; y 
(e) la comprensibilidad de los estados financieros se reduce como resultado de ocultar información material o con importancia relativa dentro de información no significativa, en la medida en que los usuarios principales no puedan determinar qué información es material o tiene importancia relativa. 
La evaluación de si la información pudiera razonablemente esperarse que influya en las decisiones tomadas por los usuarios principales de los estados financieros con propósito general de una entidad que informa requiere que una entidad considere las características de los usuarios a la vez que considera también las circunstancias propias de la entidad. Numerosos inversores, prestamistas y otros acreedores existentes y potenciales no tienen la posibilidad de requerir que las entidades que informan les proporcionen información directamente, y deben confiar en los estados financieros con propósito general para obtener la mayor parte de la información financiera que necesitan. Por consiguiente, ellos son los usuarios principales a quienes se dirigen los estados financieros con propósito general. Los estados financieros se preparan para usuarios que tienen un conocimiento razonable de las actividades económicas y del mundo de los negocios, que revisan y analizan la información con diligencia. A veces, incluso usuarios diligentes y bien informados pueden necesitar recabar la ayuda de un asesor para comprender información sobre fenómenos económicos complejos. Las notas contienen información añadida a la que se presenta en el estado de situación financiera, estado (estados) del resultado del periodo y otro resultado integral, estado de cambios en el patrimonio y estado de flujos de efectivo. Las notas suministran descripciones narrativas o desagregaciones de partidas presentadas en esos estados, e información sobre partidas que no cumplen las condiciones para ser reconocidas en ellos. 
Los componentes de otro resultado integral incluyen: 
(a) cambios en el superávit de revaluación (véase la NIC 16 Propiedades, Planta y Equipo y la NIC 38 Activos Intangibles); 
(b) nuevas mediciones de los planes de beneficios definidos (véase la NIC 19 Beneficios a los Empleados); 
(c) ganancias y pérdidas producidas por la conversión de los estados financieros de un negocio en el extranjero (véase la NIC 21 Efectos de la Variación en las Tasas de Cambio de la Moneda Extranjera);
 (d) las ganancias y pérdidas procedentes de inversiones en instrumentos de patrimonio designados a valor razonable con cambios en otro resultado integral de acuerdo con el párrafo 5.7.5 de la NIIF 9 Instrumentos Financieros; 
(da) las ganancias y pérdidas sobre activos financieros medidos al valor razonable con cambios en otro resultado integral de acuerdo con el párrafo 4.1.2A de la NIIF 9. 
(e) la parte efectiva de las ganancias y pérdidas de los instrumentos de cobertura en una cobertura de flujos de efectivo y las ganancias y pérdidas de los instrumentos de cobertura que cubren inversiones en instrumentos de patrimonio medidos a valor razonable con cambios en otro resultado integral de acuerdo con el párrafo 5.7.5 de NIIF 9 (véase el Capítulo 6 de la NIIF 9); 
(f) para pasivos particulares designados como a valor razonable con cambios en resultados, el importe del cambio en el valor razonable que sea atribuible a cambios en el riesgo de crédito del pasivo (véase el párrafo 5.7.7 de la NIIF 9); 
(g) los cambios en el valor temporal de las opciones al separar el valor intrínseco y el valor temporal de un contrato de opción y la designación como el instrumento de cobertura solo de los cambios en el valor intrínseco (véase el Capítulo 6 de la NIIF 9); 
(h) los cambios en el valor de los elementos a término de contratos a término al separar el elemento a término y el elemento al contado de un contrato a término y la designación como el instrumento de cobertura solo de los cambios en el elemento al contado, y los cambios en el valor del diferencial de la tasa de cambio de la moneda extranjera de un instrumento financiero al excluirlo de la designación de ese instrumento financiero como el instrumento de cobertura (véase el Capítulo 6 de la NIIF 9); 
(i) gastos e ingresos financieros por seguros de contratos emitidos dentro del alcance de la NIIF 17 Contratos de Seguro excluidos del resultado del periodo cuando los gastos o ingresos financieros por seguros se desglosan para incluir en el resultado del periodo un importe determinado por una asignación sistemática aplicando el párrafo 88(b) de la NIIF 17, o por un importe que elimina las asimetrías contables con los gastos o ingresos financieros por seguros, aplicando el párrafo 89(b) de la NIIF 17; y 
(j) los gastos o ingresos financieros por seguros por contratos de reaseguro mantenidos excluidos del resultado del periodo cuando los gastos o ingresos financieros por reaseguros totales se desglosan para incluir en el resultado de periodo un importe determinado por una asignación sistemática aplicando el párrafo 88(b) de la NIIF 17. 
Los propietarios son poseedores de instrumentos clasificados como patrimonio. 
El resultado del periodo es el total de ingresos menos gastos, excluyendo los componentes de otro resultado integral. Los ajustes por reclasificación son importes reclasificados en el resultado en el periodo corriente que fueron reconocidos en otro resultado integral en el periodo corriente o en periodos anteriores. El resultado integral total es el cambio en el patrimonio durante un periodo, que procede de transacciones y otros sucesos, distintos de aquellos cambios derivados de transacciones con los propietarios en su condición de tales. El resultado integral total comprende todos los componentes del “resultado” y de “otro resultado integral”. Los propietarios son poseedores de instrumentos clasificados como patrimonio. El resultado del periodo es el total de ingresos menos gastos, excluyendo los componentes de otro resultado integral. Los ajustes por reclasificación son importes reclasificados en el resultado en el periodo corriente que fueron reconocidos en otro resultado integral en el periodo corriente o en periodos anteriores. El resultado integral total es el cambio en el patrimonio durante un periodo, que procede de transacciones y otros sucesos, distintos de aquellos cambios derivados de transacciones con los propietarios en su condición de tales. El resultado integral total comprende todos los componentes del “resultado” y de “otro resultado integral”. 8 Aunque esta Norma utiliza los términos “otro resultado integral”, “resultado” y “resultado integral total”, una entidad puede utilizar otros términos para denominar los totales, siempre que el significado sea claro. Por ejemplo, una entidad puede utilizar el término “resultado neto” para denominar al resultado. 
8ª Los siguientes términos se describen en la NIC 32 Instrumentos Financieros: Presentación y se utilizan en esta Norma con el significado especificado en dicha NIC 32: 
(a) instrumento financiero con opción de venta clasificado como un instrumento de patrimonio (descrito en los párrafos 16A y 16B de la NIC 32) 
(b) un instrumento que impone a la entidad una obligación de entregar a terceros una participación proporcional de los activos netos de la entidad solo en el momento de la liquidación y se clasifica como un instrumento de patrimonio (descrito en los párrafos 16C y 16D de la NIC 32).  
ESTADOS FINANCIEROS 
FINALIDAD DE LOS ESTADOS FINANCIEROS
 9 Los estados financieros constituyen una representación estructurada de la situación financiera y del rendimiento financiero de una entidad. El objetivo de los estados financieros es suministrar información acerca de la situación financiera, del rendimiento financiero y de los flujos de efectivo de una entidad, que sea útil a una amplia variedad de usuarios a la hora de tomar sus decisiones económicas. Los estados financieros también muestran los resultados de la gestión realizada por los administradores con los recursos que les han sido confiados. Para cumplir este objetivo, los estados financieros suministrarán información acerca de los siguientes elementos de una entidad: 
(a) activos; 
(b) pasivos; 
(c) patrimonio; 
(d) ingresos y gastos, en los que se incluyen las ganancias y pérdidas; 
(e) aportaciones de los propietarios y distribuciones a los mismos en su condición de tales; y 
(f) flujos de efectivo. Esta información, junto con la contenida en las notas, ayuda a los usuarios a predecir los flujos de efectivo futuros de la entidad y, en particular, su distribución temporal y su grado de certidumbre. 
CONJUNTO COMPLETO DE ESTADOS FINANCIEROS 
10 Un juego completo de estados financieros comprende: 
(a) un estado de situación financiera al final del periodo; 
(b) un estado del resultado y otro resultado integral del periodo; 
(c) un estado de cambios en el patrimonio del periodo; 
(d) un estado de flujos de efectivo del periodo; 
(e) notas, que incluyan un resumen de las políticas contables significativas y otra información explicativa; 
(ea) información comparativa con respecto al periodo inmediato anterior como se especifica en los párrafos 38 y 38A; y 
(f) un estado de situación financiera al principio del primer periodo inmediato anterior, cuando una entidad aplique una política contable de forma retroactiva o haga una reexpresión retroactiva de partidas en sus estados financieros, o cuando reclasifique partidas en sus estados financieros de acuerdo con los párrafos 40A a 40D. Una entidad puede utilizar, para denominar a los estados, títulos distintos a los utilizados en esta Norma. Por ejemplo, una entidad puede utilizar el título “estado del resultado integral” en lugar de “estado del resultado y otro resultado integral”. 10ª Una entidad puede presentar un estado del resultado del periodo y otro resultado integral único, con el resultado del periodo y el otro resultado integral presentados en dos secciones. Las secciones se presentarán juntas, con la sección del resultado del periodo presentado en primer lugar seguido directamente por la sección de otro resultado integral. Una entidad puede presentar la sección del resultado del periodo en un estado de resultado del periodo separado. Si lo hace así, el estado del resultado del periodo separado precederá inmediatamente al estado que presente el resultado integral, que comenzará con el resultado del periodo. 
11 Una entidad presentará con el mismo nivel de importancia todos los estados financieros que forman un juego completo de estados financieros. 
12 [Eliminado] 
13 Muchas entidades presentan, fuera de sus estados financieros, un análisis financiero elaborado por la gerencia, que describe y explica las características principales del rendimiento financiero y la situación financiera de la entidad, así como las principales incertidumbres a las que se enfrenta. Tal informe puede incluir un examen de: 
(a) los principales factores e influencias que han determinado el rendimiento financiero, incluyendo los cambios en el entorno en que opera la entidad, su respuesta a esos cambios y su efecto, así como la política de inversiones que sigue para mantener y mejorar dicho rendimiento financiero, incluyendo su política de dividendos; 
(b) las fuentes de financiación de la entidad, así como su objetivo respecto al coeficiente de deudas sobre patrimonio; y 
(c) los recursos de la entidad no reconocidos en el estado de situación financiera según las NIIF. 
14 Muchas entidades también presentan, fuera de sus estados financieros, informes y estados tales como informes medioambientales y estados del valor añadido, particularmente en sectores industriales en los que los factores del medio ambiente son significativos y cuando los trabajadores se consideran un grupo de usuarios importante. Los informes y estados presentados fuera de los estados financieros quedan fuera del alcance de las NIIF. 
CARACTERÍSTICAS GENERALES 
PRESENTACIÓN RAZONABLE Y CUMPLIMIENTO DE LAS NIIF
 15 Los estados financieros deberán presentar razonablemente la situación financiera, el rendimiento financiero, así como los flujos de efectivo de una entidad. Esta presentación razonable requiere la presentación fidedigna de los efectos de las transacciones, así como de otros sucesos y condiciones, de acuerdo con las definiciones y los criterios de reconocimiento de activos, pasivos, ingresos y gastos establecidos en el Marco Conceptual. Se presume que la aplicación de las NIIF, acompañada de información adicional cuando sea preciso, dará lugar a estados financieros que proporcionen una presentación razonable. 
16 Una entidad cuyos estados financieros cumplan las NIIF efectuará, en las notas, una declaración, explícita y sin reservas, de dicho cumplimiento. Una entidad no señalará que sus estados financieros cumplen con las NIIF a menos que satisfagan todos los requerimientos de estas. 
17 En casi la totalidad de las circunstancias, una entidad logrará una presentación razonable cumpliendo con las NIIF aplicables. Una presentación razonable también requiere que una entidad: 
(a) Seleccione y aplique las políticas contables de acuerdo con la NIC 8 Políticas Contables, Cambios en las Estimaciones Contables y Errores. La NIC 8 establece una jerarquía normativa, a considerar por la gerencia en ausencia de una NIIF que sea aplicable específicamente a una partida. 
(b) Presente información, que incluya a las políticas contables, de una forma que sea relevante, fiable, comparable y comprensible. 
(c) Suministre información adicional, siempre que el cumplimiento con los requerimientos especificados por las NIIF resulte insuficiente para permitir a los usuarios comprender el impacto de determinadas transacciones, de otros sucesos o condiciones, sobre la situación financiera y el rendimiento financiero de la entidad. 18 Una entidad no puede rectificar políticas contables inapropiadas mediante la revelación de las políticas contables utilizadas, ni mediante la utilización de notas u otro material explicativo. 
19 En la circunstancia extremadamente excepcional de que la gerencia concluyera que el cumplimiento de un requerimiento de una NIIF sería tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual, la entidad no lo aplicará, según se establece en el párrafo 20, siempre que el marco regulatorio aplicable requiera, o no prohíba, esta falta de aplicación. 20 Cuando una entidad no aplique un requerimiento establecido en una NIIF de acuerdo con el párrafo 19, revelará: 
(a) que la gerencia ha llegado a la conclusión de que los estados financieros presentan razonablemente la situación financiera, rendimiento financiero y los flujos de efectivo; 
(b) que ha cumplido con las NIIF aplicables, excepto que ha dejado de aplicar un requerimiento concreto para lograr una presentación razonable; 
(c) el título de la NIIF que la entidad ha dejado de aplicar, la naturaleza del desacuerdo, incluyendo el tratamiento que la NIIF requeriría, la razón por la que ese tratamiento sería en las circunstancias tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual, junto con el tratamiento alternativo adoptado; y 
(d) para cada periodo sobre el que se presente información, el impacto financiero de la falta de aplicación sobre cada partida de los estados financieros que debería haber sido presentada cumpliendo con el requerimiento mencionado. Cuando una entidad haya dejado de aplicar, en algún periodo anterior, un requerimiento de una NIIF, y ello afecte a los importes reconocidos en los estados financieros del periodo actual, deberá revelar la información establecida en el párrafo 20(c) y (d). 
21 Cuando una entidad haya dejado de aplicar, en algún periodo anterior, un requerimiento de una NIIF, y ello afecte a los importes reconocidos en los estados financieros del periodo actual, deberá revelar la información establecida en el párrafo 20(c) y (d).
22 El párrafo 21 se aplicará, por ejemplo, cuando una entidad haya dejado de cumplir, en un periodo anterior, un requerimiento de una NIIF para la medición de activos o pasivos, y ello afectase a la medición de los cambios en activos y pasivos reconocidos en los estados financieros del periodo actual. 
23 En la circunstancia extremadamente excepcional de que la gerencia concluyera que el cumplimiento de un requerimiento de una NIIF sería tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual, pero el marco regulatorio prohibiera apartamientos al requerimiento, la entidad reducirá, en la medida de lo posible, los aspectos de cumplimiento que perciba como causantes del engaño, mediante la revelación de: 
(a) el título de la NIIF en cuestión, la naturaleza del requerimiento, y la razón por la cual la gerencia ha llegado a la conclusión de que su cumplimiento sería tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual; y 
(b) para cada periodo presentado, los ajustes a cada partida de los estados financieros que la gerencia haya concluido que serían necesarios para lograr una presentación razonable. 
24 Para los fines de los párrafos 19 a 23, una partida entraría en conflicto con el objetivo de los estados financieros cuando no representase de una forma fidedigna las transacciones, así como los otros sucesos y condiciones que debiera representar, o pudiera razonablemente esperarse que representara y, en consecuencia, fuera probable que influyera en las decisiones económicas tomadas por los usuarios de los estados financieros. Al evaluar si el cumplimiento de un requerimiento específico, establecido en una NIIF, sería tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual, la gerencia considerará: 
(a) por qué no se alcanza el objetivo de los estados financieros, en las circunstancias particulares que se están sopesando; y 
(b) la forma en que las circunstancias de la entidad difieren de las que se dan en otras entidades que cumplen con ese requerimiento. Si otras entidades cumplieran con ese requerimiento en circunstancias similares, existirá la presunción refutable de que el cumplimiento del requerimiento, por parte de la entidad, no sería tan engañoso como para entrar en conflicto con el objetivo de los estados financieros establecido en el Marco Conceptual. 
HIPÓTESIS DE NEGOCIO
 25 Al elaborar los estados financieros, la gerencia evaluará la capacidad que tiene una entidad para continuar en funcionamiento. Una entidad elaborará los estados financieros bajo la hipótesis de negocio en marcha, a menos que la gerencia pretenda liquidar la entidad o cesar en su actividad, o bien no exista otra alternativa más realista que proceder de una de estas formas. Cuando la gerencia es conocedora, al realizar su evaluación, de incertidumbres significativa relacionadas con sucesos o condiciones que pudieran arrojar dudas significativas sobre la capacidad de la entidad de continuar como negocio en marcha, la entidad revelará esas incertidumbres. Cuando una entidad no prepare los estados financieros bajo la hipótesis de negocio en marcha, revelará ese hecho, junto con las hipótesis sobre las que han sido elaborados y las razones por las que la entidad no se considera como un negocio en marcha. 
26 Al evaluar si la hipótesis de negocio en marcha resulta apropiada, la gerencia tendrá en cuenta toda la información disponible sobre el futuro, que deberá cubrir al menos los doce meses siguientes a partir del final del periodo sobre el que se informa, sin limitarse a dicho periodo. El grado de detalle de las consideraciones dependerá de los hechos que se presenten en cada caso. Cuando una entidad tenga un historial de operaciones rentable, así como un pronto acceso a recursos financieros, la entidad podrá concluir que la utilización de la hipótesis de negocio en marcha es apropiada, sin realizar un análisis detallado. En otros casos, puede ser necesario que la gerencia, antes de convencerse a sí misma de que la hipótesis de negocio en marcha es apropiada, deba ponderar una amplia gama de factores relacionados con la rentabilidad actual y esperada, el calendario de pagos de la deuda y las fuentes potenciales de sustitución de la financiación existente. 
BASE CONTABLE DE ACUMULACIÓN (DEVENGO) 
27 Una entidad elaborará sus estados financieros, excepto en lo relacionado con la información sobre flujos de efectivo, utilizando la base contable de acumulación (o devengo). 
28 Cuando se utiliza la base contable de acumulación (devengo), una entidad reconocerá partidas como activos, pasivos, patrimonio, ingresos y gastos (los elementos de los estados financieros), cuando éstas satisfagan las definiciones y los criterios de reconocimiento previstos para tales elementos en el Marco Conceptual. 
 MATERIALIDAD O IMPORTANCIA RELATIVA Y AGREGACIÓN DE DATOS
29 Una entidad presentará por separado cada clase significativa de partidas similares. Una entidad presentará por separado las partidas de naturaleza o función distinta, a menos que no tengan importancia relativa. 
30 Los estados financieros son el producto del procesamiento de un gran número de transacciones y otros sucesos, que se agrupan por clases de acuerdo con su naturaleza o función. La etapa final del proceso de agregación y clasificación es la presentación de datos condensados y clasificados, que constituyen las partidas de los estados financieros. Si una partida concreta careciese de importancia relativa por sí sola, se agregará con otras partidas, ya sea en los estados financieros o en las notas. 
30ª Una partida que no tenga la suficiente importancia relativa como para justificar su presentación separada en esos estados financieros puede justificar su presentación separada en las notas. Al aplicar esta y otras NIIF una entidad decidirá, teniendo en consideración todos los hechos y circunstancias relevantes, la forma en que agrega la información en los estados financieros, los cuales incluyen a las notas. Una entidad no reducirá la comprensibilidad de sus estados financieros ocultando información significativa en información sin importancia relativa o agrupando partidas importantes que tienen diferentes naturalezas o funciones. 
31 Algunas NIIF especifican la información que se requiere incluir en los estados financieros, los cuales incluyen a las notas. No es necesario que una entidad revele información específica requerida por una NIIF si la información procedente de esa revelación carece de importancia relativa. Este es el caso incluso si la NIIF contiene una lista de requerimientos específicos o los describe como requerimientos mínimos. Una entidad decidirá también revelar o no información adicional, cuando el cumplimiento con los requerimientos específicos de las NIIF resulte insuficiente para permitir a los usuarios de los estados financieros comprender el impacto de transacciones concretas, así como de otros sucesos y condiciones, sobre la situación y el rendimiento financieros de la entidad. 
COMPENSACIÓN 
32 Una entidad no compensará activos con pasivos o ingresos con gastos a menos que así lo requiera o permita una NIIF. 
33 Una entidad informará por separado sobre sus activos y pasivos e ingresos y gastos. La compensación en el estado (o estados) del resultado del periodo y otro resultado integral o de situación financiera, excepto cuando la compensación refleja la sustancia de la transacción u otro suceso, limita la capacidad de los usuarios para comprender las transacciones y otros sucesos y condiciones que se hayan producido, así como para evaluar los flujos futuros de efectivo de la entidad. La medición por el neto en el caso de los activos sujetos a correcciones valorativas —por ejemplo, correcciones por deterioro del valor de inventarios por obsolescencia y de las cuentas por cobrar de dudoso cobro— no es una compensación.
34 La NIIF 15 Ingresos de Actividades Ordinarias procedentes de Contratos con Clientes requiere que una entidad mida los ingresos de actividades ordinarias procedentes de contratos con clientes por la contraprestación a la que espera tener derecho a cambio de transferir los bienes o servicios comprometidos. Por ejemplo, el importe de ingresos de actividades ordinarias reconocidos refleja cualesquiera descuentos comerciales y rebajas por volumen de ventas que permita la entidad. Una entidad lleva a cabo, en el curso de sus actividades ordinarias, otras transacciones que no generan ingresos de actividades ordinarias, sino que son accesorias con respecto a las actividades principales que generan estos ingresos. Una entidad presentará los resultados de estas transacciones compensando los ingresos con los gastos relacionados que genere la misma operación, siempre que dicha presentación refleje el fondo de la transacción u otro suceso. Por ejemplo: 
(a) una entidad presentará las ganancias y pérdidas por la disposición de activos no corrientes, incluyendo inversiones y activos de operación, deduciendo del importe recibido importe de la contraprestación por dicha disposición el importe en libros del activo y los gastos de venta correspondientes; y 
(b) una entidad podrá compensar los desembolsos relativos a las provisiones reconocidas de acuerdo con la NIC 37 Provisiones, Pasivos Contingentes y Activos Contingentes, que hayan sido reembolsados a la entidad como consecuencia de un acuerdo contractual con otra parte (por ejemplo, un acuerdo de garantía de productos cubierto por un proveedor) con los reembolsos relacionados. 
35 Además, una entidad presentará en términos netos las ganancias y pérdidas que procedan de un grupo de transacciones similares, por ejemplo, las ganancias y pérdidas por diferencias de cambio, o las derivadas de instrumentos financieros mantenidos para negociar. Sin embargo, una entidad presentará estas ganancias y pérdidas por separado si tienen importancia relativa. 
FRECUENCIA DE LA INFORMACIÓN 
36 Una entidad presentará un juego completo de estados financieros (incluyendo información comparativa) al menos anualmente. Cuando una entidad cambie el cierre del periodo sobre el que informa y presente los estados financieros para un periodo contable superior o inferior a un año, revelará, además del periodo cubierto por los estados financieros: 
(a) la razón para utilizar un periodo de duración inferior o superior; y 
(b) el hecho de que los importes presentados en los estados financieros no son totalmente comparables. 
37 Normalmente, una entidad prepara, de forma coherente en el tiempo, estados financieros que comprenden un periodo anual. No obstante, determinadas entidades prefieren informar, por razones prácticas, sobre periodos de 52 semanas. Esta Norma no prohíbe esta práctica.
INFORMACIÓN COMPARATIVA 
Información comparativa mínima 
38 A menos que las NIIF permitan o requieran otra cosa, una entidad revelará información comparativa respecto del periodo anterior para todos los importes incluidos en los estados financieros del periodo corriente. Una entidad incluirá información comparativa para la información descriptiva y narrativa, cuando esto sea relevante para la comprensión de los estados financieros del periodo corriente. 38ª Una entidad presentará, como mínimo, dos estados de situación financiera, dos estados del resultado y otro resultado integral del periodo, dos estados del resultado del periodo separados (si los presenta), dos estados de flujos de efectivo y dos estados de cambios en el patrimonio, y notas relacionadas. 
38b En algunos casos, la información narrativa proporcionada en los estados financieros de periodo(s) inmediatamente anterior(es) continúa siendo relevante en el periodo actual. Por ejemplo, una entidad revelará en el periodo actual detalles de una disputa legal cuyo resultado era incierto al final del periodo inmediato anterior y que todavía está pendiente de resolución. Los usuarios se beneficiarán de la información revelada sobre la incertidumbre existente al final del periodo inmediato anterior, así como de la relativa a los pasos dados durante el periodo para resolver dicha incertidumbre. 
Información comparativa adicional 
38c Una entidad puede presentar información comparativa, además de los estados financieros comparativos mínimos requeridos por las NIIF, en la medida en que esa información se prepare de acuerdo con las NIIF. Esta información comparativa puede consistir en uno o más estados a los que hace referencia el párrafo 10, pero no necesita comprender un juego completo de estados financieros. Cuando este sea el caso, la entidad presentará información relacionada en una nota a dichos estados adicionales. 
38d, Por ejemplo, una entidad puede presentar un tercer estado del resultado del periodo y otro resultado integral (presentando, de ese modo, el periodo actual, el periodo inmediato anterior y un periodo comparativo adicional). Sin embargo, no se requiere que la entidad presente un tercer estado de situación financiera, un tercer estado de flujos de efectivo o un tercer estado de cambios en el patrimonio (es decir, un estado financiero adicional comparativo). Se requiere que la entidad presente, en las notas a los estados financieros, información comparativa relacionada con el estado del resultado y otro resultado integral adicional. 
39 a 40[Eliminado] 
CAMBIOS EN POLÍTICAS CONTABLES, REEXPRESIÓN RETROACTIVA O RECLASIFICACIÓN 
40ª Una entidad presentará un tercer estado de situación financiera al comienzo del periodo inmediato anterior, además de los estados financieros comparativos mínimos requeridos por el párrafo 38A si:
(a) aplica una política contable de forma retroactiva, realiza una reexpresión retroactiva de partidas en sus estados financieros o reclasifica partidas en éstos; y (b) la aplicación retroactiva, reexpresión retroactiva o reclasificación tiene un efecto material (de importancia relativa) sobre la información en el estado de situación financiera al comienzo del periodo inmediato anterior. 
40b En las circunstancias descritas en el párrafo 40A, una entidad presentará tres estados de situación financiera, como sigue: 
(a) al cierre del periodo actual; 
(b) al cierre del periodo inmediato anterior; y 
(c) al comienzo del periodo inmediato anterior. 
40c Cuando se requiera que una entidad presente un estado de situación financiera adicional de acuerdo con el párrafo 40A, deberá revelar la información requerida por los párrafos 41 a 44 y la NIC 8. Sin embargo, no necesitará presentar las notas relativas al estado de situación financiera de apertura al comienzo del periodo inmediato anterior.
40d La fecha de ese estado de situación financiera de apertura será la del comienzo del periodo inmediato anterior, independientemente de si los estados financieros de una entidad presentan información comparativa para periodos anteriores (como permite el párrafo 38C). 
41 Cuando la entidad modifique la presentación o la clasificación de partidas en sus estados financieros, también reclasificará los importes comparativos, a menos que resulte impracticable hacerlo. Cuando la una entidad reclasifique importes comparativos, revelará (incluyendo el comienzo del periodo inmediato anterior): 
(a) la naturaleza de la reclasificación; 
(b) el importe de cada partida o clase de partidas que se han reclasificado; y 
(c) la razón de la reclasificación. 
42 Cuando la reclasificación de los importes comparativos sea impracticable, la entidad revelará: (a) la razón para no reclasificar los importes; y (b) la naturaleza de los ajustes que tendrían que haberse efectuado si los importes hubieran sido reclasificados. 
43 El mejoramiento de la comparabilidad de la información entre periodos ayuda a los usuarios en la toma de decisiones económicas, sobre todo al permitir la evaluación de tendencias en la información financiera con propósitos predictivos. En algunas circunstancias, la reclasificación de la información comparativa de periodos anteriores concretos para conseguir la comparabilidad con las cifras del periodo corriente es impracticable. Por ejemplo, una entidad puede no haber calculado algunos datos en periodos anteriores, de una manera que permita su reclasificación y la reproducción de la información es, por tanto, impracticable. 
44 La NIC 8 establece los ajustes a realizar en la información comparativa requerida, cuando una entidad cambia una política contable o corrige un error. 
UNIFORMIDAD EN LA PRESENTACIÓN 
45 Una entidad mantendrá la presentación y clasificación de las partidas en los estados financieros de un periodo a otro, a menos que: (a) tras un cambio en la naturaleza de las actividades de la entidad o una revisión de sus estados financieros, se ponga de manifiesto que sería más apropiada otra presentación u otra clasificación, tomando en consideración los criterios para la selección y aplicación de políticas contables de la NIC 8; o 
(b) una NIIF requiera un cambio en la presentación. 
46 Por ejemplo, una adquisición o disposición significativa, o una revisión de la presentación de los estados financieros, podrían sugerir que éstos necesitan ser presentados de forma diferente. Una entidad sólo cambiará la presentación de sus estados financieros cuando dicho cambio proporcione información fiable y más relevante para los usuarios de los estados financieros, y la nueva estructura tenga visos de continuidad, de modo que la comparabilidad no quede perjudicada. Cuando se realicen estos cambios en la presentación, una entidad reclasificará su información comparativa de acuerdo con los párrafos 41 y 42. 
ESTRUCTURA Y CONTENIDO
INTRODUCCIÓN
 47 Esta Norma requiere revelar determinada información en el estado de situación financiera o en el estado (o estados) del resultado del periodo y otro resultado integral, o en el estado de cambios en el patrimonio, y requiere la revelación de partidas en estos estados o en las notas. La NIC 7 Estado de Flujos de Efectivo establece los requerimientos de presentación para la información sobre el flujo de efectivo. 
48 Esta Norma a menudo utiliza el término “información a revelar” en un sentido amplio, incluyendo partidas presentadas en los estados financieros. Otras NIIF también requieren revelar información. A menos que en esta Norma se especifique lo contrario o en otra NIIF esta información a revelar podría estar en los estados financieros. 
IDENTIFICACIÓN DE LOS ESTADOS FINANCIEROS 
49 Una entidad identificará claramente los estados financieros y los distinguirá de cualquier otra información publicada en el mismo documento.  
50 Las NIIF se aplican solo a los estados financieros, y no necesariamente a otra información presentada en un informe anual, en las presentaciones a entes reguladores o en otro documento. Por tanto, es importante que los usuarios sean capaces de distinguir la información que se prepara utilizando las NIIF de cualquier otra información que, aunque les pudiera ser útil, no está sujeta a los requerimientos de éstas. 
51 Una entidad identificará claramente cada estado financiero y las notas. Además, una entidad mostrará la siguiente información en lugar destacado, y la repetirá cuando sea necesario para que la información presentada sea comprensible: (a) el nombre de la entidad u otra forma de identificación de la misma, así como los cambios relativos a dicha información desde el final del periodo precedente; (b) si los estados financieros pertenecen a una entidad individual o a un grupo de entidades; (c) la fecha del cierre del periodo sobre el que se informa o el periodo cubierto por el juego de los estados financieros o notas; (d) la moneda de presentación, tal como se define en la NIC 21; y (e) el grado de redondeo practicado al presentar las cifras de los estados financieros. 
52 Una entidad cumple con los requerimientos del párrafo 51 a través de la presentación de encabezamientos apropiados para las páginas, estados, notas, columnas y similares. Se requiere la utilización del juicio profesional para determinar la mejor forma de presentar esta información. Por ejemplo, cuando una entidad presenta los estados financieros electrónicamente no siempre no siempre se utilizan páginas separadas; en este caso, una entidad presentará las partidas anteriores para asegurar que la información incluida en los estados financieros puede entenderse.
53 Con frecuencia, una entidad hará más comprensibles los estados financieros presentando las cifras en miles o millones de unidades monetarias de la moneda de presentación. Esto será aceptable en la medida en que la entidad revele el grado de redondeo practicado y no omita información material o de importancia relativa al hacerlo. 
ESTADO DE SITUACIÓN FINANCIERA 
INFORMACIÓN A PRESENTAR EN EL ESTADO DE SITUACIÓN FINANCIERA 
54 El estado de situación financiera incluirá partidas que presenten los siguientes importes: 
(a) propiedades, planta y equipo; 
(b) propiedades de inversión; 
(c) activos intangibles; 
(d) activos financieros (excluidos los importes mencionados en los apartados (e), (h) e (i)); 
(da) grupos de contratos dentro del alcance de la NIIF 17 que son activos, desglosados como requiere el párrafo 78 de la NIIF 17; 
(e) inversiones contabilizadas utilizando el método de la participación; 
(f) activos biológicos dentro del alcance de la NIC 41 Agricultura; 
(g) inventarios; 
(h) deudores comerciales y otras cuentas por cobrar;
(i) efectivo y equivalentes al efectivo; 
(j) el total de activos clasificados como mantenidos para la venta y los activos incluidos en grupos de activos para su disposición, que se hayan clasificado como mantenidos para la venta de acuerdo con la NIIF 5 Activos No corrientes Mantenidos para la Venta y Operaciones Discontinuadas; 
(k) acreedores comerciales y otras cuentas por pagar; 
(l) provisiones; 
(m) pasivos financieros [excluyendo los importes mencionados en los apartados (k) y (l)]; 
(ma) grupos de contratos dentro del alcance de la NIIF 17 que son pasivos, desglosados como requiere el párrafo 78 de la NIIF 17; 
(n) pasivos y activos por impuestos corrientes, según se definen en la NIC 12 Impuesto a las Ganancias; 
(o) pasivos y activos por impuestos diferidos, según se definen en la NIC 12; 
(p) pasivos incluidos en los grupos de activos para su disposición clasificados como mantenidos para la venta de acuerdo con la NIIF 5; 
(q) participaciones no controladoras, presentadas dentro del patrimonio; y 
(r) capital emitido y reservas atribuibles a los propietarios de la controladora. 
55 Una entidad presentará en el estado de situación financiera partidas adicionales (incluyendo por desagregación las partidas enumeradas en el párrafo 54), encabezados y subtotales, cuando esa presentación sea relevante para comprender su situación financiera. 
55ª Cuando una entidad presente subtotales de acuerdo con el párrafo 55, dichos subtotales: (a) comprenderán partidas formadas por importes reconocidos y medidos de acuerdo con las NIIF;  (b) se presentarán y denominarán de forma que las partidas que constituyen el subtotal sean claras y comprensibles; (c) serán congruentes de periodo a periodo, de acuerdo con el párrafo 45; y (d) no se mostrarán con mayor importancia que los subtotales y totales requeridos en las NIIF para el estado de situación financiera. 
56 Cuando una entidad presente en el estado de situación financiera los activos clasificados en corrientes o no corrientes, y los pasivos en corrientes o no corrientes como clasificaciones separadas no clasificará los activos (o los pasivos) por impuestos diferidos como activos (o pasivos) corrientes. 
57 Esta Norma no prescribe ni el orden ni el formato en que una entidad presentará las partidas. El párrafo 54 simplemente enumera partidas que son lo suficientemente diferentes, en su naturaleza o función, como para justificar su presentación por separado en el estado de situación financiera. Además: 
(a) Se añadirán otras partidas cuando el tamaño, naturaleza o función de una partida o grupo de partidas sea tal que la presentación por separado resulte relevante para comprender la situación financiera de la entidad; y 
(b) las denominaciones utilizadas y la ordenación de las partidas o agrupaciones de partidas similares podrán ser modificadas de acuerdo con la naturaleza de la entidad y de sus transacciones, para suministrar información que sea relevante para la comprensión de la situación financiera de la entidad. Por ejemplo, una institución financiera puede modificar las denominaciones anteriores para proporcionar información que sea relevante para sus operaciones. 
58 Una entidad decidirá si ha de presentar partidas adicionales de forma separada en función de una evaluación de: (a) la naturaleza y la liquidez de los activos; (b) la función de los activos dentro de la entidad; y (c) los importes, la naturaleza y el plazo de los pasivos.
59 La utilización de diferentes bases de medición para distintas clases de activos sugiere que su naturaleza o su función difieren y, en consecuencia, que deben ser presentados como partidas separadas. Por ejemplo, ciertas clases de propiedades, planta y equipo pueden contabilizarse al costo histórico, o por sus importes revaluados, de acuerdo con la NIC 16. 
DISTINCIÓN ENTRE PARTIDAS CORRIENTES Y NO CORRIENTES 
60 Una entidad presentará sus activos corrientes y no corrientes, así como sus pasivos corrientes y no corrientes, como categorías separadas en su estado de situación financiera, de acuerdo con los párrafos 66 a 76, excepto cuando una presentación basada en el grado de liquidez proporcione una información fiable que sea más relevante. Cuando se aplique esa excepción, una entidad presentará todos los activos y pasivos ordenados atendiendo a su liquidez. 
61 Independientemente del método de presentación adoptado, una entidad revelará el importe esperado a recuperar o a cancelar después de los doce meses para cada partida de activo o pasivo que combine importe a recuperar o a cancelar: (a) dentro de los doce meses siguientes después del periodo sobre el que se informa, y (b) después de doce meses tras esa fecha. 
62 Cuando una entidad suministra bienes o servicios dentro de un ciclo de operación claramente identificable, la clasificación separada de los activos y pasivos corrientes y no corrientes, en el estado de situación financiera, proporciona una información útil al distinguir los activos netos que están circulando continuamente como capital de trabajo, de los utilizados en las operaciones a largo plazo de la entidad. Esta distinción servirá también para destacar tanto los activos que se espera realizar en el transcurso del ciclo normal de la operación, como los pasivos que se deban liquidar en ese mismo periodo. 
63 Para algunas entidades, tales como las instituciones financieras, una presentación de activos y pasivos en orden ascendente o descendente de liquidez proporciona información fiable y más relevante que la presentación corriente-no corriente, debido a que la entidad no suministra bienes ni presta servicios dentro de un ciclo de operación claramente identificable. 
64 Se permite que, al aplicar el párrafo 60, una entidad presente algunos de sus activos y pasivos empleando la clasificación corriente/no corriente, y otros en orden a su liquidez, siempre que esto proporcione información fiable y más relevante. La necesidad de mezclar las bases de presentación podría aparecer cuando una entidad realice actividades diferentes. 
65 La información sobre las fechas esperadas de realización de los activos y pasivos es útil para evaluar la liquidez y la solvencia de una entidad. La NIF 7 Instrumentos Financieros: Informaciones a Revelar requiere la revelación de información acerca de las fechas de vencimiento de los activos financieros y pasivos financieros. Los activos financieros incluyen las cuentas de deudores comerciales y otras cuentas por cobrar, y los pasivos financieros las cuentas de acreedores comerciales y otras cuentas por pagar. También será de utilidad la información acerca de la fecha esperada de recuperación de los activos no monetarios, como los inventarios, y la fecha esperada de cancelación de pasivos como las provisiones, con independencia de que se los clasifiquen como corrientes o no corrientes. Por ejemplo, una entidad revelará los importes de los inventarios que espera realizar después de los doce meses después del periodo sobre el que se informa. 
ACTIVOS CORRIENTES 
66 Una entidad clasificará un activo como corriente cuando: 
(a) espera realizar el activo, o tiene la intención de venderlo o consumirlo en su ciclo normal de operación; 
(b) mantiene el activo principalmente con fines de negociación; 
(c) espera realizar el activo dentro de los doce meses siguientes al periodo sobre el que se informa; o 
(d) el activo es efectivo o equivalente al efectivo (como se define en la NIC 7), a menos que éste se encuentre restringido y no pueda ser intercambiado ni utilizado para cancelar un pasivo por un ejercicio mínimo de doce meses después del ejercicio sobre el que se informa. Una entidad clasificará todos los demás activos como no corrientes. 
67 En esta Norma, el término “no corriente” incluye activos tangibles, intangibles y financieros que por su naturaleza son a largo plazo. No está prohibido el uso de descripciones alternativas siempre que su significado sea claro. 
68 El ciclo normal de la operación de una entidad es el periodo comprendido entre la adquisición de los activos que entran en el proceso productivo, y su realización en efectivo o equivalentes al efectivo. Cuando el ciclo normal de la operación no sea claramente identificable, se supondrá que su duración es de doce meses. Los activos corrientes incluyen activos (tales como inventarios y deudores comerciales) que se venden, consumen o realizan, dentro del ciclo normal de la operación, incluso cuando no se espere su realización dentro del periodo de doce meses a partir de la fecha del periodo de presentación. Los activos corrientes también incluyen activos que se mantienen fundamentalmente para negociar (por ejemplo, algunos activos financieros que cumplen la definición de mantenidos para negociar de la NIIF 9) y la parte a corto plazo de los activos financieros no corrientes. 
PASIVOS CORRIENTES 
69 Una entidad clasificará un pasivo como corriente cuando: 
(a) espera liquidar el pasivo en su ciclo normal de operación; 
(b) mantiene el pasivo principalmente con fines de negociación; 
(c) el pasivo debe liquidarse dentro de los doce meses siguientes a la fecha del periodo sobre el que se informa; o 
(d) no tiene un derecho incondicional para aplazar la cancelación del pasivo durante, al menos, los doce meses siguientes a la fecha del periodo sobre el que se informa (véase el párrafo 73). Las condiciones de un pasivo que puedan dar lugar, a elección de la otra parte, a su liquidación mediante la emisión de instrumentos de patrimonio, no afectan a su clasificación. 
Una entidad clasificará todos los demás pasivos como no corrientes. 
70 Algunos pasivos corrientes, tales como las cuentas comerciales por pagar y otros pasivos acumulados (devengados), ya sea por costos de personal o por otros costos de operación, integran el capital de trabajo utilizado en el ciclo normal de operación de la entidad. Una entidad clasificará estas partidas de operación como pasivos corrientes, aunque se vayan a liquidar después de los doce meses de la fecha del periodo sobre el que se informa. Para la clasificación de los activos y pasivos de una entidad se aplicará el mismo ciclo normal de operación. Cuando el ciclo normal de la operación no sea claramente identificable, se supondrá que su duración es de doce meses. 
71 Otros tipos de pasivos corrientes no se cancelan como parte del ciclo normal de la operación, pero deben liquidarse dentro de los doce meses siguientes a la fecha del periodo de presentación o se mantienen fundamentalmente con propósitos de negociación. Son ejemplos de este tipo algunos pasivos financieros que cumplen la definición como mantenidos para negociar de acuerdo con la NIIF 9, los descubiertos bancarios, y la parte corriente de los pasivos financieros no corrientes, los dividendos a pagar, los impuestos sobre las ganancias y otras cuentas por pagar no comerciales. Los pasivos financieros que proporcionan financiación a largo plazo (es decir, no forman parte del capital de trabajo utilizado en el ciclo normal de operación de la entidad) y que no deban liquidarse dentro de los doce meses a partir de la fecha del periodo de presentación, son pasivos no corrientes, sujetos a las condiciones de los párrafos 74 y 75. 
72 Una entidad clasificará sus pasivos financieros como corrientes cuando deban liquidarse dentro de los doce meses siguientes a la fecha del periodo sobre el que informa, aunque: (a) el plazo original del pasivo fuera un periodo superior a doce meses; y (b) se haya concluido un acuerdo de refinanciación o de reestructuración de los pagos a largo plazo después de la fecha del periodo sobre el que se informa y antes de que los estados financieros sean autorizados para su publicación.
73 Si una entidad tuviera la expectativa y, además, la facultad de renovar o refinanciar una obligación al menos durante los doce meses siguientes a la fecha del periodo sobre el que se informa, de acuerdo con las condiciones de financiación existentes, clasificará la obligación como no corriente, aun cuando de otro modo venza en un período más corto. No obstante, cuando la refinanciación o extensión del plazo no sea una facultad de la entidad (por ejemplo, si no existiese un acuerdo de refinanciación), la entidad no tendrá en cuenta la refinanciación potencial y la obligación se clasificará como corriente. 
74 Cuando una entidad infrinja una disposición contenida en un contrato de préstamo a largo plazo al final del periodo sobre el que se informa o antes con el efecto de que el pasivo se convierta en exigible a voluntad del prestamista, tal pasivo se clasificará como corriente, incluso si el prestamista hubiera acordado, después de la fecha del periodo sobre el que se informa y antes de que los estados financieros sean autorizados para su publicación, no exigir el pago como consecuencia de la infracción. Una entidad clasificará el pasivo como corriente porque, al final del periodo sobre el que se informa, no tiene el derecho incondicional de aplazar la cancelación del pasivo durante al menos, doce meses tras esa fecha. 
75 Sin embargo, una entidad clasificará el pasivo como no corriente si el prestamista hubiese acordado, al final del periodo sobre el que se informa, la concesión de un periodo de gracia que finalice al menos doce meses después de esa fecha, dentro de cuyo plazo la entidad puede rectificar la infracción y durante el cual el prestamista no puede exigir el reembolso inmediato. 
76 Con respecto a los préstamos clasificados como pasivos corrientes, si los sucesos que siguen ocurriesen entre el final del periodo sobre el que se informa y la fecha en que los estados financieros son autorizados para su publicación, esos sucesos se revelarán como hechos ocurridos después de la fecha de balance que no implican ajustes, de acuerdo con la NIC 10 Hechos Ocurridos Después del Periodo sobre el que se Informa: (a) refinanciación a largo plazo; (b) rectificación de la infracción del contrato de préstamo a largo plazo; y (c) concesión, por parte del prestamista, de un periodo de gracia para rectificar la infracción relativa al contrato de préstamo a largo plazo que finalice al menos doce meses después del periodo sobre el que se informa. 
INFORMACIÓN A PRESENTAR EN EL ESTADO DE SITUACIÓN FINANCIERA O EN LAS NOTAS 
77 Una entidad revelará, ya sea en el estado de situación financiera o en las notas, subclasificaciones adicionales de las partidas presentadas, clasificadas de una manera que sea apropiada para las operaciones de la entidad. 
78 El detalle suministrado en las subclasificaciones dependerá de los requerimientos de las NIIF, así como del tamaño, la naturaleza y la función de los importes afectados. Para decidir los criterios de subclasificación, una entidad utilizará también los factores descritos en el párrafo 58. El nivel de información suministrada variará para cada partida, por ejemplo: 
(a) las partidas de propiedades, planta y equipo se desagregarán por clases, de acuerdo con la NIC 16; 
(b) las cuentas por cobrar se desagregarán en importes por cobrar de clientes comerciales, de partes relacionadas, anticipos y otros importes; 
(c) los inventarios se desagregarán, de acuerdo con la NIC 2 Inventarios, en clasificaciones tales como mercaderías, materias primas, materiales, productos en curso y productos terminados; 
(d) las provisiones se desglosarán, de forma que se muestren por separado las que corresponden a provisiones por beneficios a empleados y el resto; y 
(e) el capital y las reservas se desagregarán en varias clases, tales como capital pagado, primas de emisión y reservas. 
79 Una entidad revelará lo siguiente, sea en el estado de situación financiera, en el estado de cambios en el patrimonio o en las notas: 
(a) para cada clase de capital en acciones: 
(i) el número de acciones autorizadas; 
(ii) el número de acciones emitidas y pagadas totalmente, así como las emitidas, pero aún no pagadas en su totalidad; 
(iii) el valor nominal de las acciones, o el hecho de que no tengan valor nominal; 
(iv) una conciliación entre el número de acciones en circulación al principio y al final del periodo; 
(v) los derechos, privilegios y restricciones correspondientes a cada clase de acciones, incluyendo las restricciones sobre la distribución de dividendos y el reembolso del capital; 
(vi) las acciones de la entidad que estén en su poder o bien en el de sus subsidiarias o asociadas; y 
(vii) las acciones cuya emisión está reservada como consecuencia de la existencia de opciones o contratos para la venta de acciones, incluyendo las condiciones e importes correspondientes; y 
(b) una descripción de la naturaleza y destino de cada partida de reservas que figure en el patrimonio; 
80 Una entidad sin capital en acciones, tal como las que responden a una fórmula societaria o fiduciaria, revelará información equivalente a la requerida en el párrafo 79(a), mostrando los cambios producidos durante el periodo en cada una de las categorías que componen el patrimonio y los derechos, privilegios y restricciones asociados a cada una. 
80ª Si una entidad ha reclasificado (a) un instrumento financiero con opción de venta clasificado como un instrumento de patrimonio, o (b) un instrumento que impone a la entidad una obligación de entregar a terceros una participación proporcional de los activos netos de la entidad solo en el momento de la liquidación y se clasifica como un instrumento de patrimonio entre pasivos financieros y patrimonio, revelará el importe reclasificado dentro y fuera de cada categoría (pasivo financiero o patrimonio), y el momento y razón de esa reclasificación. 
ESTADO DEL RESULTADO DEL PERIODO Y OTRO RESULTADO INTEGRAL 81 [Eliminado] 
81ª El estado del resultado del periodo y otro resultado integral (estado del resultado integral) presentará, además de las secciones del resultado del periodo y otro resultado integral: (a) el resultado del periodo; (b) otro resultado integral total; (c) el resultado integral del periodo, siendo el total del resultado del periodo y otro resultado integral. Si una entidad presenta un estado del resultado del periodo separado, no presentará la sección del resultado del periodo en el estado que presente el resultado integral. 
81b Una entidad presentará las siguientes partidas, además de las secciones del resultado del periodo y otro resultado integral, como distribuciones del resultado del periodo y otro resultado integra para el periodo: (a) resultado del periodo atribuible a: (i) participaciones no controladoras y (ii) propietarios de la controladora. (b) resultado integral del periodo atribuible a: (i) participaciones no controladoras y (ii) propietarios de la controladora. Si una entidad presenta el resultado del periodo en un estado separado, presentará (a) en ese estado. 
INFORMACIÓN A PRESENTAR EN LA SECCIÓN DEL RESULTADO DEL PERIODO O EN EL ESTADO DEL RESULTADO DEL PERIODO 
82 Además de las partidas requeridas por otras NIIF, la sección del resultado del periodo o el estado del resultado del periodo incluirán las partidas que presenten los importes siguientes para el periodo: (a) ingresos de actividades ordinarias, presentando por separado: 
ingresos por intereses calculados utilizando el método del interés efectivo; y 
(ii) ingresos de actividades ordinarias por seguros (véase la NIIF 17); 
(aa) ganancias y pérdidas que surgen de la baja en cuentas de activos financieros medidos al costo amortizado;
(ab) gastos del servicio de seguro de contratos emitidos dentro del alcance de la NIIF 17 (véase la NIIF 17); 
(ac) ingresos o gastos por contratos de reaseguro mantenidos (véase la NIIF 17); 
(b) costos financieros; 
(ba) pérdidas por deterioro de valor (incluyendo reversiones de pérdidas por deterioro de valor o ganancias por deterioro de valor) determinados de acuerdo con la Sección 5.5 de la NIIF 9; 
(bb) gastos o ingresos financieros por seguros de contratos emitidos dentro del alcance de la NIIF 17 (véase la NIIF 17); 
(bc) ingresos o gastos financieros por contratos de reaseguro mantenidos (véase la NIIF 17); 
(c) participación en el resultado del periodo de las asociadas y negocios conjuntos que se contabilicen por el método de la participación; 
(ca) si un activo financiero se reclasifica desde la categoría de medición del costo amortizado, y se pasa a medir a valor razonable con cambios en resultados, cualquier ganancia o pérdida que surja de una diferencia entre el costo amortizado anterior del activo financiero y su valor razonable en la fecha de la reclasificación (como se define en la NIIF 9); 
(cb) si un activo financiero se reclasifica desde la categoría de medición de valor razonable con cambios en otro resultado integral de forma que se mida a valor razonable con cambios en resultados, las ganancias o pérdidas acumuladas anteriormente reconocidas en otro resultado integral que se reclasifican al resultado del periodo; 
(d) gasto por impuestos; 
(e) [eliminado] (ea) un importe único para el total de operaciones discontinuadas (véase la NIIF 5). 
(f) a (i) [eliminado] 
INFORMACIÓN A PRESENTAR EN LA SECCIÓN DE OTRO RESULTADO INTEGRAL 
82ª La sección del otro resultado integral presentará partidas por el importe para el periodo de: 
(a)	partidas de otro resultado integral [excluyendo los importes del párrafo (b)], clasificadas por naturaleza y agrupadas en aquellas que, de acuerdo con otras NIIF: 
(i) no se reclasificarán posteriormente al resultado del periodo; y 
(ii) se reclasificarán posteriormente al resultado del periodo, cuando se cumplan ciertas condiciones específicas. 
(b)	la participación en el otro resultado integral de asociadas y negocios conjuntos contabilizados utilizando el método de la participación, separada en la participación en partidas que, de acuerdo con otras NIIF: (i) no se reclasificarán posteriormente al resultado del periodo; y 
(c)	(ii) se reclasificarán posteriormente al resultado del periodo, cuando se cumplan ciertas condiciones específicas. 
83ª84 [Eliminado] 
85 Una entidad presentará partidas adicionales (incluyendo aquellas por desagregación de las partidas enumeradas en el párrafo 82), encabezados y subtotales en el estado (estados), que presente los resultados del periodo y otro resultado integral, cuando dicha presentación sea relevante para comprender el rendimiento financiero de la entidad. 
85ª Cuando una entidad presente subtotales de acuerdo con el párrafo 85, dichos subtotales: 
(a) comprenderán partidas formadas por importes reconocidos y medidos de acuerdo con las NIIF; 
(b) se presentarán y denominarán de forma que las partidas que constituyen el subtotal sean claras y comprensibles; 
(c) serán congruentes de periodo a periodo, de acuerdo con el párrafo 45; y 
(d) no se mostrarán con mayor importancia que los subtotales y totales requeridos en las NIIF para el estado (estados) que presente el resultado del periodo y otro resultado integral. 
85b Una entidad presentará las partidas en el estado (estados) que presente el resultado del periodo y otro resultado integral que concilien los subtotales presentados de acuerdo con el párrafo 85 con los subtotales o totales requeridos en las NIIF para este estado (estados). 
86 Dado que los efectos de las diferentes actividades, transacciones y otros sucesos de una entidad, difieren en frecuencia, potencial de ganancias o pérdidas y capacidad de predicción, la revelación de información sobre los componentes del rendimiento financiero ayuda a los usuarios a comprender dicho rendimiento financiero logrado, así como a realizar proyecciones a futuro sobre éste. Una entidad incluirá partidas adicionales en los estados que presenten el resultado del periodo y otro resultado integral y modificará las denominaciones y la ordenación de partidas cuando sea necesario para explicar los elementos del rendimiento financiero. Una entidad considerará factores que incluyan la materialidad (importancia relativa) y la naturaleza y función de las partidas de ingreso y gasto. Por ejemplo, una institución financiera puede modificar las denominaciones para proporcionar información que sea relevante para las operaciones de una institución financiera. Una entidad no compensará partidas de ingresos y gastos, a menos que se cumplan los criterios del párrafo 32. 
87 Una entidad no presentará ninguna partida de ingreso o gasto como partidas extraordinarias en los estados que presenten el resultado del periodo y otro resultado integral o en las notas. 
RESULTADO DEL PERIODO 
88 Una entidad reconocerá todas las partidas de ingreso y gasto de un periodo en el resultado a menos que una NIIF requiera o permita otra cosa.
89 Algunas NIIF especifican las circunstancias en las que una entidad reconocerá determinadas partidas fuera del resultado del periodo corriente. La NIC 8 especifica dos de estas circunstancias: la corrección de errores y el efecto de cambios en políticas contables. Otras NIIF requieren o permiten que componentes de otro resultado integral que cumplen la definición de ingreso o gasto proporcionada por el Marco Conceptual se excluyan del resultado (véase el párrafo 7). 
OTRO RESULTADO INTEGRAL DEL PERIODO 
90 Una entidad revelará el importe del impuesto a las ganancias relativo a cada partida de otro resultado integral, incluyendo los ajustes por reclasificación, en el estado del resultado del periodo y otro resultado integral o en las notas. 
91 Una entidad puede presentar las partidas de otro resultado integral: 
(a) netas de los efectos fiscales relacionados, o 
(b) antes de los efectos fiscales relacionados con un importe que muestre el importe acumulado del impuesto a las ganancias relacionado con esas partidas. Si una entidad elige la alternativa (b), distribuirá el impuesto entre las partidas que pueden reclasificarse posteriormente a la sección del resultado del periodo y las que no se reclasificarán posteriormente a esta sección. 
92 Una entidad revelará los ajustes por reclasificación relacionados con los componentes de otro resultado integral. 
93 Otras NIIF especifican si y cuándo reclasificar en resultados los importes previamente reconocidos en otro resultado integral. Estas reclasificaciones se denominan en esta Norma ajustes por reclasificación. Un ajuste por reclasificación se incluye con el componente relacionado de otro resultado integral en el periodo en el que tal ajuste se reclasifica dentro del resultado del periodo. Estos importes pueden haber sido reconocidos en otro resultado integral como ganancias no realizadas en el periodo corriente o en periodos anteriores. Esas ganancias no realizadas deben deducirse de otro resultado integral en el periodo en que las ganancias realizadas se reclasifican dentro del resultado para evitar su inclusión por duplicado en el resultado integral total. 
94 Una entidad puede presentar el ajuste por reclasificación en los estados del resultado del periodo y otro resultado integral o en las notas. Una entidad que presente los ajustes por reclasificación en las notas presentará las partidas de otro resultado integral después de cualquier ajuste por reclasificación relacionado. 
95 Los ajustes por reclasificación surgen, por ejemplo, al disponer un negocio en el extranjero (véase la NIC 21), y cuando algún flujo de efectivo previsto cubierto afecta al resultado del periodo (véase el párrafo 6.5.11(d) de la NIIF 9 en relación con la cobertura de flujos de efectivo).
96 Los ajustes por reclasificación no surgen por cambios en el superávit de revaluación reconocido de acuerdo con la NIC 16 o la NIC 38, o por nuevas mediciones de planes de beneficios definidos reconocidas de acuerdo con la NIC 19. Estos componentes se reconocerán en otro resultado integral y no se reclasificarán en el resultado en periodos posteriores. Los cambios en el superávit de revaluación pueden transferirse a ganancias acumuladas en periodos posteriores a medida que se utiliza el activo o cuando éste se da de baja (véase la NIC 16 y la NIC 38). De acuerdo con la NIIF 9, los ajustes de reclasificación no surgen si una cobertura de flujos de efectivo o la contabilidad del valor temporal de una opción (o el elemento a término de un contrato a término o el diferencial de la tasa de cambio de un instrumento financiero) dan lugar a importes que se eliminan de la reserva de cobertura de flujos de efectivo o de un componente separado de patrimonio, respectivamente, e incluido directamente en el costo inicial u otro importe en libros de un activo o pasivo. Estos importes se transfieren directamente a los activos o pasivos. 
INFORMACIÓN A PRESENTAR EN LOS ESTADOS DEL RESULTADO DEL PERIODO Y OTRO RESULTADO INTEGRAL O EN LAS NOTAS. 
97 Cuando las partidas de ingreso o gasto son materiales (tienen importancia relativa), una entidad revelará de forma separada información sobre su naturaleza e importe. 
98 Entre las circunstancias que darían lugar a revelaciones separadas de partidas de ingresos y gastos están las siguientes: (a) la rebaja de los inventarios hasta su valor neto realizable, o de los elementos de propiedades, planta y equipo hasta su importe recuperable, así como la reversión de tales rebajas; (b) la reestructuración de las actividades de una entidad y la reversión de cualquier provisión para hacer frente a los costos de ella; (c) la disposición de partidas de propiedades, planta y equipo; (d) las disposiciones de inversiones; (e) las operaciones discontinuadas; (f) cancelaciones de pagos por litigios; y (g) otras reversiones de provisiones. 
99 Una entidad presentará un desglose de los gastos reconocidos en el resultado, utilizando una clasificación basada en la naturaleza o en la función de ellos dentro de la entidad, lo que proporcione una información que sea fiable y más relevante. 100 Se recomienda que las entidades presenten el desglose del párrafo 99 en el estado que presente el resultado del periodo y otro resultado integral. 
101 Los gastos se subclasifican para destacar los componentes del rendimiento financiero, que puedan ser diferentes en términos de frecuencia, potencial de ganancia o pérdida y capacidad de predicción. Este desglose se proporciona en una de las dos formas descritas a continuación. 
102 La primera forma de desglose es el método de la “naturaleza de los gastos”. Una entidad agrupará gastos dentro del resultado de acuerdo con su naturaleza (por ejemplo, depreciación, compras de materiales, costos de transporte, beneficios a los empleados y costos de publicidad) y no los redistribuirá atendiendo a las diferentes funciones que se desarrollan en la entidad. Este método resulta fácil de aplicar, porque no es necesario distribuir los gastos en clasificaciones funcionales. Un ejemplo de clasificación que utiliza el método de la naturaleza de los gastos es el siguiente: 
Ingresos de actividades ordinarias                                               X 
Otros ingresos                                                                                X
 Variación en los inventarios de productos terminados
 y en proceso                                                                   X 
Consumos de materias primas y consumibles             X 
Gastos por beneficios a los empleados                        X 
Gastos por depreciación y amortización                     X 
Otros gastos X Total de gastos                                                     (X) 
Ganancia antes de impuestos                                                            X
103 La segunda forma de desglose es el método de la “función de los gastos” o del “costo de las ventas”, y clasifica los gastos de acuerdo con su función como parte del costo de las ventas o, por ejemplo, de los costos de actividades de distribución o administración. Como mínimo una entidad revelará, según este método, su costo de ventas de forma separada de otros gastos. Este método puede proporcionar a los usuarios una información más relevante que la clasificación de gastos por naturaleza, pero la distribución de los costos por función puede requerir asignaciones arbitrarias, e implicar la realización de juicios de importancia. Un ejemplo de clasificación utilizando el método de gastos por función es el siguiente: 
Ingresos de actividades ordinarias                                                X 
Costo de ventas                                                                           (X) 
Ganancia bruta                                                                                X 
Otros ingresos                                                                                  X
Costos de distribución                                                                (X) 
Gastos de administración                                                           (X) 
Otros gastos                                                                                 (X) 
Ganancia antes de impuestos                                                         X
104 Una entidad que clasifique los gastos por función revelará información adicional sobre la naturaleza de ellos, donde incluirá los gastos por depreciación y amortización y el gasto por beneficios a los empleados. 
105 La elección entre el método de la naturaleza de los gastos o de la función de los gastos dependerá de factores históricos, así como del sector industrial y de la naturaleza de la entidad. Ambos métodos suministran una indicación de los costos que puedan variar directa o indirectamente, con el nivel de ventas o de producción de la entidad. Puesto que cada método de presentación tiene ventajas para tipos distintos de entidades, esta Norma requiere que la gerencia seleccione la presentación que sea fiable y más relevante. Sin embargo, puesto que la información sobre la naturaleza de los gastos es útil para predecir los flujos de efectivo futuros, se requieren información a revelar adicional cuando se utiliza la clasificación de la función de los gastos. En el párrafo 104, “beneficios a los empleados” tiene el mismo significado que en la NIC 19. 
ESTADO DE CAMBIOS EN EL PATRIMONIO 
Información para presentar en el estado de cambios en el patrimonio 
106 Una entidad presentará un estado de cambios en el patrimonio tal como se requiere en el párrafo 10. El estado de cambios en el patrimonio incluye la siguiente información: 
(a) el resultado integral total del periodo, mostrando de forma separada los importes totales atribuibles a los propietarios de la controladora y los atribuibles a las participaciones no controladoras; 
(b) para cada componente de patrimonio, los efectos de la aplicación retroactiva o la reexpresión retroactiva reconocidos según la NIC 8; y
 (c) [eliminado] 
(d) para cada componente del patrimonio, una conciliación entre los importes en libros, al inicio y al final del periodo, revelando por separado (como mínimo) los cambios resultantes de: (i) el resultado del periodo; (ii) otro resultado integral; y (iii) transacciones con los propietarios en su calidad de tales, mostrando por separado las contribuciones realizadas por los propietarios y las distribuciones a éstos y los cambios en las participaciones de propiedad en subsidiarias que no den lugar a una pérdida de control.
INFORMACIÓN PARA PRESENTAR EN EL ESTADO DE CAMBIOS EN EL PATRIMONIO O EN LAS NOTAS 
106ª Una entidad presentará para cada componente del patrimonio, ya sea en el estado de cambios en el patrimonio o en las notas, un desglose por partida de otro resultado integral [véase el párrafo 106(d)(ii)]. 
107 Una entidad presentará, ya sea en el estado de cambios en el patrimonio o en las notas, el importe de los dividendos reconocidos como distribuciones a los propietarios durante el periodo, y el importe de dividendos por acción correspondiente. 
108 En el párrafo 106, los componentes de patrimonio incluyen, por ejemplo, cada una de las clases de capitales aportados, el saldo acumulado de cada una de las clases que componen el otro resultado integral y las ganancias acumuladas. 
109 Los cambios en el patrimonio de una entidad, entre el comienzo y el final del periodo sobre el que se informa, reflejarán el incremento o la disminución en sus activos netos en dicho periodo. Excepto por lo que se refiere a los cambios que procedan de transacciones con los propietarios en su condición de tales (como por ejemplo, aportaciones de patrimonio, las recompras por la entidad de sus propios instrumentos de patrimonio y los dividendos) y los costos directamente relacionados con estas transacciones, la variación integral del patrimonio durante el periodo representa el importe total de ingresos y gastos, incluyendo ganancias o pérdidas, generadas por las actividades de la entidad durante el periodo. 
110 La NIC 8 requiere ajustes retroactivos al efectuar cambios en las políticas contables, en la medida en que sean practicables, excepto cuando las disposiciones transitorias de alguna NIIF requieran otra cosa. La NIC 8 también requiere que la reexpresión para corregir errores se efectúe retroactivamente, en la medida en que sea practicable. Los ajustes y las reexpresiones retroactivas no son cambios en el patrimonio sino ajustes al saldo inicial de las ganancias acumuladas, excepto cuando alguna NIIF requiera el ajuste retroactivo de otro componente de patrimonio. El párrafo 106(b) requiere la revelación de información en el estado de cambios en el patrimonio, sobre los ajustes totales en cada uno de sus componentes derivados de los cambios en las políticas contables y, por separado, de la corrección de errores. Se revelará información sobre estos ajustes para cada periodo anterior y para el principio del periodo. 
ESTADO DE FLUJOS DE EFECTIVO 
111 La información sobre los flujos de efectivo proporciona a los usuarios de los estados financieros una base para evaluar la capacidad de la entidad para generar efectivo y equivalentes al efectivo y las necesidades de la entidad para utilizar esos flujos de efectivo. La NIC 7 establece los requerimientos para la presentación y revelación de información sobre flujos de efectivo. 
NOTAS 
Estructura 
112 Las notas: 
(a) presentarán información acerca de las bases para la preparación de los estados financieros, y sobre las políticas contables específicas utilizadas de acuerdo con los párrafos 117 a 124; 
(b) revelarán la información requerida por las NIIF que no haya sido incluida en otro lugar de los estados financieros; y 
(c) proporcionarán información que no se presente en ninguno de los estados financieros, pero que es relevante para entender cualquiera de ellos. 
113 Una entidad presentará las notas, en la medida en que sea practicable, de una forma sistemática. Para la determinación de una forma sistemática, la entidad considerará el efecto sobre la comprensibilidad y comparabilidad de sus estados financieros. Una entidad hará referencia cruzada de cada partida incluida en los estados de situación financiera y del resultado integral, en el estado de resultados separado (cuando se lo presenta) y en los estados de cambios en el patrimonio y de flujos de efectivo, con cualquier información relacionada en las notas. 
114 Ejemplos de ordenación y agrupación sistemática de las notas incluyen: 
(a) Dar importancia a las áreas de sus actividades que la entidad considera que son más relevantes para la comprensión de su rendimiento financiero y situación financiera, tal como agrupar información sobre actividades operativas concretas; 
(b) agrupar información sobre partidas medidas de forma similar tal como activos medidos a valor razonable; o 
(c) seguir el orden de las partidas del estado (estados) del resultado del periodo y otro resultado integral y del estado de situación financiera, tal como: (i) una declaración de cumplimiento con las NIIF (véase el párrafo 16); (ii) las políticas contables significativas aplicadas (véase el párrafo 117); (iii) información de apoyo para las partidas presentadas en los estados de situación financiera, el estado (estados) del resultado del periodo y otro resultado integral, y en los estados de cambios en el patrimonio y de flujos de efectivo, en el orden en que se presenta cada estado y cada partida; y (iv) otra información a revelar, incluyendo: 
(1) pasivos contingentes (véase la NIC 37); y compromisos contractuales no reconocidos; y revelaciones de información no financiera, por ejemplo, los objetivos y políticas de gestión del riesgo financiero (véase la NIIF 7). 
115 [Eliminado] 
116 Una entidad puede presentar las notas que proporcionan información acerca de las bases para la preparación de los estados financieros y las políticas contables específicas como una sección separada de los estados financieros. 
INFORMACIÓN A REVELAR SOBRE POLÍTICAS CONTABLES 
117 Una entidad revelará sus políticas contables significativas incluyendo: 
(a) la base (o bases) de medición utilizada para elaborar los estados financieros; y (b) las otras políticas contables utilizadas que sean relevantes para la comprensión de los estados financieros. 
118 Para una entidad es importante informar a los usuarios acerca de la base, o bases, de medición utilizada en los estados financieros (por ejemplo: costo histórico, costo corriente, valor neto realizable, valor razonable o importe recuperable), puesto que esa base, sobre la que una entidad elabora los estados financieros, afecta significativamente al análisis realizado por los usuarios. Cuando una entidad utiliza más de una base de medición en los estados financieros, por ejemplo, cuando se han revaluado clases concretas de activos, será suficiente con proporcionar una indicación de las categorías de activos y pasivos a los que se ha aplicado cada una de las bases de medición. 
119 Al decidir si una determinada política contable debe revelarse, la gerencia considerará si la revelación ayudara a los usuarios a comprender la forma en la que las transacciones y otros sucesos y condiciones se reflejan en la información sobre el rendimiento y la situación financiera. Cada entidad considerará la naturaleza de sus operaciones, y las políticas que los usuarios de sus estados financieros esperarían que se revelasen para ese tipo de entidad. La revelación de políticas contables particulares será especialmente útil para los usuarios cuando ellas se seleccionen entre las alternativas permitidas en las NIIF. Un ejemplo es revelar información sobre si una entidad aplica el valor razonable o el modelo del costo a sus propiedades de inversión (véase la NIC 40 Propiedades de Inversión). Algunas NIIF requieren, de forma específica, información a revelar acerca de determinadas políticas contables, incluyendo las opciones escogidas por la gerencia entre las diferentes políticas permitidas. Por ejemplo, la NIC 16 requiere revelar información acerca de las bases de medición utilizadas para las distintas clases de propiedades, planta y equipo. 
120 [Eliminado] 
121 Una política contable podría ser significativa debido a la naturaleza de las operaciones de la entidad, incluso cuando los importes del periodo corriente o del anterior carecieran de importancia relativa. También resultará adecuado revelar información acerca de cada política contable significativa que no esté requerida específicamente por las NIIF, pero que la entidad seleccione y aplique de acuerdo con la NIC 8. 
122 Una entidad revelará, junto con sus políticas contables significativas u otras notas, los juicios, distintos de los que implican estimaciones (véase el párrafo 125), que ha realizado la gerencia en el proceso de aplicación de las políticas contables de la entidad y que tienen el efecto más significativo sobre los importes reconocidos en los estados financieros. 
123 En el proceso de aplicación de las políticas contables de la entidad, la gerencia realizará diversos juicios, diferentes de los relativos a las estimaciones, que pueden afectar significativamente a los importes reconocidos en los estados financieros. Por ejemplo, la gerencia realizará juicios profesionales para determinar: (a) [eliminado] (b) cuándo sustancialmente todos los riesgos y las ventajas significativos inherentes a la propiedad de los activos financieros y, para el arrendador, los activos sujetos a arrendamiento se transfieren a otras entidades; (c) si, por su esencia económica, ciertas ventas de bienes son acuerdos de financiación y, en consecuencia, no ocasionan ingresos de actividades ordinarias; y (d) si las condiciones contractuales de un activo financiero dan lugar, en fechas especificadas, a flujos de efectivo que son únicamente pagos del principal e intereses sobre el importe del principal pendiente. 
124 Alguna de la información a revelar de conformidad con el párrafo 122, es requerida por otras NIIF. Por ejemplo, la NIIF 12 Información a Revelar sobre Participaciones en Otras Entidades requiere que una entidad revele los juicios que ha realizado para determinar si controla a otra entidad. La NIC 40 Propiedades de Inversión requiere, cuando la clasificación de una determinada inversión presente dificultades, que se revele información acerca de los criterios desarrollados por la entidad para distinguir las propiedades de inversión de las propiedades ocupadas por el dueño y de las propiedades mantenidas para su venta en el curso ordinario del negocio. 
CAUSAS DE INCERTIDUMBRE EN LAS ESTIMACIONES 
125 Una entidad revelará información sobre los supuestos realizados acerca del futuro y otras causas de incertidumbre en la estimación al final del periodo sobre el que se informa, que tengan un riesgo significativo de ocasionar ajustes significativos en el valor en libros de los activos o pasivos dentro del periodo contable siguiente. Con respecto a esos activos y pasivos, las notas incluirán detalles de: (a) su naturaleza; y (b) su importe en libros al final del periodo sobre el que se informa. 
126 La determinación del importe en libros de algunos activos y pasivos requerirá la estimación, al final del periodo sobre el que se informa, de los efectos de sucesos futuros inciertos sobre dichos activos y pasivos. Por ejemplo, en ausencia de precios de mercado observados recientemente, será necesario efectuar estimaciones acerca del futuro para medir el importe recuperable de las distintas clases de propiedades, planta y equipo, el efecto de la obsolescencia tecnológica sobre los inventarios, las provisiones condicionadas por los desenlaces futuros de litigios en curso y los pasivos por beneficios a los empleados a largo plazo, tales como las obligaciones por pensiones. Estas estimaciones implican supuestos sobre estas partidas como los flujos de efectivo ajustados por el riesgo o las tasas de descuento empleadas, la evolución prevista en los salarios o los cambios en los precios que afectan a otros costos. 
127 Los supuestos y otras fuentes de incertidumbre en la estimación revelados de acuerdo con el párrafo 125, se refieren a las estimaciones que ofrezcan para la gerencia una mayor dificultad, subjetividad o complejidad en el juicio. A medida que aumenta el número de variables y supuestos que afectan al posible desenlace futuro de las incertidumbres, los juicios profesionales son más subjetivos y complejos, y la posibilidad de que se produzcan cambios significativos en el importe en libros de los activos o pasivos normalmente se incrementa en consecuencia. 
128 La información a revelar indicada en el párrafo 125 no se requiere para activos y pasivos con un riesgo significativo de que sus importes en libros puedan cambiar significativamente dentro del siguiente periodo contable si, al final del periodo sobre el que se informa, han sido medidos a valor razonable basado en un precio cotizado en un mercado activo para un activo o pasivo idéntico. Dichos valores razonables pueden cambiar significativamente dentro del periodo contable próximo pero estos cambios se originarán de los supuestos u otros datos de estimación de la incertidumbre al final del periodo sobre el que se informa. 
129 Una entidad presentará las revelaciones de información del párrafo 125 de forma que ayuden a los usuarios de los estados financieros a entender los juicios efectuados por la gerencia, sobre el futuro y otras fuentes de incertidumbre en la estimación. La naturaleza y el alcance de la información proporcionada variarán de acuerdo con la naturaleza de los supuestos, y con otras circunstancias. Son ejemplos de los tipos revelaciones que una entidad realizará: (a) la naturaleza de los supuestos u otras incertidumbres en la estimación; (b) la sensibilidad del importe en libros a los métodos, supuestos y estimaciones implícitas en su cálculo, incluyendo las razones de tal sensibilidad; (c) la resolución esperada de la incertidumbre, así como el rango de las consecuencias razonablemente posibles dentro del año próximo, respecto del importe en libros de los activos y pasivos afectados; y (d) cuando la incertidumbre continúe sin resolverse, una explicación de los cambios efectuados a los supuestos pasados referentes a dichos activos y pasivos. 
130 Esta Norma no requiere que una entidad revele información presupuestaria o previsiones al revelar la información del párrafo 125. 
131 Algunas veces es impracticable revelar el alcance de los posibles efectos de una hipótesis u otra fuente de incertidumbre en la estimación al final del periodo del que se informa. En tales casos, la entidad revelará que es razonablemente posible, sobre la base del conocimiento existente, que los desenlaces producidos dentro del siguiente periodo contable que sean diferentes de los supuestos utilizados, podrían requerir ajustes significativos en el importe en libros del activo o pasivo afectado. En cualquier caso, la entidad revelará la naturaleza y el importe en libros del activo o pasivo del específico (o de la clase de activos o pasivos) afectado por el supuesto en cuestión. 
132 La información a revelar requerida por el párrafo 122, sobre los juicios particulares efectuados por la gerencia en el proceso de aplicación de las políticas contables de la entidad, no guarda relación con las informaciones a revelar acerca de las fuentes de incertidumbre en la estimación previstas en el párrafo 125. 
133 Otras NIIF requieren la revelación de algunos de los supuestos que de otra forma sería requerida de acuerdo con el párrafo 125. Por ejemplo, la NIC 37 requiere la revelación, en circunstancias específicas, de las principales hipótesis sobre los sucesos futuros que afecten a las diferentes clases de provisiones. La NIIF 13 Medición del Valor Razonable requiere que se revelen las suposiciones significativas (incluyendo las técnicas de valoración y los datos de entrada) que la entidad aplica en la medición del valor razonable de los activos y pasivos, que se contabilicen al valor razonable. 
CAPITAL 
134 Una entidad revelará información que permita que los usuarios de sus estados financieros evalúen los objetivos, las políticas y los procesos que ella aplica para gestionar el capital. 
135 Para cumplir lo establecido en el párrafo 134, la entidad revelará lo siguiente: (a) información cualitativa sobre sus objetivos, políticas y procesos de gestión de capital, que incluya: 
(i)	una descripción de lo que considera capital a efectos de su gestión; 
(ii)	 cuando una entidad está a sujeta a requerimientos externos de capital, la naturaleza de ellos y la forma en que se incorporan en la gestión de capital; y 
(iii)	cómo cumple sus objetivos de gestión de capital. 
(b) datos cuantitativos resumidos acerca de lo que gestiona como capital. Algunas entidades consideran como parte del capital a determinados pasivos financieros (por ejemplo, algunas formas de deuda subordinada). Otras excluyen del capital a algunos componentes del patrimonio (por ejemplo, los componentes surgidos de las coberturas de flujos de efectivo). 
(c) los cambios en (a) y (b) desde el periodo anterior. 
(d) si durante el periodo ha cumplido con cualquier requerimiento externo de capital al cual esté sujeta. 
(e) cuando la entidad no haya cumplido con alguno de estos requerimientos externos de capital impuestos, las consecuencias de este incumplimiento. La entidad basa esta información a revelar internamente proporcionada al personal clave de la gerencia. 
136 Una entidad puede gestionar su capital de diversas formas y estar sujeta a distintos requerimientos sobre el capital. Por ejemplo, un conglomerado puede incluir entidades que lleven a cabo actividades de seguro y actividades bancarias, y esas entidades pueden operar en diferentes jurisdicciones. Si la revelación de forma agregada de los requerimientos de capital y de la forma de gestionar el capital no proporcionase información útil o distorsionase la comprensión de los recursos de capital de una entidad por parte de los usuarios de los estados financieros, la entidad revelará información separada sobre cada requerimiento de capital al que esté sujeta. 
INSTRUMENTOS FINANCIEROS CON OPCIÓN DE VENTA CLASIFICADOS COMO PATRIMONIO 
136ª En el caso de instrumentos financieros con opción de venta clasificados como instrumentos de patrimonio, una entidad revelará (en la medida en que no lo haya hecho en ninguna otra parte): 
(a) un resumen de datos cuantitativos sobre el importe clasificado como patrimonio; (b) sus objetivos, políticas y procesos de gestión de su obligación de recomprar o reembolsar los instrumentos cuando le sea requerido por los tenedores de los instrumentos, incluyendo cualquier cambio sobre el periodo anterior; 
(c) las salidas de efectivo esperadas por reembolso o recompra de esa clase de instrumentos financieros; y 
(d) información sobre cómo se determinaron las salidas de efectivo esperadas por reembolso o recompra. 
OTRA INFORMACIÓN A REVELAR 
137 Una entidad revelará en las notas: 
(a) el importe de los dividendos propuestos o anunciados antes de que los estados financieros hayan sido autorizados para su emisión, que no hayan sido reconocidos como distribución a los propietarios durante el periodo, así como los importes correspondientes por acción; y 
(b) el importe de cualquier dividendo preferente de carácter acumulativo que no haya sido reconocido. 
138 Una entidad revelará lo siguiente, si no ha sido revelado en otra parte de la información publicada con los estados financieros: 
(a) el domicilio y forma legal de la entidad, el país en que se ha constituido y la dirección de su sede social (o el domicilio principal donde desarrolle sus actividades, si fuese diferente de la sede social); 
(b) una descripción de la naturaleza de las operaciones de la entidad, así como de sus principales actividades; 
(c) el nombre de la controladora directa y de la controladora última del grupo; y 
(d) si es una entidad de vida limitada, información sobre la duración de esta.
', category_id:1}])