puts 'Nic 2'

nic = Nic.create(category_id:1, number:2, name:'Inventarios')

puts "Se creó #{nic.name}"

nic.contents.create!(text: 'Objetivo', label: 3, order: 1)
nic.contents.create!(text: 'El objetivo de esta Norma es prescribir el tratamiento contable de los inventarios. Un tema fundamental en la contabilidad de los inventarios es la cantidad de costo que debe reconocerse como un activo, para que sea diferido hasta que los ingresos correspondientes sean reconocidos. Esta Norma suministra una guía práctica para la determinación de ese costo, así como para el subsiguiente reconocimiento como un gasto del periodo, incluyendo también cualquier deterioro que rebaje el importe en libros al valor neto realizable. También suministra directrices sobre las fórmulas del costo que se usan para atribuir costos a los inventarios.', number: '1', order: 2)

nic.contents.create!(text: 'Alcance', label: 3, order: 3)
nic.contents.create!(text: 'Esta Norma es de aplicación a todos los inventarios, excepto a:  
(a) [eliminado]
(b) los instrumentos financieros (véanse las <a href="/nics/32/detail/1" class="content_detail">NIC 32</a> Instrumentos Financieros: Presentación y <a href="/niifs/9/detail/1" class="content_detail">NIIF 9</a> Instrumentos Financieros); y 
(c) los activos biológicos relacionados con la actividad agrícola y productos agrícolas en el punto de cosecha o recolección (véase la <a href="/nics/41/detail/" class="content_detail">NIC 41</a> Agricultura).', number: '2', order: 4)
nic.contents.create!(text: 'Esta Norma no es de aplicación en la medición de los inventarios mantenidos por: (a) Productores de productos agrícolas y forestales, de productos agrícolas tras la cosecha o recolección, de minerales y de productos minerales, siempre que sean medidos por su valor neto realizable, de acuerdo con prácticas bien consolidadas en esos sectores industriales. En el caso de que esos inventarios se midan al valor neto realizable, los cambios en este valor se reconocerán en el resultado del periodo en que se produzcan dichos cambios.
(b) Intermediarios que comercian con materias primas cotizadas, siempre que midan sus inventarios al valor razonable menos costos de venta. En el caso de que esos inventarios se lleven al valor razonable menos costos de venta, los cambios en el importe del valor razonable menos costos de venta se reconocerán en el resultado del periodo en que se produzcan dichos cambios.', number: '3', order: 5)
nic.contents.create!(text: 'Los inventarios a que se ha hecho referencia en el <a href="/nics/2/detail/3a" class="content_detail">párrafo 3(a)</a> se miden por su valor neto realizable en ciertas fases de la producción. Ello ocurre, por ejemplo, cuando se han recogido las cosechas agrícolas o se han extraído los minerales, siempre que su venta esté asegurada por un contrato a plazo sea cual fuere su tipo o garantizada por el gobierno, o bien cuando existe un mercado activo y el riesgo de fracasar en la venta sea mínimo. Esos inventarios se excluyen únicamente de los requerimientos de medición establecidos en esta Norma.', number: '4', order: 6)
nic.contents.create!(text: 'Los intermediarios que comercian son aquellos que compran o venden materias primas cotizadas por cuenta propia, o bien por cuenta de terceros. Los inventarios a que se ha hecho referencia en el apartado (b) del <a href="/nics/2/detail/3" class="content_detail">párrafo 3</a> se adquieren, principalmente, con el propósito de venderlos en un futuro próximo, y generar ganancias procedentes de las fluctuaciones en el precio, o un margen de comercialización. Cuando esos inventarios se contabilicen por su valor razonable menos los costos de venta quedarán excluidos únicamente de los requerimientos de medición establecidos en esta Norma.', number: '5', order: 7)

nic.contents.create!(text: 'Definiciones', label: 3, order: 8)
nic.contents.create!(text: 'Los siguientes términos se usan en esta Norma con los significados que a continuación se especifican:
Inventarios son activos:
(a) poseídos para ser vendidos en el curso normal de la operación;
(b) en proceso de producción con vistas a esa venta; o
(c) en forma de materiales o suministros que serán consumidos en el proceso de producción o en la prestación de servicios.
Valor neto realizable es el precio estimado de venta de un activo en el curso normal de la operación menos los costos estimados para terminar su producción y los necesarios para llevar a cabo la venta.
Valor razonable es el precio que se recibiría por vender un activo o que se pagaría por transferir un pasivo en una transacción ordenada entre participantes del mercado en la fecha de la medición. (Véase la <a href="/niifs/13/detail/" class="content_detail">NIIF 13</a> Medición del Valor Razonable).', number: '6', order: 9)
nic.contents.create!(text: 'El valor neto realizable hace referencia al importe neto que la entidad espera obtener por la venta de los inventarios en el curso normal de la operación. El valor razonable refleja el precio al que tendría lugar una transacción ordenada para vender el mismo inventario en el mercado principal (o más ventajoso) para ese inventario, entre participantes de mercado en la fecha de la medición. El primero es un valor específico para la entidad, mientras que el último no. El valor neto realizable de los inventarios puede no ser igual al valor razonable menos los costos de venta.', number: '7', order: 10)
nic.contents.create!(text: 'Entre los inventarios también se incluyen los bienes comprados y almacenados para su reventa, entre los que se encuentran, por ejemplo, las mercaderías adquiridas por un minorista para su reventa a sus clientes, y también los terrenos u otras propiedades de inversión que se tienen para ser vendidos a terceros. También son inventarios los productos terminados o en curso de fabricación mantenidos por la entidad, así como los materiales y suministros para ser usados en el proceso productivo. Los costos incurridos para cumplir un contrato con un cliente que no dan lugar a inventarios (o activos dentro del alcance de otra Norma) se contabilizarán de acuerdo con la <a href="/niifs/15/detail/1" class="content_detail">NIIF 15</a> Ingresos de Actividades Ordinarias Procedentes de Contratos con Clientes.', number: '8', order: 11)

nic.contents.create!(text: 'Medición de los Inventarios', label: 3, order: 12)
nic.contents.create!(text: 'Los inventarios se medirán al costo o al valor neto realizable, según cual sea menor.', number: '9', order: 13)

nic.contents.create!(text: 'Costo de los Inventarios', label: 3, order: 14)
nic.contents.create!(text: 'El costo de los inventarios comprenderá todos los costos derivados de su adquisición, transformación, así como otros costos en los que se haya incurrido para darles su condición y ubicación actuales.', number: '10', order: 15)

nic.contents.create!(text: 'Costo de Adquisición', label: 3, order: 16)
nic.contents.create!(text: 'El costo de adquisición de los inventarios comprenderá el precio de compra, los aranceles de importación y otros impuestos (que no sean recuperables posteriormente de las autoridades fiscales) y transporte, manejo y otros costos directamente atribuibles a la adquisición de mercaderías, materiales y servicios. Los descuentos comerciales, las rebajas y otras partidas similares se deducirán para determinar el costo de adquisición.', number: '11', order: 17)

nic.contents.create!(text: 'Costos de Transformación', label: 3, order: 18)
nic.contents.create!(text: 'Los costos de transformación de los inventarios comprenderán aquellos costos directamente relacionados con las unidades de producción, tales como la mano de obra directa. También comprenderán una distribución sistemática de los costos indirectos de producción, variables o fijos, en los que se haya incurrido para transformar las materias primas en productos terminados. Son costos indirectos fijos de producción los que permanecen relativamente constantes, con independencia del volumen de producción, tales como la depreciación y mantenimiento de los edificios y equipos de la fábrica y los activos por derecho de uso utilizados en el proceso de producción, así como el costo de gestión y administración de la planta. Son costos indirectos variables de producción los que varían directamente, o casi directamente, con el volumen de producción obtenida, tales como los materiales y la mano de obra indirecta.', number: '12', order: 19)
nic.contents.create!(text: 'El proceso de distribución de los costos indirectos fijos a los costos de transformación se basará en la capacidad normal de trabajo de los medios de producción. Capacidad normal es la producción que se espera conseguir en circunstancias normales, considerando el promedio de varios periodos o temporadas, y teniendo en cuenta la pérdida de capacidad que resulta de las operaciones previstas de mantenimiento. Puede usarse el nivel real de producción siempre que se aproxime a la capacidad normal. El importe de costo indirecto fijo distribuido a cada unidad de producción no se incrementará como consecuencia de un nivel bajo de producción, ni por la existencia de capacidad ociosa. Los costos indirectos no distribuidos se reconocerán como gastos del periodo en que han sido incurridos. En periodos de producción anormalmente alta, el importe de costo indirecto distribuido a cada unidad de producción se disminuirá, de manera que no se valoren los inventarios por encima del costo. Los costos indirectos variables se distribuirán a cada unidad de producción sobre la base del nivel real de uso de los medios de producción.', number: '13', order: 20)
nic.contents.create!(text: 'El proceso de producción puede dar lugar a la fabricación simultánea de más de un producto. Este es el caso, por ejemplo, de la producción conjunta o de la producción de productos principales junto a subproductos. Cuando los costos de transformación de cada tipo de producto no sean identificables por separado, se distribuirá el costo total entre los productos utilizando bases uniformes y racionales. La distribución puede basarse, por ejemplo, en el valor de ventas relativo de cada producto ya sea como producción en proceso, en el momento en que los productos pasan a poder identificarse por separado, o cuando se termine el proceso de producción. La mayoría de los subproductos, por su propia naturaleza, no poseen un valor significativo. Cuando este es el caso, se miden frecuentemente al valor neto realizable, deduciendo esa cantidad del costo del producto principal. Como resultado de esta distribución, el importe en libros del producto principal no resultará significativamente diferente de su costo.', number: '14', order: 21)

nic.contents.create!(text: 'Otros Costos', label: 3, order: 22)
nic.contents.create!(text: 'Se incluirán otros costos, en el costo de los inventarios, siempre que se hubiera incurrido en ellos para dar a los mismos su condición y ubicación actuales. Por ejemplo, podrá ser apropiado incluir, como costo de los inventarios, algunos costos indirectos no derivados de la producción, o los costos del diseño de productos para clientes específicos.', number: '15', order: 23)
nic.contents.create!(text: 'Son ejemplos de costos excluidos del costo de los inventarios, reconocidos como gastos del periodo en el que se incurren, los siguientes:
(a) los importes anormales de desperdicio de materiales, mano de obra u otros costos de producción;
(b) los costos de almacenamiento, a menos que sean necesarios en el proceso productivo, previos a un proceso de elaboración ulterior;
(c) los costos indirectos de administración que no hayan contribuido a dar a los inventarios su condición y ubicación actuales; y
(d) los costos de venta.', number: '16', order: 24)
nic.contents.create!(text: 'En la <a href="/nics/23/detail/1" class="content_detail">NIC 23</a> Costos por Préstamos, se identifican las limitadas circunstancias en las que los costos financieros se incluyen en el costo de los inventarios.', number: '17', order: 25)
nic.contents.create!(text: 'Una entidad puede adquirir inventarios con pago aplazado. Cuando el acuerdo contenga de hecho un elemento de financiación, como puede ser, por ejemplo, la diferencia entre el precio de adquisición en condiciones normales de crédito y el importe pagado, este elemento se reconocerá como gasto por intereses a lo largo del periodo de financiación.', number: '18', order: 26)

nic.contents.create!(text: 'Costo de los Inventarios para un prestador de Servicios', label: 3, order: 27)
nic.contents.create!(text: '[Eliminado]', number: '19', order: 28)

nic.contents.create!(text: 'Costo de los Productos Agrícolas recolectados de Activos Biológicos', label: 3, order: 29)
nic.contents.create!(text: 'De acuerdo con la <a href="/nics/41/detail/1" class="content_detail">NIC 41</a> Agricultura, los inventarios que comprenden productos agrícolas, que la entidad haya cosechado o recolectado de sus activos biológicos, se medirán, para su reconocimiento inicial, por el valor razonable menos los costos de venta en el momento de su cosecha o recolección. Este será el costo de los inventarios en esa fecha, para la aplicación de la presente Norma.', number: '20', order: 30)

nic.contents.create!(text: 'Técnicas de Medición de Costos', label: 3, order: 31)
nic.contents.create!(text: 'Las técnicas para la medición del costo de los inventarios, tales como el método del costo estándar o el método de los minoristas, podrán ser utilizadas por conveniencia siempre que el resultado de aplicarlas se aproxime al costo. Los costos estándares tendrán en cuenta los niveles normales de materias primas, suministros, mano de obra, eficiencia y utilización de la capacidad. Éstos se revisarán de forma regular y, si es necesario, se cambiarán en función de las condiciones actuales.', number: '21', order: 32)
nic.contents.create!(text: 'El método de los minoristas se utiliza a menudo, en el sector comercial al por menor para la medición de inventarios cuando hay un gran número de artículos que rotan velozmente, que tienen márgenes similares y para los cuales resulta impracticable usar otros métodos de cálculo de costos. Cuando se emplea este método, el costo de los inventarios se determinará deduciendo, del precio de venta del artículo en cuestión, un porcentaje apropiado de margen bruto. El porcentaje aplicado tendrá en cuenta la parte de los inventarios que se han marcado por debajo de su precio de venta original. A menudo se utiliza un porcentaje promedio para cada sección o departamento comercial.', number: '22', order: 33)

nic.contents.create!(text: 'Fórmulas de Cálculo del Costo', label: 3, order: 34)
nic.contents.create!(text: 'El costo de los inventarios de productos que no son habitualmente intercambiables entre sí, así como de los bienes y servicios producidos y segregados para proyectos específicos, se determinará a través de la identificación específica de sus costos individuales.', number: '23', order: 35)
nic.contents.create!(text: 'La identificación específica del costo significa que cada tipo de costo concreto se distribuye entre ciertas partidas identificadas dentro de los inventarios. Este es el tratamiento adecuado para los productos que se segregan para un proyecto específico, con independencia de que hayan sido comprados o producidos. Sin embargo, la identificación específica de costos resultará inadecuada cuando, en los inventarios, haya un gran número de productos que sean habitualmente intercambiables. En estas circunstancias, el método para seleccionar qué productos individuales van a permanecer en la existencia final, podría ser usado para obtener efectos predeterminados en el resultado del periodo.', number: '24', order: 36)
nic.contents.create!(text: 'El costo de los inventarios, distintos de los tratados en el <a href="/nics/2/detail/23" class="content_detail">párrafo 23</a>, se asignará utilizando los métodos de primera entrada primera salida (the first-in, first-out, FIFO, por sus siglas en inglés) o costo promedio ponderado. Una entidad utilizará la misma fórmula de costo para todos los inventarios que tengan una naturaleza y uso similares. Para los inventarios con una naturaleza o uso diferente, puede estar justificada la utilización de fórmulas de costo distintas.', number: '25', order: 37)
nic.contents.create!(text: 'Por ejemplo, dentro de la misma entidad, los inventarios utilizados en un segmento de operación pueden tener un uso diferente del que se da al mismo tipo de inventarios, en otro segmento de operación. Sin perjuicio de lo anterior, la diferencia en la ubicación geográfica de los inventarios (o en las reglas fiscales correspondientes) no es, por sí misma, motivo suficiente para justificar el uso de fórmulas de costo diferentes.', number: '26', order: 38)
nic.contents.create!(text: 'La fórmula FIFO asume que los productos en inventarios comprados o producidos antes serán vendidos en primer lugar y, consecuentemente, que los productos que queden en la existencia final serán los producidos o comprados más recientemente. Si se utiliza el método o fórmula del costo promedio ponderado, el costo de cada unidad de producto se determinará a partir del promedio ponderado del costo de los artículos similares, poseídos al principio del periodo, y del costo de los mismos artículos comprados o producidos durante el periodo. El promedio puede calcularse periódicamente o después de recibir cada envío adicional, dependiendo de las circunstancias de la entidad.', number: '27', order: 39)

nic.contents.create!(text: 'Valor Neto Realizable', label: 3, order: 40)
nic.contents.create!(text: 'El costo de los inventarios puede no ser recuperable en caso de que los mismos estén dañados, si han devenido parcial o totalmente obsoletos, o bien si sus precios de mercado han caído. Asimismo, el costo de los inventarios puede no ser recuperable si los costos estimados para su terminación o su venta han aumentado. La práctica de rebajar el saldo, hasta que el costo sea igual al valor neto realizable, es coherente con el punto de vista según el cual los activos no deben registrarse en libros por encima de los importes que se espera obtener a través de su venta o uso.', number: '28', order: 41)
nic.contents.create!(text: 'Generalmente, la rebaja hasta alcanzar el valor neto realizable se calcula para cada partida de los inventarios. En algunas circunstancias, sin embargo, puede resultar apropiado agrupar partidas similares o relacionadas. Este puede ser el caso de las partidas de inventarios relacionados con la misma línea de productos, que tienen propósitos o usos finales similares, se producen y venden en la misma área geográfica y no pueden ser, por razones prácticas, evaluados separadamente de otras partidas de la misma línea. No es apropiado realizar las rebajas a partir de partidas que reflejen clasificaciones completas de los inventarios, por ejemplo, sobre la totalidad de los productos terminados, o sobre todos los inventarios en un segmento de operación determinado.', number: '29', order: 42)
nic.contents.create!(text: 'Las estimaciones del valor neto realizable se basarán en la información más fiable de que se disponga, en el momento de hacerlas, acerca del importe por el que se espera realizar los inventarios. Estas estimaciones tendrán en consideración las fluctuaciones de precios o costos relacionados directamente con los hechos posteriores al cierre, en la medida que esos hechos confirmen condiciones existentes al final del periodo.', number: '30', order: 43)
nic.contents.create!(text: 'Al hacer las estimaciones del valor neto realizable se tendrá en consideración el propósito para el que se mantienen los inventarios. Por ejemplo, el valor neto realizable del importe de inventarios que se tienen para cumplir con los contratos de venta, o de prestación de servicios, se basa en el precio que figura en el contrato. Si los contratos de ventas son por una cantidad inferior a la reflejada en inventarios, el valor neto realizable del exceso se determina sobre la base de los precios generales de venta. Pueden aparecer provisiones o pasivos contingentes por contratos de venta firmes que excedan las cantidades de productos en existencia, o bien de productos que vayan a obtenerse por contratos de compra firmes. Estas provisiones o pasivos contingentes se tratarán contablemente de acuerdo con la <a href="/nics/37/detail/1" class="content_detail">NIC 37</a> Provisiones, Pasivos Contingentes y Activos Contingentes.', number: '31', order: 44)
nic.contents.create!(text: 'No se rebajarán las materias primas y otros suministros, mantenidos para su uso en la producción de inventarios, para situar su importe en libros por debajo del costo, siempre que se espere que los productos terminados a los que se incorporen sean vendidos al costo o por encima del mismo. Sin embargo, cuando una reducción en el precio de las materias primas indique que el costo de los productos terminados excederá a su valor neto realizable, se rebajará su importe en libros hasta cubrir esa diferencia. En estas circunstancias, el costo de reposición de las materias primas puede ser la mejor medida disponible de su valor neto realizable.', number: '32', order: 45)
nic.contents.create!(text: 'Se realizará una nueva evaluación del valor neto realizable en cada periodo posterior. Cuando las circunstancias que previamente causaron la rebaja del inventario hayan dejado de existir, o cuando exista una clara evidencia de un incremento en el valor neto realizable como consecuencia de un cambio en las circunstancias económicas, se revertirá el importe de la misma, de manera que el nuevo valor contable sea el menor entre el costo y el valor neto realizable revisado. Esto ocurrirá, por ejemplo, cuando un artículo en existencia que se lleva al valor neto realizable porque ha bajado su precio de venta está todavía en inventario de un periodo posterior y su precio de venta se ha incrementado.', number: '33', order: 46)

nic.contents.create!(text: 'Reconocimiento como un Gasto', label: 3, order: 47)
nic.contents.create!(text: 'Cuando los inventarios sean vendidos, el importe en libros de los mismos se reconocerá como gasto del periodo en el que se reconozcan los correspondientes ingresos de operación. El importe de cualquier rebaja de valor, hasta alcanzar el valor neto realizable, así como todas las demás pérdidas en los inventarios, será reconocido en el periodo en que ocurra la rebaja o la pérdida. El importe de cualquier reversión de la rebaja de valor que resulte de un incremento en el valor neto realizable se reconocerá como una reducción en el valor de los inventarios que hayan sido reconocidos como gasto en el periodo en que la recuperación del valor tenga lugar.', number: '34', order: 48)
nic.contents.create!(text: 'Algunos inventarios pueden ser incorporados a otras cuentas de activo, por ejemplo, los inventarios que se emplean como un componente de las propiedades, planta y equipo de propia construcción. Los inventarios asignados a otros activos de esta manera, se reconocerá como gasto a lo largo de la vida útil de los mismos.', number: '35', order: 49)

nic.contents.create!(text: 'Información a Revelar', label: 3, order: 50)
nic.contents.create!(text: 'En los estados financieros se revelará la siguiente información:
(a) las políticas contables adoptadas para la medición de los inventarios, incluyendo la fórmula del costo que se haya utilizado;
(b) el importe total en libros de los inventarios, y los importes parciales según la clasificación apropiada para la entidad;
(c) el importe en libros de los inventarios que se llevan al valor razonable menos los costos de venta;
(d) el importe de los inventarios reconocido como gasto durante el periodo;
(e) el importe de las rebajas de valor de los inventarios que se ha reconocido como gasto en el periodo, de acuerdo con el <a href="/nics/2/detail/34" class="content_detail">párrafo 34</a>;
(f) el importe de las reversiones en las rebajas de valor anteriores, que se ha reconocido como una reducción en la cuantía del gasto por inventarios en el periodo, de acuerdo con el <a href="/nics/2/detail/34" class="content_detail">párrafo 34</a>;
(g) las circunstancias o eventos que hayan producido la reversión de las rebajas de valor, de acuerdo con el referido <a href="/nics/2/detail/34" class="content_detail">párrafo 34</a>; y
(h) el importe en libros de los inventarios pignorados en garantía del cumplimiento de deudas.', number: '36', order: 51)
nic.contents.create!(text: 'La información acerca del importe en libros de las diferentes clases de inventarios, así como la variación de dichos importes en el periodo, resultará de utilidad a los usuarios de los estados financieros. Una clasificación común de los inventarios es la que distingue entre mercaderías, suministros para la producción, materias primas, productos en curso y productos terminados.', number: '37', order: 52)
nic.contents.create!(text: 'El importe de los inventarios reconocido como gasto durante el periodo, denominado generalmente costo de las ventas, comprende los costos previamente incluidos en la medición de los productos que se han vendido, así como los costos indirectos no distribuidos y los costos de producción de los inventarios por importes anómalos. Las circunstancias particulares de cada entidad podrían exigir la inclusión de otros costos, tales como los costos de distribución.', number: '38', order: 53)
nic.contents.create!(text: 'Algunas entidades adoptan un formato para la presentación del resultado del periodo donde presentan importes diferentes a la cifra de costo de los inventarios que ha sido reconocida como gasto durante el periodo. Según este formato, una entidad presentará un análisis de los gastos mediante una clasificación basada en la naturaleza de estos gastos. En este caso, la entidad revelará los costos reconocidos como gastos de materias primas y consumibles, costos de mano de obra y otros costos, junto con el importe del cambio neto en los inventarios para el periodo.', number: '39', order: 54)

