puts 'Nic 7'

nic = Nic.create(category_id:4, number:7, name:'Estado de Flujo de Efectivos')

puts "Se creó #{nic.name}"

nic.contents.create!(text: 'Objetivo', label: 3, order: 1)
nic.contents.create!(text: 'La información acerca de los flujos de efectivo de una entidad es útil porque suministra a los usuarios de los estados financieros una base para evaluar la capacidad de la entidad para generar efectivo y equivalentes al efectivo y las necesidades de la entidad para utilizar esos flujos de efectivo. Para tomar decisiones económicas, los usuarios deben evaluar la capacidad que la entidad tiene de generar efectivo y equivalentes al efectivo, así como las fechas en que se producen y el grado de certidumbre relativa de su aparición. El objetivo de esta Norma es requerir el suministro de información sobre los cambios históricos en el efectivo y equivalentes al efectivo de una entidad mediante un estado de flujos de efectivo en el que los flujos de fondos del período se clasifiquen según si proceden de actividades de operación, de inversión o de financiación.', number: 'a', order: 2)

nic.contents.create!(text: 'Alcance', label: 3, order: 3)
nic.contents.create!(text: 'Esta Norma sustituye a la antigua NIC 7 Estado de Cambios en la Posición Financiera, aprobada en julio de 1977.', number: 'p2', order: 4)
nic.contents.create!(text: 'Los usuarios de los estados financieros están interesados en saber cómo la entidad genera y utiliza el efectivo y los equivalentes al efectivo. Esta necesidad es independiente de la naturaleza de las actividades de la entidad, incluso cuando el efectivo pueda ser considerado como el producto de la entidad en cuestión, como puede ser el caso de las entidades financieras. Básicamente, las entidades necesitan efectivo por las mismas razones, por muy diferentes que sean las actividades que constituyen su principal fuente de ingresos. En efecto, todas ellas necesitan efectivo para llevar a cabo sus operaciones, pagar sus obligaciones y suministrar rendimientos a sus inversores. Por consiguiente, esta Norma requiere que todas las entidades presenten un estado de flujos de efectivo.', number: 'p3', order: 5)

nic.contents.create!(text: 'Beneficios de la Información sobre flujos de Efectivo', label: 3, order: 6)
nic.contents.create!(text: 'Un estado de flujos de efectivo, cuando se usa juntamente con el resto de los estados financieros, suministra información que permite a los usuarios evaluar los cambios en los activos netos de una entidad, su estructura financiera (incluyendo su liquidez y solvencia) y su capacidad para afectar a los importes y las fechas de los flujos de efectivo, a fin de adaptarse a la evolución de las circunstancias y a las oportunidades. La información acerca del flujo de efectivo es útil para evaluar la capacidad que la entidad tiene para generar efectivo y equivalentes al efectivo, y permite a los usuarios desarrollar modelos para evaluar y comparar el valor presente de los flujos netos de efectivo de diferentes entidades. También mejora la comparabilidad de la información sobre el rendimiento de las operaciones de diferentes entidades, puesto que elimina los efectos de utilizar distintos tratamientos contables para las mismas transacciones y sucesos económicos.', number: '4', order: 7)
nic.contents.create!(text: 'Con frecuencia, la información histórica sobre flujos de efectivo se usa como indicador del importe, momento de la aparición y certidumbre de flujos de efectivo futuros. Es también útil para comprobar la exactitud de evaluaciones pasadas respecto de los flujos futuros, así como para examinar la relación entre rendimiento, flujos de efectivo netos y el impacto de los cambios en los precios.', number: '5', order: 8)

nic.contents.create!(text: 'Definiciones', label: 3, order: 9)
nic.contents.create!(text: 'Los siguientes términos se usan en esta Norma con los significados que a continuación se especifican:
El efectivo comprende tanto el efectivo como los depósitos bancarios a la vista.
Los equivalentes al efectivo son inversiones a corto plazo de gran liquidez, que son fácilmente convertibles en importes determinados de efectivo, estando sujetos a un riesgo poco significativo de cambios en su valor.
Flujos de efectivo son las entradas y salidas de efectivo y equivalentes al efectivo.
Actividades de operación son las actividades que constituyen la principal fuente de ingresos de la entidad, así como otras actividades que no puedan ser calificadas como de inversión o financiación.
Actividades de inversión son las de adquisición y disposición de activos a largo plazo, así como de otras inversiones no incluidas en los equivalentes al efectivo.
Actividades de financiación son las actividades que producen cambios en el tamaño y composición de los capitales propios y de los préstamos tomados por la entidad.', number: '6', order: 10)

nic.contents.create!(text: 'Efectivo y equivalentes al Efectivo', label: 3, order: 11)
nic.contents.create!(text: 'Los equivalentes al efectivo se tienen, más que para propósitos de inversión o similares, para cumplir los compromisos de pago a corto plazo. Para que una inversión financiera pueda ser calificada como equivalente al efectivo debe poder ser fácilmente convertible en una cantidad determinada de efectivo y estar sujeta a un riesgo insignificante de cambios en su valor. Por ello, una inversión normalmente cumple los requisitos de un equivalente al efectivo cuando tiene un periodo de vencimiento corto, digamos, de tres meses o menos desde la fecha de la adquisición. Las inversiones en patrimonio se excluyen de los equivalentes al efectivo a menos que sean, en sustancia, equivalentes al efectivo, por ejemplo, en el caso de acciones preferentes adquiridas dentro un corto periodo de tiempo hasta su vencimiento y con una fecha de rescate especificada.', number: '7', order: 12)
nic.contents.create!(text: 'Los préstamos bancarios se consideran, en general, como actividades de financiación. En algunos países, sin embargo, los sobregiros exigibles en cualquier momento por el banco forman parte integrante de la gestión del efectivo de la entidad. En tales circunstancias, tales sobregiros se incluyen como componentes del efectivo y equivalentes al efectivo. Una característica de los acuerdos bancarios que regulan los sobregiros u operaciones similares es que el saldo con el banco fluctúa constantemente de deudor a acreedor.', number: '8', order: 13)
nic.contents.create!(text: 'Los flujos de efectivo no incluirán ningún movimiento entre las partidas que constituyen el efectivo y equivalentes al efectivo, puesto que estos componentes son parte de la gestión de efectivo de la entidad más que de sus actividades de operación, de inversión o financiación. La gestión del efectivo comprende también la inversión de los sobrantes de efectivo y equivalentes al efectivo.', number: '9', order: 14)

nic.contents.create!(text: 'Presentación de un Estado de Flujos de Efectivo', label: 3, order: 15)
nic.contents.create!(text: 'El estado de flujos de efectivo informará acerca de los flujos de efectivo habidos durante el periodo, clasificándolos por actividades de operación, de inversión y de financiación.', number: '10', order: 16)
nic.contents.create!(text: 'Cada entidad presenta sus flujos de efectivo procedentes de las actividades de operación, de inversión y de financiación, de la manera que resulte más apropiada según la naturaleza de sus actividades. La clasificación de los flujos según las actividades citadas suministra información que permite a los usuarios evaluar el impacto de las mismas en la posición financiera de la entidad, así como sobre el importe final de su efectivo y demás equivalentes al efectivo. Esta información puede ser útil también al evaluar las relaciones entre tales actividades.', number: '11', order: 17)
nic.contents.create!(text: 'Una transacción puede contener flujos de efectivo pertenecientes a las diferentes categorías. Por ejemplo, cuando los reembolsos correspondientes a un préstamo incluyen capital e interés, la parte de intereses puede clasificarse como actividades de operación, mientras que la parte de devolución del principal se clasifica como actividad de financiación.', number: '12', order: 18)

nic.contents.create!(text: 'Actividades de Operación', label: 3, order: 19)
nic.contents.create!(text: '13 El importe de los flujos de efectivo procedentes de actividades de operación es un indicador clave de la medida en la cual estas actividades han generado fondos líquidos suficientes para reembolsar los préstamos, mantener la capacidad de operación de la entidad, pagar dividendos y realizar nuevas inversiones sin recurrir a fuentes externas de financiación. La información acerca de los componentes específicos de los flujos de efectivo de las actividades de operación es útil, junto con otra información, para pronosticar los flujos de efectivo futuros de tales actividades.', number: '13', order: 20)
nic.contents.create!(text: 'Los flujos de efectivo procedentes de las actividades de operación se derivan fundamentalmente de las transacciones que constituyen la principal fuente de ingresos de actividades ordinarias de la entidad. Por tanto, proceden de las operaciones y otros sucesos que entran en la determinación de las ganancias o pérdidas netas. Ejemplos de flujos de efectivo por actividades de operación son los siguientes:
(a) cobros procedentes de las ventas de bienes y la prestación de servicios;
(b) cobros procedentes de regalías, cuotas, comisiones y otros ingresos de actividades ordinarias;
(c) pagos a proveedores por el suministro de bienes y servicios;
(d) pagos a y por cuenta de los empleados;
(e) [eliminado]
(f) pagos o devoluciones de impuestos sobre las ganancias, a menos que éstos puedan clasificarse específicamente dentro de las actividades de inversión o financiación; y
(g) cobros y pagos derivados de contratos que se tienen para intermediación o para negociar con ellos.
Algunas transacciones, tales como la venta de un elemento de propiedades, planta y equipo, pueden dar lugar a una pérdida o ganancia que se incluirá en el resultado reconocido. Los flujos de efectivo relacionados con estas transacciones son flujos de efectivo procedentes de actividades de inversión. Sin embargo, los pagos para elaborar o adquirir activos mantenidos para arrendar a terceros, que posteriormente se clasifiquen como mantenidos para la venta en los términos descritos en el párrafo 68A de la NIC 16 Propiedades, Planta y Equipo son flujos de efectivo procedentes de actividades de operación Los cobros por el arrendamiento y posterior venta de esos activos también se considerarán como flujos de efectivo procedentes de actividades de operación.', number: '14', order: 21)
nic.contents.create!(text: 'Una entidad puede tener títulos o conceder préstamos por razones de intermediación u otro tipo de acuerdos comerciales habituales, en cuyo caso estas inversiones se considerarán similares a los inventarios adquiridos específicamente para revender. Por tanto, los flujos de efectivo de tales operaciones se clasifican como procedentes de actividades de operación. De forma similar, los anticipos de efectivo y préstamos realizados por instituciones financieras se clasificarán habitualmente entre las actividades de operación, puesto que están relacionados con las actividades que constituyen la principal fuente de ingresos de actividades ordinarias de la entidad.', number: '15', order: 22)

nic.contents.create!(text: 'Actividades de Inversión', label: 3, order: 23)
nic.contents.create!(text: '16 La información a revelar por separado de los flujos de efectivo procedentes de las actividades de inversión es importante, porque tales flujos de efectivo representan la medida en la cual se han hecho desembolsos para recursos que se prevé van a producir ingresos y flujos de efectivo en el futuro. Solo los desembolsos que den lugar al reconocimiento de un activo en el estado de situación financiera cumplen las condiciones para su clasificación como actividades de inversión. Ejemplos de flujos de efectivo por actividades de inversión son los siguientes:
(a) pagos por la adquisición de propiedades, planta y equipo, activos intangibles y otros activos a largo plazo. Estos pagos incluyen aquellos relacionados con los costos de desarrollo capitalizados y las propiedades, planta y equipo construidos por la entidad para sí misma;
(b) cobros por ventas de propiedades, planta y equipo, activos intangibles y otros activos a largo plazo;
(c) pagos por la adquisición de instrumentos de pasivo o de patrimonio, emitidos por otras entidades, así como participaciones en negocios conjuntos (distintos de los pagos por esos mismos títulos e instrumentos que sean considerados efectivo y equivalentes al efectivo, y de los que se tengan para intermediación u otros acuerdos comerciales habituales);
(d) cobros por venta y reembolso de instrumentos de pasivo o de capital emitidos por otras entidades, así como participaciones en negocios conjuntos (distintos de los cobros por esos mismos títulos e instrumentos que sean considerados efectivo y otros equivalentes al efectivo, y de los que se posean para intermediación u otros acuerdos comerciales habituales);
(e) anticipos de efectivo y préstamos a terceros (distintos de las operaciones de ese tipo hechas por entidades financieras);
(f) cobros derivados del reembolso de anticipos y préstamos a terceros (distintos de las operaciones de este tipo hechas por entidades financieras);
(g) pagos derivados de contratos a término, de futuro, de opciones y de permuta financiera, excepto cuando dichos contratos se mantengan por motivos de intermediación u otros acuerdos comerciales habituales, o bien cuando los anteriores pagos se clasifiquen como actividades de financiación; y
(h) cobros procedentes de contratos a término, a futuro, de opciones y de permuta financiera, excepto cuando dichos contratos se mantengan por motivos de intermediación u otros acuerdos comerciales habituales, o bien cuando los anteriores cobros se clasifiquen como actividades de financiación.
Cuando un contrato se trata contablemente como cobertura de una posición comercial o financiera determinada, los flujos de efectivo del mismo se clasifican de la misma forma que los procedentes de la posición que se está cubriendo.', number: '16', order: 24)

nic.contents.create!(text: 'Actividades de Financiación', label: 3, order: 25)
nic.contents.create!(text: 'Es importante la presentación separada de los flujos de efectivo procedentes de actividades de financiación, puesto que resulta útil al realizar la predicción de necesidades de efectivo para cubrir compromisos con los suministradores de capital a la entidad. Ejemplos de flujos de efectivo por actividades de financiación son los siguientes:
(a) cobros procedentes de la emisión de acciones u otros instrumentos de capital;
(b) pagos a los propietarios por adquirir o rescatar las acciones de la entidad;
(c) cobros procedentes de la emisión de obligaciones sin garantía, préstamos, bonos, cédulas hipotecarias y otros fondos tomados en préstamo, ya sea a largo o a corto plazo;
(d) reembolsos en efectivo de fondos tomados en préstamo; y
(e) pagos realizados por el arrendatario para reducir una deuda pendiente procedente de un arrendamiento.', number: '17', order: 26)

nic.contents.create!(text: 'Información sobre Flujos de Efectivo de las Actividades de Operación', label: 3, order: 27)
nic.contents.create!(text: 'La entidad debe informar acerca de los flujos de efectivo de las operaciones usando uno de los dos siguientes métodos:
(a) método directo, según el cual se presentan por separado las principales categorías de cobros y pagos en términos brutos; o
(b) método indirecto, según el cual se comienza presentando la ganancia o pérdida en términos netos, cifra que se corrige luego por los efectos de las transacciones no monetarias, por todo tipo de partidas de pago diferido y acumulaciones (o devengos) que son la causa de cobros y pagos en el pasado o en el futuro, así como de las partidas de pérdidas o ganancias asociadas con flujos de efectivo de operaciones clasificadas como de inversión o financiación.', number: '18', order: 28)
nic.contents.create!(text: 'Se aconseja a las entidades que presenten los flujos de efectivo de las actividades de operación utilizando el método directo. Este método suministra información que puede ser útil en la estimación de los flujos de efectivo futuros, la cual no está disponible utilizando el método indirecto. En este método directo, la información acerca de las principales categorías de cobros o pagos en términos brutos puede ser obtenida por uno de los siguientes procedimientos:
(a) utilizando los registros contables de la entidad, o
(b) ajustando las ventas y el costo de las ventas (para el caso de las entidades financieras, los intereses recibidos e ingresos asimilables y los gastos por intereses y otros gastos asimilables), así como otras partidas en el estado del resultado integral por:
(i) los cambios habidos durante el periodo en los inventarios y en las partidas por cobrar y por pagar derivadas de las actividades de operación;
(ii) otras partidas no monetarias; y
(iii) otras partidas cuyos efectos en el efectivo se consideran flujos de efectivo de inversión o financiación.', number: '19', order: 29)
nic.contents.create!(text: 'En el método indirecto, el flujo neto por actividades de operación se determina corrigiendo la ganancia o la pérdida por los efectos de:
(a) los cambios habidos durante el periodo en los inventarios y en las partidas por cobrar y por pagar derivadas de las actividades de operación;
(b) las partidas sin reflejo en el efectivo, tales como depreciación, provisiones, impuestos diferidos, pérdidas y ganancias de cambio no realizadas y participación en ganancias no distribuidas de asociadas; y
(c) todas las otras partidas cuyos efectos monetarios se consideran flujos de efectivo de inversión o financiación.
Alternativamente, el flujo de efectivo neto de las actividades de operación puede presentarse, utilizando el método indirecto, mostrando las partidas de ingresos de actividades ordinarias y gastos reveladas en el estado del resultado integral, junto con los cambios habidos durante el periodo en los inventarios y en las cuentas por cobrar y por pagar derivadas de las actividades de operación.', number: '20', order: 30)

nic.contents.create!(text: 'Información sobre Flujos de Efectivo de las Actividades de Inversión y Financiamiento', label: 3, order: 31)
nic.contents.create!(text: 'La entidad debe informar por separado sobre las principales categorías de cobros y pagos brutos procedentes de actividades de inversión y financiación, excepto por lo que se refiere a los flujos de efectivo descritos en los párrafos 22 y 24 que pueden ser incluidos en términos netos.', number: '21', order: 32)

nic.contents.create!(text: 'Información sobre Flujos de Efectivo en Términos Netos', label: 3, order: 33)
nic.contents.create!(text: 'Los flujos de efectivo que proceden de los siguientes tipos de actividades de operación, de inversión y de financiación pueden presentarse en términos netos:
(a) cobros y pagos por cuenta de clientes, siempre y cuando los flujos de efectivo reflejen la actividad del cliente más que la correspondiente a la entidad; y
(b) cobros y pagos procedentes de partidas en las que la rotación es elevada, los importes grandes y el vencimiento próximo.', number: '22', order: 34)
nic.contents.create!(text: 'Ejemplos de cobros y pagos a los que se ha hecho referencia en el párrafo 22(a) son los siguientes:
(a) la aceptación y reembolso de depósitos a la vista por parte de un banco;
(b) los fondos de clientes que posee una entidad dedicada a la inversión financiera; y
(c) los alquileres cobrados por cuenta y pagados a los poseedores de propiedades de inversión.', number: '23', order: 35)
nic.contents.create!(text: 'Ejemplos de cobros y pagos a los que se ha hecho referencia en el párrafo 22(b) son los anticipos y reembolsos hechos por causa de:
(a) saldos relativos a tarjetas de crédito de clientes (parte correspondiente al principal);
(b) compra y venta de inversiones financieras; y
(c) otros préstamos tomados a corto plazo, por ejemplo, los convenidos con periodos de vencimiento de tres meses o menos.', number: '23a', order: 36)
nic.contents.create!(text: 'Los siguientes flujos de efectivo, procedentes de las actividades de una entidad financiera, pueden presentarse en términos netos:
(a) pagos y cobros por la aceptación y reembolso de depósitos con una fecha fija de vencimiento;
(b) colocación y recuperación de depósitos en otras instituciones financieras; y
(c) anticipos y préstamos hechos a clientes, así como el reembolso de tales partidas.', number: '24', order: 37)

nic.contents.create!(text: 'Flujos de Efectivo en la Moneda Extranjera', label: 3, order: 38)
nic.contents.create!(text: 'Los flujos de efectivo procedentes de transacciones en moneda extranjera se convertirán a la moneda funcional de la entidad aplicando al importe en moneda extranjera la tasa de cambio entre ambas monedas en la fecha en que se produjo cada flujo en cuestión.', number: '25', order: 39)
nic.contents.create!(text: 'Los flujos de efectivo de una subsidiaria extranjera se convertirán utilizando la tasa de cambio entre la moneda funcional y la moneda extranjera, en la fecha en que se produjo cada flujo en cuestión.', number: '26', order: 40)
nic.contents.create!(text: 'Los flujos de efectivo en moneda extranjera se presentarán de acuerdo con la NIC 21 Efectos de las Variaciones en las Tasas de Cambio de la Moneda Extranjera. En ella se permite utilizar una tasa de cambio que se aproxime al cambio efectivo de los conjuntos de transacciones. Por ejemplo, esto supone que puede utilizarse un promedio ponderado de las tasas de cambio de un periodo para contabilizar las transacciones en moneda extranjera o la conversión de los flujos de efectivo de una entidad subsidiaria. Sin embargo, la NIC 21 no permite utilizar la tasa de cambio al final del periodo sobre el que se informa cuando se convierten los flujos de efectivo de una subsidiaria extranjera.', number: '27', order: 41)
nic.contents.create!(text: 'Las pérdidas o ganancias no realizadas, por diferencias de cambio en moneda extranjera, no producen flujos de efectivo. Sin embargo, el efecto que la variación en las tasas de cambio tiene sobre el efectivo y los equivalentes al efectivo, mantenidos o debidos en moneda extranjera, será objeto de presentación en el estado de flujos de efectivo para permitir la conciliación entre las existencias de efectivo y equivalentes al efectivo al principio y al final del periodo. Este importe se presentará por separado de los flujos procedentes de las actividades de operación, inversión y financiación, y en el mismo se incluirán las diferencias que, en su caso, hubieran resultado de haber presentado esos flujos al cambio de cierre.', number: '28', order: 42)
nic.contents.create!(text: 'Eliminado', number: '29', order: 43)
nic.contents.create!(text: 'Eliminado', number: '30', order: 44)

nic.contents.create!(text: 'Intereses y Dividendos', label: 3, order: 45)
nic.contents.create!(text: 'Los flujos de efectivo correspondientes tanto a los intereses recibidos y pagados como a los dividendos percibidos y satisfechos deben ser revelados por separado. Cada una de las anteriores partidas debe ser clasificada de forma coherente, periodo a periodo, como perteneciente a actividades de operación, de inversión o de financiación.', number: '31', order: 46)
nic.contents.create!(text: 'El importe total de intereses pagados durante un periodo se revelará, en el estado de flujos de efectivo, tanto si ha sido reconocido como gasto en el resultado del periodo como si ha sido capitalizado, de acuerdo con la NIC 23 Costos por Préstamos.', number: '32', order: 47)
nic.contents.create!(text: 'Los intereses pagados, así como los intereses y dividendos percibidos, se clasificarán usualmente, en las entidades financieras, como flujos de efectivo por actividades de operación. Sin embargo, no existe consenso para la clasificación de este tipo de flujos en el resto de las entidades. Los intereses pagados, así como los intereses y dividendos percibidos, pueden ser clasificados como procedentes de actividades de operación, porque entran en la determinación de la ganancia o pérdida. De forma alternativa, los intereses pagados y los intereses y dividendos recibidos pueden clasificarse como flujos de efectivo por actividades de financiación e inversión respectivamente, porque son costos de obtener recursos financieros o rendimientos sobre inversiones.', number: '33', order: 48)
nic.contents.create!(text: 'Los dividendos pagados pueden clasificarse como flujos de efectivo de actividades financieras puesto que representan el costo de obtener recursos financieros. Alternativamente, pueden ser clasificados como componentes de los flujos procedentes de las actividades de operación, a fin de ayudar a los usuarios a determinar la capacidad de la entidad para atender los dividendos con flujos de efectivo procedentes de las actividades de operación.', number: '34', order: 49)

nic.contents.create!(text: 'Impuesto a las Ganancias', label: 3, order: 50)
nic.contents.create!(text: 'Los flujos de efectivo procedentes de pagos relacionados con el impuesto a las ganancias deben revelarse por separado, y deben ser clasificados como flujos de efectivo procedentes de actividades de operación, a menos que puedan ser específicamente asociados con actividades de financiación y de inversión.', number: '35', order: 51)
nic.contents.create!(text: 'Los impuestos sobre las ganancias que surgen de transacciones que dan lugar a flujos de efectivo que se clasifican como actividades de operación, de inversión o de financiación en el estado de flujos de efectivo. Aun cuando el gasto acumulado (o devengado) por impuestos sobre las ganancias pueda ser fácilmente asociable con determinadas actividades de inversión o financiación, los flujos de efectivo asociados al mismo son, a menudo, imposibles de identificar y pueden surgir en un periodo diferente del que corresponda a la transacción subyacente. Por eso, los impuestos pagados se clasifican normalmente como flujos de efectivo de actividades de operación. No obstante, cuando sea posible identificar el flujo impositivo con operaciones individuales que den lugar a cobros y pagos clasificados como actividades de inversión o financiación, se clasificará igual que la transacción a la que se refiere. En caso de distribuir el pago por impuestos entre más de un tipo de actividad, se informará también del importe total de impuestos pagados en el periodo.', number: '36', order: 52)

nic.contents.create!(text: 'Inversiones en Subsidiarias, Asociadas y Negocios Conjuntos', label: 3, order: 53)
nic.contents.create!(text: 'Cuando se contabilice una inversión en una asociada, un negocio conjunto o subsidiaria usando el método del costo o el de la participación, un inversor limitará su información, en el estado de flujos de efectivo, a los flujos de efectivo habidos entre él mismo y la entidad participada, por ejemplo, los dividendos y anticipos.', number: '37', order: 54)
nic.contents.create!(text: 'Una entidad que informe sobre su participación en una asociada o negocio conjunto utilizando el método de la participación, incluirá en su estado de flujos de efectivo los flujos de efectivo habidos por inversiones en la mencionada asociada o negocio conjunto, así como las distribuciones y otros pagos y cobros entre ambas entidades.', number: '38', order: 55)

nic.contents.create!(text: 'Cambios en las Participaciones de Propiedad en Subsidiarias y otros Negocios', label: 3, order: 56)
nic.contents.create!(text: 'Los flujos de efectivo agregados procedentes de la obtención o pérdida del control de subsidiarias u otros negocios deberán presentarse por separado, y clasificarse como actividades de inversión.', number: '39', order: 57)
nic.contents.create!(text: 'Una entidad revelará, de forma agregada, respecto de cada obtención y pérdida del control de subsidiarias y otros negocios habidos durante el periodo, todos y cada uno de los siguientes extremos:
(a) la contraprestación total pagada o recibida;
(b) la porción de la contraprestación en efectivo y equivalentes al efectivo;
(c) el importe de efectivo y equivalentes al efectivo en las subsidiarias u otros negocios sobre los que se obtiene o pierde el control; y
(d) el importe de los activos y pasivos, distintos de efectivo y equivalentes al efectivo en subsidiarias u otros negocios sobre los que se obtiene o pierde el control, agrupados por cada categoría principal.', number: '40', order: 58)
nic.contents.create!(text: 'Una entidad de inversión, tal como se define en la NIIF 10 Estados Financieros Consolidados, no necesita aplicar los párrafos 40(c) o 40(d) a una inversión en una subsidiaria que se requiera medir al valor razonable con cambios en resultados.', number: '40a', order: 59)
nic.contents.create!(text: 'La presentación por separado en una sola partida de las consecuencias sobre el efectivo de la obtención o pérdida del control de subsidiarias u otros negocios junto con la información a revelar por separado sobre los importes de activos y pasivos adquiridos o dispuestos, ayudará a distinguir estos flujos de efectivo de aquéllos que surgen de otras actividades de operación, de inversión o de financiación. Las consecuencias sobre el flujo de efectivo de la pérdida del control no se deducirán de las resultantes de la obtención del control.', number: '41', order: 60)
nic.contents.create!(text: 'El importe agregado del efectivo pagado o recibido como contraprestación por la obtención o pérdida del control de subsidiarias u otros negocios se incluirá en el estado de flujos de efectivo neto del efectivo y equivalentes al efectivo adquiridos o dispuestos como parte de estas transacciones, sucesos o cambios en las circunstancias.', number: '42', order: 61)
nic.contents.create!(text: 'Los flujos de efectivo que surgen de cambios en las participaciones en la propiedad de una subsidiaria que no dan lugar a una pérdida de control se clasificarán como flujos de efectivo procedentes de actividades de financiación, a menos que la subsidiaria sea mantenida por una entidad de inversión, tal como se define en la NIIF 10, y se requiera medir al valor razonable con cambios en resultados.', number: '42a', order: 62)
nic.contents.create!(text: 'Los cambios en las participaciones en la propiedad de una subsidiaria que no den lugar a una pérdida de control, tales como la compra o venta posteriores por la controladora de instrumentos de patrimonio de una subsidiaria, se contabilizarán como transacciones de patrimonio (véase la NIIF 10), a menos que la subsidiaria se mantenga por una entidad de inversión, y que se requiera medir al valor razonable con cambios en resultados. Por consiguiente, los flujos de efectivos resultantes se clasificarán de la misma forma que otras transacciones con los propietarios descritas en el párrafo 17.', number: '42b', order: 63)

nic.contents.create!(text: 'Transacciones No Monetarias', label: 3, order: 64)
nic.contents.create!(text: 'Las transacciones de inversión o financiación que no han requerido el uso de efectivo o equivalentes al efectivo se excluirán del estado de flujos de efectivo. Estas transacciones deben ser objeto de información, en cualquier otra parte dentro de los estados financieros, de manera que suministren toda la información relevante acerca de tales actividades de inversión o financiación.', number: '43', order: 65)
nic.contents.create!(text: 'Muchas actividades de inversión o financiación no tienen un impacto directo en los flujos de efectivo del periodo, a pesar de que afectan a la estructura de los activos y del capital utilizado por la entidad. La exclusión de esas transacciones no monetarias del estado de flujos de efectivo resulta coherente con el objetivo de un estado de flujos de efectivo, puesto que tales partidas no producen flujos de efectivo en el periodo corriente. Ejemplos de transacciones no monetarias de este tipo son:
(a) la adquisición de activos ya sea asumiendo directamente los pasivos relacionados, o mediante un arrendamiento;
(b) la compra de una entidad mediante una ampliación de capital; y
(c) la conversión de deuda en patrimonio.', number: '44', order: 66)

nic.contents.create!(text: 'Cambios en los Pasivos que surgen de las Actividades de Financiación', label: 3, order: 67)
nic.contents.create!(text: 'Una entidad revelará la información que permita a los usuarios de los estados financieros evaluar los cambios en pasivos producidos por actividades de financiación, incluyendo tanto los derivados de flujos de efectivo como los que no implican flujos de efectivo.', number: '44a', order: 68)
nic.contents.create!(text: '44b En la medida en que sea necesaria para satisfacer el requerimiento del párrafo 44A, una entidad revelará los cambios siguientes en los pasivos que surgen de actividades de financiación:
(a) cambios procedentes de los flujos de efectivo por financiación;
(b) cambios que surgen de la obtención o pérdida del control de subsidiarias u otros negocios;
(c) Efectos de las variaciones en las tasas de cambio de la moneda extranjera.
(d) cambios en el valor razonable; y (e) otros cambios.', number: '44b', order: 69)
nic.contents.create!(text: 'Los pasivos que se derivan de actividades de financiación son pasivos para los que los flujos de efectivo se han clasificado, o se clasificarán en el futuro, en el estado de flujos de efectivo como flujos de efectivo procedentes de actividades de financiación. Además, el requerimiento de información a revelar del párrafo 44A también se aplica a cambios en los activos financieros (por ejemplo, activos que cubren pasivos que surgen de actividades de financiación) si los flujos de efectivo procedentes de esas actividades de financiación se han incluido, o se incluirán en el futuro, dentro de los flujos de efectivo procedentes de actividades de financiación.', number: '44c', order: 70)
nic.contents.create!(text: 'Una forma de satisfacer el requerimiento del párrafo 44A es proporcionar una conciliación entre los saldos iniciales y finales del estado de situación financiera para pasivos que surgen de actividades de financiación, que contenga los cambios identificados en el párrafo 44B. Cuando una entidad revela esta conciliación, proporcionará información suficiente para permitir a los usuarios de los estados financieros vincular las partidas incluidas en la conciliación con el estado de situación financiera y el estado de flujos de efectivo.', number: '44d', order: 71)
nic.contents.create!(text: 'Si una entidad revela la información requerida por el párrafo 44A en combinación con la de los cambios en otros activos y pasivos, revelará los cambios en los pasivos que surgen de las actividades de financiación por separado de los cambios en los demás activos y pasivos.', number: '44e', order: 72)

nic.contents.create!(text: 'Componentes de la Partida Efectivo y Equivalentes al Efectivo', label: 3, order: 73)
nic.contents.create!(text: 'Una entidad revelará los componentes del efectivo y equivalentes al efectivo, y presentará una conciliación de los importes de su estado de flujos de efectivo con las partidas equivalentes sobre las que se informa en el estado de situación financiera.', number: '45', order: 74)
nic.contents.create!(text: 'Las entidades revelarán los criterios adoptados para determinar la composición de la partida en efectivo y equivalentes al efectivo, por causa de la variedad de prácticas de gestión de efectivo y de servicios bancarios relacionados con ella en todos los países del mundo, y además para dar cumplimiento a lo previsto en la NIC 1 Presentación de Estados Financieros.', number: '46', order: 75)
nic.contents.create!(text: 'El resultado de cualquier cambio en las políticas de determinación del efectivo y equivalentes al efectivo, por ejemplo, un cambio en la clasificación de instrumentos financieros que antes se consideraban parte de la cartera de inversión, se presentará en los estados financieros de la entidad, de acuerdo con la NIC 8 Políticas Contables, Cambios en las Estimaciones Contables y Errores.', number: '47', order: 76)

nic.contents.create!(text: 'Información a Revelar', label: 3, order: 77)
nic.contents.create!(text: 'La entidad debe revelar en sus estados financieros, acompañado de un comentario por parte de la gerencia, cualquier importe significativo de sus saldos de efectivo y equivalentes al efectivo que no esté disponible para ser utilizado por ella misma o por el grupo al que pertenece.', number: '48', order: 78)
nic.contents.create!(text: 'Existen diversas circunstancias en las que los saldos de efectivo y equivalentes al efectivo mantenidos por la entidad no están disponibles para su uso por parte del grupo. Un ejemplo de tal situación son los saldos de efectivo y equivalentes al efectivo de una subsidiaria que opera en un país donde existen controles de cambio u otras restricciones legales, de manera que los citados saldos no están disponibles para uso de la controladora o de las demás subsidiarias.', number: '49', order: 79)
nic.contents.create!(text: 'Puede ser relevante, para los usuarios, conocer determinadas informaciones adicionales sobre la entidad que les ayuden a comprender su posición financiera y liquidez. Por tanto, se aconseja a las entidades que publiquen, junto con un comentario de la gerencia, informaciones tales como las siguientes:
(a) el importe de los préstamos no dispuestos que pueden estar disponibles para actividades de operación o para el pago de operaciones de inversión o financiación, indicando las restricciones sobre el uso de tales medios financieros;
(b) [eliminado]
(c) el importe acumulado de flujos de efectivo que representen incrementos en la capacidad de operación, separado de aquéllos otros que se requieran para mantener la capacidad de operación de la entidad; y
(d) el importe de los flujos de efectivo por actividades de operación, de inversión y de financiación, que procedan de cada uno de los segmentos sobre los que debe informarse (véase la NIIF 8 Segmentos de Operación).', number: '50', order: 80)
nic.contents.create!(text: 'La información, por separado, de los flujos de efectivo que incrementan la capacidad operativa, distinguiéndolos de aquellos otros que sirven para mantenerla, es útil por permitir a los usuarios juzgar acerca de si la entidad está invirtiendo adecuadamente para mantener su capacidad operativa. Toda entidad que no esté invirtiendo adecuadamente en el mantenimiento de su capacidad operativa puede estar perjudicando su rendimiento futuro a cambio de mejorar la liquidez presente y las distribuciones de ganancias a los propietarios.', number: '51', order: 81)
nic.contents.create!(text: 'La presentación de flujos de efectivo por segmentos permitirá a los usuarios obtener una mejor comprensión de las relaciones entre los flujos de efectivo de la entidad en su conjunto y los de cada una de sus partes integrantes, así como de la variabilidad y disponibilidad de los flujos de los segmentos considerados.', number: '52', order: 82)
