puts 'Nic8'

nic = Nic.create(category_id:5, number:8, name:'Políticas Contables, Cambios En Las Estimaciones Contables Y Errores')

puts "Se creó #{nic.name}"

nic.contents.create!(text: 'Objetivo', label: 3, order: 1)
nic.contents.create!(text:'El objetivo de esta Norma es prescribir los criterios para seleccionar y modificar las políticas contables, así como el tratamiento contable y la información a revelar acerca de los cambios en las políticas contables, de los cambios en las estimaciones contables y de la corrección de errores. La Norma trata de realzar la relevancia y fiabilidad de los estados financieros de una entidad, así como la comparabilidad con los estados financieros emitidos por ésta en periodos anteriores, y con los elaborados por otras entidades.',number: '1', order: 2)
nic.contents.create!(text:'Los requerimientos de información a revelar relativos a políticas contables, excepto los referentes a cambios en las políticas contables han sido establecidos en la NIC 1 Presentación de Estados Financieros.',number: '2', order: 3)

nic.contents.create!(text: 'Alcance', label: 3, order: 4)
nic.contents.create!(text:'Esta Norma se aplicará en la selección y aplicación de políticas contables, así como en la contabilización de los cambios en éstas, los cambios en las estimaciones contables y en la corrección de errores de periodos anteriores.',number: '3', order: 5)
nic.contents.create!(text:'El efecto impositivo de la corrección de los errores de periodos anteriores, así como de los ajustes retroactivos efectuados al realizar cambios en las políticas contables se contabilizará de acuerdo con la NIC 12 Impuesto a las Ganancias, y se revelará la información requerida por esta Norma.',number: '4', order: 6)

nic.contents.create!(text: 'Definiciones', label: 3, order: 7)
nic.contents.create!(text:'Los términos siguientes se usan, en esta Norma, con los significados que a continuación se especifican:
Políticas contables son los principios, bases, acuerdos, reglas y procedimientos específicos adoptados por la entidad en la elaboración y presentación de sus estados financieros. Un cambio en una estimación contable es un ajuste en el importe en libros de un activo o de un pasivo, o en el importe del consumo periódico de un activo, que se produce tras la evaluación de la situación actual del elemento, así como de los beneficios futuros esperados y de las obligaciones asociadas con los activos y pasivos correspondientes. Los cambios en las estimaciones contables son el resultado de nueva información o nuevos acontecimientos y, en consecuencia, no son correcciones de errores. Las Normas Internacionales de Información Financiera (NIIF) son las Normas e Interpretaciones emitidas por el Consejo de Normas Internacionales de Contabilidad (IASB). Esas Normas comprenden:
(a) Normas Internacionales de Información Financiera;
(b) las Normas Internacionales de Contabilidad;
(c) las Interpretaciones CINIIF; y
(d) Interpretaciones SIC.1
Material se define en el párrafo 7 de la NIC 1 y se utiliza en esta Norma con el mismo significado. Errores de periodos anteriores son las omisiones e inexactitudes en los estados financieros de una entidad, para uno o más periodos anteriores, resultantes de un fallo al emplear o de un error al utilizar información fiable que:
(a) estaba disponible cuando los estados financieros para tales periodos fueron formulados; y
(b) podría esperarse razonablemente que se hubiera conseguido y tenido en cuenta en la elaboración y presentación de aquellos estados financieros. Dentro de estos errores se incluyen los efectos de errores aritméticos, errores en la aplicación de políticas contables, la inadvertencia o mala interpretación de hechos, así como los fraudes. La aplicación retroactiva consiste en aplicar una nueva política contable a transacciones, otros sucesos y condiciones, como si ésta se hubiera aplicado siempre.
La reexpresión retroactiva consiste en corregir el reconocimiento, medición e información a revelar de los importes de los elementos de los estados financieros, como si el error cometido en periodos anteriores no se hubiera cometido nunca. Impracticable La aplicación de un requerimiento es impracticable cuando la entidad no pueda aplicarlo tras efectuar todos los esfuerzos razonables para hacerlo. Para un periodo anterior en particular, es impracticable aplicar un cambio en una política contable retroactivamente o realizar una reexpresión retroactiva para corregir un error si:
(a) los efectos de la aplicación o de la reexpresión retroactivas no son determinables;
(b) la aplicación o la reexpresión retroactivas implican establecer suposiciones acerca de cuáles hubieran podido ser las intenciones de la gerencia en ese periodo; o (c) la aplicación o la reexpresión retroactivas requieren estimaciones de importes significativos, y es imposible distinguir objetivamente información de tales estimaciones que:
1 Definición de las NIIF modificada después de los cambios de nombre introducidos mediante la Constitución revisada de la Fundación IFRS en 2010.
(i) suministre evidencia de las circunstancias que existían en la fecha o fechas en que tales importes fueron reconocidos, medidos o fue revelada la correspondiente información; y
(ii) hubiera estado disponible cuando los estados financieros de los periodos anteriores fueron autorizados para su emisión a partir de otra información. La aplicación prospectiva de un cambio en una política contable y del reconocimiento del efecto de un cambio en una estimación contable consiste, respectivamente, en:
(a) la aplicación de la nueva política contable a las transacciones, otros sucesos y condiciones ocurridos tras la fecha en que se cambió la política; y
(b) el reconocimiento del efecto del cambio en la estimación contable para el periodo corriente y los periodos futuros afectados por dicho cambio.',number: '5', order: 8)
nic.contents.create!(text:'[Eliminado]',number: '6', order: 9)

nic.contents.create!(text: 'Políticas Contables', label: 3, order: 10)
nic.contents.create!(text: 'Selección Y Aplicación De Políticas Contables', label: 4, order: 11)
nic.contents.create!(text:'Cuando una NIIF sea específicamente aplicable a una transacción, otro evento o condición, la política o políticas contables aplicadas a esa partida se determinarán aplicando la NIIF concreta.',number: '7', order: 12)
nic.contents.create!(text:'En las NIIF se establecen políticas contables sobre las que el IASB ha llegado a la conclusión de que dan lugar a estados financieros que contienen información relevante y fiable sobre las transacciones, otros eventos y condiciones a las que son aplicables. Estas políticas no necesitan ser aplicadas cuando el efecto de su utilización no sea significativo. Sin embargo, no es adecuado dejar de aplicar las NIIF, o dejar de corregir errores, apoyándose en que el efecto no es significativo, con el fin de alcanzar una presentación particular de la posición financiera, el rendimiento financiero o los flujos de efectivo de la entidad.',number: '8', order: 13)
nic.contents.create!(text:'Las NIIF se acompañan de guías que ayudan a las entidades a aplicar sus requerimientos. Todas estas guías señalan si son parte integrante de las NIIF. Las guías que sean parte integrante de las NIIF serán de cumplimiento obligatorio. Las guías que no sean parte integrante de las NIIF no contienen requerimientos aplicables a los estados financieros.',number: '9', order: 14)
nic.contents.create!(text:'En ausencia de una NIIF que sea aplicable específicamente a una transacción o a otros hechos o condiciones, la gerencia deberá usar su juicio en el desarrollo y aplicación de una política contable, a fin de suministrar información que sea:
(a) relevante para las necesidades de toma de decisiones económicas de los usuarios; y
(b) fiable, en el sentido de que los estados financieros:
(i) presenten de forma fidedigna la situación financiera, el rendimiento financiero y los flujos de efectivo de la entidad;
(ii) reflejen la esencia económica de las transacciones, otros eventos y condiciones, y no simplemente su forma legal;
(iii) sean neutrales, es decir, libres de prejuicios o sesgos;
(iv) sean prudentes; y
(v) estén completos en todos sus extremos significativos.',number: '10', order: 15)
nic.contents.create!(text:'Al realizar los juicios descritos en el párrafo 10, la gerencia se referirá, en orden descendente, a las siguientes fuentes a la hora de considerar su aplicabilidad:
(a) los requerimientos de las NIIF que traten temas similares y relacionados; y
(b) las definiciones, los criterios de reconocimiento y medición de activos, pasivos, ingresos y gastos establecidos en el Marco Conceptual para la Información Financiera (Marco Conceptual).2',number: '11', order: 16)
nic.contents.create!(text:'Al realizar los juicios descritos en el párrafo 10, la gerencia podrá considerar también los pronunciamientos más recientes de otras instituciones emisoras de normas que empleen un marco conceptual similar al emitir normas contables, así como otra literatura contable y las prácticas aceptadas en los diferentes sectores de actividad, en la medida que no entren en conflicto con las fuentes señaladas en el párrafo 11.',number: '12', order: 17)

nic.contents.create!(text: 'Uniformidad De Las Políticas Contables', label: 3, order: 18)
nic.contents.create!(text:'Una entidad seleccionará y aplicará sus políticas contables de manera uniforme para transacciones, otros eventos y condiciones que sean similares, a menos que una NIIF requiera o permita específicamente establecer categorías de partidas para las cuales podría ser apropiado aplicar diferentes políticas. Si una NIIF requiere o permite establecer esas categorías, se seleccionará una política contable adecuada, y se aplicará de manera uniforme a cada categoría.',number: '13', order: 19)

nic.contents.create!(text: 'Objetivo', label: 3, order: 20)
nic.contents.create!(text:'La entidad cambiará una política contable sólo si tal cambio:
(a) se requiere por una NIIF; o
(b) lleva a que los estados financieros suministren información fiable y más relevante sobre los efectos de las transacciones, otros eventos o condiciones que afecten a la situación financiera, el rendimiento financiero o los flujos de efectivo de la entidad.',number: '14', order: 21)
nic.contents.create!(text: '2 El párrafo 54G explica cómo se modifica este requerimiento para los saldos contables de actividades reguladas.', label: 7, order: 22)
nic.contents.create!(text:'Los usuarios de los estados financieros tienen la necesidad de poder comparar los estados financieros de una entidad a lo largo del tiempo, a fin de identificar tendencias en su situación financiera, rendimiento financiero y flujos de efectivo. En consecuencia, se aplicarán las mismas políticas contables dentro de cada periodo, así como de un periodo a otro, excepto si se presentase algún cambio en una política contable que cumpliera alguno de los criterios del párrafo 14.',number: '15', order: 23)
nic.contents.create!(text:'Las siguientes situaciones no constituyen cambios en las políticas contables: (a) la aplicación de una política contable para transacciones, otros eventos o condiciones que difieren sustancialmente de aquéllos que han ocurrido previamente; y (b) la aplicación de una nueva política contable para transacciones, otros eventos o condiciones que no han ocurrido anteriormente o que, de ocurrir, carecieron de materialidad.',number: '16', order: 24)
nic.contents.create!(text:'La aplicación por primera vez de una política que consista en la revaluación de activos, de acuerdo con la NIC 16 Propiedades, Planta y Equipo, o con la NIC 38 Activos Intangibles, es un cambio de política contable que ha de ser tratado como una revaluación, de acuerdo con la NIC 16 o con la NIC 38, en lugar de aplicar las disposiciones contenidas en esta Norma.',number: '17', order: 25)
nic.contents.create!(text:'Los párrafos 19 a 31 no serán de aplicación a los cambios en las políticas contables descritos en el párrafo 17.',number: '18', order: 26)

nic.contents.create!(text: 'Aplicación De Los Cambios En Políticas Contables', label: 3, order: 27)
nic.contents.create!(text:'Con sujeción al párrafo 23: (a) la entidad contabilizará un cambio en una política contable derivado de la aplicación inicial de una NIIF, de acuerdo con las disposiciones transitorias específicas de tales NIIF, si las hubiera; y (b) cuando la entidad cambie una política contable, ya sea por la aplicación inicial de una NIIF que no incluya una disposición transitoria específica aplicable a tal cambio, o porque haya decidido cambiarla de forma voluntaria, aplicará dicho cambio retroactivamente.',number: '19', order: 27)
nic.contents.create!(text:'Para los propósitos de esta Norma, la aplicación anticipada de una NIIF no se considerará un cambio voluntario en una política contable.',number: '20', order: 28)
nic.contents.create!(text:'En ausencia de una NIIF específicamente aplicable a una transacción u otros eventos o condiciones, la gerencia podrá, de acuerdo con el párrafo 12, aplicar una política contable considerando los pronunciamientos más recientes de otras instituciones emisoras de normas que empleen un marco conceptual similar al emitir normas contables. Si, debido a una modificación de tal pronunciamiento, la entidad optase por el cambio de una política contable, ese cambio se contabilizará y se revelará como un cambio voluntario de una política contable.',number: '21', order: 29)

nic.contents.create!(text: 'Aplicación Retroactiva', label: 3, order: 30)
nic.contents.create!(text:'Con sujeción a la limitación establecida en el párrafo 23, cuando un cambio en una política contable se aplique retroactivamente de acuerdo con los apartados (a) o (b) del párrafo 19, la entidad ajustará los saldos iniciales de cada componente afectado del patrimonio para el periodo anterior más antiguo que se presente, revelando información acerca de los demás importes comparativos para cada periodo anterior presentado, como si la nueva política contable se hubiese estado aplicando siempre.',number: '22', order: 31)

nic.contents.create!(text: 'Limitaciones A La Aplicación Retroactiva', label: 3, order: 32)
nic.contents.create!(text:'Cuando sea obligatoria la aplicación retroactiva en función de lo establecido en los apartados (a) o (b) del párrafo 19, el cambio en la política contable se aplicará retroactivamente, salvo y en la medida en que fuera impracticable determinar los efectos del cambio en cada periodo específico o el efecto acumulado.',number: '23', order: 33)
nic.contents.create!(text:'Cuando sea impracticable determinar los efectos que se derivan, en cada periodo específico, del cambio de una política contable sobre la información comparativa en uno o más periodos anteriores para los que se presente información, la entidad aplicará la nueva política contable a los saldos iniciales de los activos y pasivos al principio del periodo más antiguo para el que la aplicación retroactiva sea practicable —que podría ser el propio periodo corriente— y efectuará el correspondiente ajuste a los saldos iniciales de cada componente del patrimonio que se vea afectado para ese periodo.',number: '24', order: 34)
nic.contents.create!(text:'Cuando sea impracticable determinar el efecto acumulado, al principio del periodo corriente, por la aplicación de una nueva política contable a todos los periodos anteriores, la entidad ajustará la información comparativa aplicando la nueva política contable de forma prospectiva, desde la fecha más antigua en que sea practicable hacerlo.',number: '25', order: 35)
nic.contents.create!(text:'Cuando la entidad aplique una nueva política contable retroactivamente, la aplicará a la información comparativa de periodos anteriores, retrotrayéndose en el tiempo tanto como sea practicable. La aplicación retroactiva a un periodo anterior no será practicable a menos que sea posible determinar el efecto acumulado tanto sobre los importes de apertura como de cierre del estado de situación financiera correspondiente a ese periodo. El importe del ajuste resultante, referido a los periodos previos a los presentados en los estados financieros, se llevará contra los saldos iniciales de cada componente afectado del patrimonio del periodo previo más antiguo sobre el que se presente información. Normalmente, el ajuste se hace contra las ganancias acumuladas. Sin embargo, los ajustes pueden hacerse contra otro componente del patrimonio (por ejemplo, para cumplir con una NIIF). Cualquier otro tipo de información que se incluya respecto a periodos anteriores, tal como resúmenes históricos de datos financieros, será asimismo objeto de ajuste, retrotrayéndose en el tiempo tanto como sea practicable.',number: '26', order: 36)
nic.contents.create!(text:'Cuando sea impracticable para la entidad aplicar una nueva política contable retroactivamente, debido a que no pueda determinar el efecto acumulado de la aplicación de la política para todos los periodos anteriores, la entidad, de acuerdo con el párrafo 25, aplicará la nueva política contable de forma prospectiva desde el inicio del periodo más antiguo que sea practicable. En consecuencia, se ignorará la porción del ajuste acumulado de los activos, pasivos y patrimonio surgido antes de esa fecha. Se permitirán los cambios de políticas contables, incluso si fuera impracticable la aplicación de dicha política de forma prospectiva a algún periodo anterior. Los párrafos 50 a 53 suministran guías sobre cuándo resulta impracticable aplicar una nueva política contable a uno o más periodos anteriores.',number: '27', order: 37)

nic.contents.create!(text: 'Información A Revelar', label: 3, order: 38)
nic.contents.create!(text:'Cuando la aplicación por primera vez de una NIIF tenga efecto en el periodo corriente o en alguno anterior —salvo que fuera impracticable determinar el importe del ajuste— o bien pudiera tener efecto sobre periodos futuros, la entidad revelará:
(a) el título de la NIIF;
(b) en su caso, que el cambio en la política contable se ha efectuado de acuerdo con su disposición transitoria;
(c) la naturaleza del cambio en la política contable;
(d) en su caso, una descripción de la disposición transitoria;
(e) en su caso, la disposición transitoria que podría tener efectos sobre periodos futuros;
(f) para el periodo corriente y para cada periodo anterior presentado, en la medida en que sea practicable, el importe del ajuste:
(i) para cada partida del estado financiero que se vea afectada; y
(ii) si la NIC 33 Ganancias por Acción es aplicable a la entidad, para las ganancias por acción tanto básicas como diluidas;
(g) el importe del ajuste relativo a periodos anteriores presentados, en la medida en que sea practicable; y
(h) si la aplicación retroactiva exigida por los apartados (a) o (b) del párrafo 19 fuera impracticable para un periodo previo en concreto, o para periodos anteriores sobre los que se presente información, las circunstancias que conducen a la existencia de esa situación, y una descripción de cómo y desde cuándo se ha aplicado el cambio en la política contable.',number: '28', order: 38)
nic.contents.create!(text: 'No es necesario repetir esta información a revelar en estados financieros de periodos posteriores.', label: 7, order: 39)
nic.contents.create!(text:'Cuando un cambio voluntario en una política contable tenga efecto en el periodo corriente o en alguno anterior, tendría efecto en ese periodo excepto que sea impracticable determinar el importe del ajuste— o bien pudiera tener efecto sobre periodos futuros, la entidad revelará:
(a) la naturaleza del cambio en la política contable;
(b) las razones por las que la aplicación de la nueva política contable suministra información fiable y más relevante;
(c) para el periodo corriente y para cada periodo anterior presentado, en la medida en que sea practicable, el importe del ajuste:
(i) para cada partida del estado financiero que se vea afectada; y
(ii) si la NIC 33 es aplicable a la entidad, para las ganancias por acción tanto básicas como diluidas;
(d) el importe del ajuste relativo a periodos anteriores presentados, en la medida en que sea practicable; y
(e) si la aplicación retroactiva fuera impracticable para un periodo anterior en particular, o para periodos anteriores presentados, las circunstancias que conducen a esa situación, junto con una descripción de cómo y desde cuándo se ha aplicado el cambio en la política contable.',number: '29', order: 39)

nic.contents.create!(text: 'Esta información a revelar podrá omitirse en los estados financieros de periodos posteriores.', label: 3, order: 40)
nic.contents.create!(text:'Cuando una entidad no haya aplicado una nueva NIIF que, habiendo sido emitida, todavía no ha entrado en vigor, la entidad deberá revelar:
(a) este hecho; y
(b) información relevante, conocida o razonablemente estimada, para evaluar el posible impacto que la aplicación de la nueva NIIF tendrá sobre los estados financieros de la entidad en el periodo en que se aplique por primera vez.',number: '30', order: 41)
nic.contents.create!(text:'Para cumplir con el párrafo 30, la entidad revelará:
(a) el título de la nueva NIIF;
(b) la naturaleza del cambio o cambios inminentes en la política contable;
(c) la fecha en la cual es obligatoria la aplicación de la NIIF;
(d) la fecha a partir de la que está previsto aplicar la NIIF por primera vez; y
(e) una u otra de las siguientes informaciones:
(i) una explicación del impacto esperado, derivado de la aplicación inicial de la NIIF, sobre los estados financieros de la entidad; o
(ii) si el impacto fuera desconocido o no pudiera ser estimado razonablemente, una declaración al efecto.',number: '31', order: 42)

nic.contents.create!(text: 'Cambios En Las Estimaciones Contables', label: 3, order: 43)
nic.contents.create!(text:'Como resultado de las incertidumbres inherentes al mundo de los negocios, muchas partidas de los estados financieros no pueden ser medidas con precisión, sino sólo estimadas. El proceso de estimación implica la utilización de juicios basados en la información fiable disponible más reciente. Por ejemplo, podría requerirse estimaciones para:
(a) las cuentas por cobrar de dudosa recuperación;
(b) la obsolescencia de los inventarios;
(c) el valor razonable de activos o pasivos financieros;
(d) la vida útil o las pautas de consumo esperadas de los beneficios económicos futuros incorporados en los activos depreciables; y
(e) las obligaciones por garantías concedidas.',number: '32', order: 44)
nic.contents.create!(text:'La utilización de estimaciones razonables es una parte esencial de la elaboración de los estados financieros, y no menoscaba su fiabilidad.',number: '33', order: 45)
nic.contents.create!(text:'Si se produjesen cambios en las circunstancias en que se basa la estimación, es posible que ésta pueda necesitar ser revisada, como consecuencia de nueva información obtenida o de poseer más experiencia. La revisión de la estimación, por su propia naturaleza, no está relacionada con periodos anteriores ni tampoco es una corrección de un error.',number: '34', order: 46)
nic.contents.create!(text:'Un cambio en los criterios de medición aplicados es un cambio en una política contable, y no un cambio en una estimación contable. Cuando sea difícil distinguir entre un cambio de política contable y un cambio en una estimación contable, el cambio se tratará como si fuera un cambio en una estimación contable.',number: '35', order: 47)
nic.contents.create!(text:'El efecto de un cambio en una estimación contable, diferente de aquellos cambios a los que se aplique el párrafo 37, se reconocerá de forma prospectiva, incluyéndolo en el resultado de:
(a) el periodo en que tiene lugar el cambio, si éste afecta solo a ese periodo; o
(b) el periodo del cambio y periodos futuros, si el cambio afectase a todos ellos.',number: '36', order: 48)
nic.contents.create!(text:'En la medida que un cambio en una estimación contable dé lugar a cambios en activos y pasivos, o se refiera a una partida de patrimonio, deberá ser reconocido ajustando el valor en libros de la correspondiente partida de activo, pasivo o patrimonio en el periodo en que tiene lugar el cambio.',number: '37', order: 49)
nic.contents.create!(text:'El reconocimiento prospectivo del efecto de un cambio en una estimación contable significa que el cambio se aplica a las transacciones, otros eventos y condiciones, desde la fecha del cambio en la estimación. Un cambio en una estimación contable podría afectar únicamente al resultado del periodo corriente, o bien al de éste y al de periodos futuros. Por ejemplo, un cambio en las estimaciones del importe de los clientes de dudoso cobro afectará sólo al resultado del periodo corriente y, por tanto, se reconocerá en este periodo. Sin embargo, un cambio en la vida útil estimada, o en los patrones de consumo de los beneficios económicos futuros incorporados a un activo depreciable, afectará al gasto por depreciación del periodo corriente y de cada uno de los periodos de vida útil restante del activo. En ambos casos, el efecto del cambio relacionado con el periodo corriente se reconoce como ingreso o gasto del periodo corriente. El efecto, si existiese, en periodos futuros se reconoce como ingreso o gasto de dichos periodos futuros.',number: '38', order: 50)

nic.contents.create!(text: 'Información A Revelar', label: 3, order: 51)
nic.contents.create!(text:'La entidad revelará la naturaleza e importe de cualquier cambio en una estimación contable que haya producido efectos en el periodo corriente, o que se espere vaya a producirlos en periodos futuros, exceptuándose de lo anterior la revelación de información del efecto sobre periodos futuros, en el caso de que fuera impracticable estimar ese efecto.',number: '39', order: 52)
nic.contents.create!(text:'Si no se revela el importe del efecto en periodos futuros debido a que la estimación es impracticable, la entidad revelará este hecho.',number: '40', order: 53)

nic.contents.create!(text: 'Errores', label: 3, order: 54)
nic.contents.create!(text:'Los errores pueden surgir al reconocer, valorar, presentar o revelar la información de los elementos de los estados financieros. Los estados financieros no cumplen con las NIIF si contienen errores, tanto materiales como inmateriales, cuando han sido cometidos intencionadamente para conseguir, respecto de una entidad, una determinada presentación de su situación financiera, de su rendimiento financiero o de sus flujos de efectivo. Los errores potenciales del periodo corriente, descubiertos en este mismo periodo, se corregirán antes de que los estados financieros sean autorizados para la emisión. Sin embargo, los errores materiales en ocasiones no se descubren hasta un periodo posterior, de forma que tales errores de periodos anteriores se corregirán en la información comparativa presentada en los estados financieros de los periodos siguientes (véanse los párrafos 42 a 47).',number: '41', order: 55)
nic.contents.create!(text:'Con sujeción a lo establecido en el párrafo 43, la entidad corregirá los errores materiales de periodos anteriores, de forma retroactiva, en los primeros estados financieros formulados después de haberlos descubierto:
(a) Re expresando la información comparativa para el periodo o periodos anteriores en los que se originó el error; o
(b) si el error ocurrió con anterioridad al periodo más antiguo para el que se presenta información, Re expresando los saldos iniciales de activos, pasivos y patrimonio para dicho periodo.',number: '42', order: 56)

nic.contents.create!(text: 'Limitaciones A La Reexpresión Retroactiva', label: 3, order: 57)
nic.contents.create!(text:'El error correspondiente a un periodo anterior se corregirá mediante la reexpresión retroactiva, salvo que sea impracticable determinar los efectos en cada periodo específico o el efecto acumulado del error.',number: '43', order: 58)
nic.contents.create!(text:'Cuando sea impracticable determinar los efectos que se derivan, en cada periodo específico, de un error sobre la información comparativa de uno o más periodos anteriores para los que se presente información, la entidad re expresará los saldos iniciales de los activos, pasivos y patrimonio para los periodos más antiguos en los cuales tal reexpresión retroactiva sea practicable (que podría también ser el propio periodo corriente).',number: '44', order: 59)
nic.contents.create!(text:'Cuando sea impracticable determinar el efecto acumulado, al principio del periodo actual, de un error sobre todos los periodos anteriores, la entidad re expresará la información comparativa corrigiendo el error de forma prospectiva, desde la fecha más antigua en que sea practicable hacerlo.',number: '45', order: 60)
nic.contents.create!(text:'El efecto de la corrección de un error de periodos anteriores no se incluirá en el resultado del periodo en el que se descubra el error. Cualquier otro tipo de información que se incluya respecto a periodos anteriores, tales como resúmenes históricos de datos financieros, será objeto de reexpresión, yendo tan atrás como sea posible.',number: '46', order: 61)
nic.contents.create!(text:'Cuando sea impracticable determinar el importe de un error para todos los periodos previos (por ejemplo, una equivocación al aplicar una política contable), la entidad, de acuerdo con el párrafo 45, Re expresará la información comparativa de forma prospectiva desde la fecha más remota posible. En consecuencia, se ignorará la porción del ajuste acumulado de activos, pasivos y patrimonio que haya surgido antes de esa fecha. En los párrafos 50 a 53 se suministran guías sobre cuándo resulta impracticable corregir un error para uno o más periodos anteriores.',number: '47', order: 63)
nic.contents.create!(text:'La corrección de errores puede distinguirse con facilidad de los cambios en las estimaciones contables. Las estimaciones contables son, por su naturaleza, aproximaciones que pueden necesitar revisión cuando se tenga conocimiento de información adicional. Por ejemplo, las pérdidas o ganancias reconocidas como resultado del desenlace de una contingencia no constituyen corrección de un error.',number: '48', order: 64)

nic.contents.create!(text: 'Información A Revelar Sobre Errores De Periodos Anteriores', label: 3, order: 65)
nic.contents.create!(text:'En aplicación del párrafo 42, una entidad revelará la siguiente información: (a) la naturaleza del error del periodo anterior;
(b) para cada periodo anterior presentado, en la medida que sea practicable, el importe del ajuste:
(i) para cada partida del estado financiero que se vea afectada; y
(ii) para el importe de la ganancia por acción tanto básica como diluida, si la NIC 33 fuera aplicable a la entidad;
(c) el importe del ajuste al principio del periodo anterior más antiguo sobre el que se presente información; y
(d) si fuera impracticable la reexpresión retroactiva para un periodo anterior en particular, las circunstancias que conducen a esa situación, junto con una descripción de cómo y desde cuándo se ha corregido el error. No es necesario repetir esta información a revelar en estados financieros de periodos posteriores.',number: '49', order: 66)

nic.contents.create!(text: 'Impracticabilidad De La Aplicación Y De La Reexpresión Retroactivas', label: 3, order: 67)
nic.contents.create!(text:'En algunas circunstancias, es impracticable el ajuste de la información comparativa de uno o más periodos anteriores cuando se desea conseguir la comparabilidad con el periodo corriente. Por ejemplo, los datos podrían no haberse obtenido, en el periodo o periodos anteriores, de forma que permitan la aplicación retroactiva de una nueva política contable (incluyendo, para el propósito de los párrafos 51 a 53, su aplicación prospectiva a periodos anteriores), o la reexpresión retroactiva para corregir un error de un periodo anterior, como consecuencia de lo cual la reconstrucción de la información es impracticable.',number: '50', order: 68)
nic.contents.create!(text:'Con frecuencia es necesario efectuar estimaciones al aplicar una política contable a los elementos de los estados financieros reconocidos o revelados que hacen referencia a determinadas transacciones, otros sucesos y condiciones. La estimación es subjetiva en sí misma, y podría haberse realizado después del periodo sobre el que se informa. El desarrollo de estimaciones puede ser todavía más difícil cuando se aplica retroactivamente una política contable, o cuando se efectúa una reexpresión retroactiva para corregir un error de periodos anteriores, debido al dilatado periodo de tiempo que podría haber transcurrido desde que se produjo la transacción afectada u ocurrió el otro suceso o condición objeto de la reexpresión. Sin embargo, el objetivo de una estimación, que se refiere a periodos anteriores, es el mismo que para las estimaciones realizadas en el periodo corriente, esto es, una y otra han de reflejar las circunstancias existentes cuando la transacción, suceso o condición haya ocurrido.',number: '51', order: 69)
nic.contents.create!(text:'En consecuencia, la aplicación retroactiva de una nueva política contable o la corrección de un error de un periodo anterior exigen diferenciar la información que:
(a) suministra evidencia de las circunstancias existentes en la fecha o fechas en las que la transacción, otro suceso o condición hayan ocurrido, y
(b) hubiera estado disponible cuando los estados financieros de los periodos anteriores fueron formulados de otro tipo de información. Para algunos tipos de estimaciones (por ejemplo, una medición del valor razonable que utiliza datos de entrada no observables significativos), es impracticable distinguir estos tipos de información. Cuando la aplicación retroactiva o la reexpresión retroactiva exijan efectuar estimaciones significativas, para las que sea imposible distinguir aquellos dos tipos de información, resultará impracticable aplicar la nueva política contable o corregir el error del periodo previo de forma retroactiva.',number: '52', order: 70)
nic.contents.create!(text:'Cuando se esté aplicando una nueva política contable o se corrijan importes de un periodo anterior, no debe utilizarse el razonamiento en retrospectiva, ya consista en suposiciones acerca de las intenciones que hubiera tenido la gerencia en un periodo previo o en estimaciones de los importes que se hubieran reconocido, medido o revelado en tal periodo anterior. Por ejemplo, cuando una entidad corrija un error de un periodo anterior en el cálculo de sus pasivos a favor de los empleados por ausencias acumuladas en caso de enfermedad de acuerdo con la NIC 19 Beneficios a los Empleados, no considerará la información sobre una epidemia grave de gripe estacional que haya aparecido en el siguiente periodo, si este dato sólo pudo conocerse después de que los estados financieros para el periodo anterior fueran autorizados para su emisión. El hecho de frecuentemente se exija efectuar estimaciones significativas cuando se modifica la información comparativa presentada para periodos anteriores no impide ajustar o corregir razonablemente dicha información comparativa.',number: '53', order: 71)



