niifs = Niif.create([{name:'Contrato de Seguro', number: 4, text:'OBJETIVO
1 El objetivo de esta NIIF consiste en especificar la información financiera que debe
ofrecer, sobre los contratos de seguro, la entidad emisora de dichos contratos (que en esta NIIF se denomina aseguradora), hasta que el Consejo complete la segunda fase de su proyecto sobre contratos de seguro. En particular, esta NIIF requiere:
(a) Realizar un conjunto de mejoras limitadas en la contabilización de los contratos de seguro por parte de las aseguradoras.
(b) Revelar información que identifique y explique los importes de los contratos de seguro en los estados financieros de la aseguradora, y que ayude a los usuarios de dichos estados a comprender el importe, calendario e incertidumbre de los flujos de efectivo futuros procedentes de dichos contratos.
ALCANCE
2 Una entidad aplicará esta NIIF a los:
(a) Contratos de seguro (incluyendo también los contratos de reaseguro) que emita y a los contratos de reaseguro de los que sea tenedora.
(b) Instrumentos financieros que emita con un componente de participación discrecional (véase el párrafo 35). La NIIF 7 Instrumentos Financieros: Información a Revelar requiere revelar información sobre los instrumentos financieros, incluyendo los instrumentos que contengan esta característica.
3 Esta NIIF no aborda otros aspectos contables de las aseguradoras, como la contabilización de los activos financieros que sean propiedad de entidades aseguradoras y de los pasivos financieros emitidos por aseguradoras (véanse la NIC 32 Instrumentos Financieros: Presentación, la NIC 39 Instrumentos Financieros: Reconocimiento y Medición, la NIIF 7 y la NIIF 9 Instrumentos Financieros), salvo por lo establecido en las disposiciones transitorias del párrafo 45.
4 Una entidad no aplicará esta NIIF a: (a) Las garantías de productos emitidas directamente por el fabricante, el mayorista o el minorista (véase la NIC 18 Ingresos de Actividades Ordinarias y la NIC 37 Provisiones, Pasivos Contingentes y Activos Contingentes).
(b) Los activos y los pasivos de los empleadores que se deriven de los planes de beneficios definidos (véanse la NIC 19 Beneficios a los Empleados y la NIIF 2 Pagos Basados en Acciones), ni a las obligaciones de beneficios por retiro presentadas que proceden de los planes de beneficios definidos (véase la NIC 26 Contabilización e Información Financiera sobre Planes de Prestaciones por Retiro).
(c) Los derechos contractuales y las obligaciones contractuales de tipo contingente, que dependan del uso futuro, o del derecho al uso, de una partida no financiera (por ejemplo, de algunas cuotas por licencia, regalías, cuotas contingentes en arrendamientos y otras partidas similares), así como el valor residual garantizado para el arrendatario que se incluye en un contrato de arrendamiento financiero (véanse la NIC 17 Arrendamientos, NIC 18 Ingresos de Actividades Ordinarias y la NIC 38 Activos Intangibles).
(d) Los contratos de garantía financiera, a menos que el emisor haya manifestado previa y explícitamente que considera a tales contratos como de seguro y que ha utilizado la contabilidad aplicable a los contratos de seguro, en cuyo caso el emisor podrá optar entre aplicar la NIC 32, NIIF 7 y la NIIF 9 o esta NIIF a dichos contratos de garantía financiera. El emisor podrá efectuar la elección contrato por contrato, pero la elección que haga para cada contrato será irrevocable.
(e) La contraprestación contingente, a pagar o cobrar en una combinación de negocios (véase la NIIF 3 Combinaciones de Negocios).
(f) Los contratos de seguro directo que la entidad tiene (los contratos de seguro directo donde la entidad es la tenedora del seguro). No obstante, el cedente aplicará esta NIIF a los contratos de reaseguro de los que sea tenedor.
5 Para facilitar las referencias, esta NIIF denomina aseguradora a toda entidad que emita un contrato de seguro, con independencia de que dicha entidad se considere
aseguradora a efectos legales o de supervisión.
6 Un contrato de reaseguro es un tipo de contrato de seguro. De acuerdo con ello, todas las referencias que se hacen a los contratos de seguro, en esta NIIF, son aplicables también a los contratos de reaseguro.
DERIVADOS IMPLÍCITOS
7 La NIIF 9 requiere que una entidad separe algunos derivados implícitos de sus contratos anfitriones, los mida por su valor razonable, e incluya los cambios en su valor razonable en el resultado del periodo. La NIIF 9 será también aplicable a los derivados implícitos en un contrato de seguro, a menos que el derivado implícito sea en sí mismo un contrato de seguro.
8 Como excepción al requerimiento establecido en la NIIF 9, la aseguradora no precisará separar, ni medir por su valor razonable, la opción que el tenedor del seguro tenga para rescatar el contrato de seguro por una cantidad fija (o por un importe basado en una cantidad fija más una tasa de interés), incluso aunque el precio de ejercicio sea diferente del importe en libros del pasivo por contratos de seguro del contrato anfitrión. No obstante, el requerimiento de la NIIF 9 será de aplicación a una opción de venta o a una opción para rescatar en efectivo, que estén implícitas en un contrato de seguro, siempre que el valor de rescate varíe en función del cambio en una variable financiera (como un precio o índice de precios de acciones o materias primas cotizadas), o del cambio en una variable no financiera que no sea específico para una de las partes del contrato. Además, esos requerimientos también se aplicarán si la posibilidad del tenedor de ejercitar la opción de venta, o la opción para rescatar en efectivo, se activa cuando ocurre un cambio en esa variable (por ejemplo, una opción de venta que puede ejercitarse si un determinado índice bursátil alcanza un valor prefijado). 
9 El párrafo 8 será igualmente de aplicación a las opciones para rescatar un instrumento financiero que contenga un componente de participación discrecional.
DISOCIACIÓN DE LOS COMPONENTES DE DEPÓSITO
10 Algunos contratos de seguro contienen tanto un componente de seguro como un
componente de depósito. En algunos casos, la aseguradora estará obligada o tendrá la facultad de disociar estos componentes:
(a) La disociación será obligatoria si se cumplen las siguientes condiciones:
(i) La aseguradora puede medir el componente de depósito (incluyendo las opciones de rescate implícitas) de forma separada (es decir, sin considerar el componente de seguro).
(ii) Las políticas contables de la aseguradora no requieren que reconozca todos los derechos y obligaciones causados por el componente de depósito.
(b) La disociación estará permitida, pero sin ser obligatoria, si la aseguradora puede medir por separado el componente de depósito, como se indica en el apartado (a)(i) anterior, pero sus políticas contables requieren que reconozca todos los derechos y obligaciones causados por el componente de depósito, con independencia de las bases que se utilicen para medir esos derechos y obligaciones.
(c) La disociación estará prohibida si la aseguradora no puede medir por separado
el componente de depósito, como se indica en el apartado (a)(i).
11 Se inserta a continuación un ejemplo donde las políticas contables de la aseguradora no requieren que reconozca todas las obligaciones causadas por un componente de depósito. Un cedente tiene derecho a recibir de una reaseguradora compensación por pérdidas, pero el contrato le obliga a devolver la compensación en años futuros. Esta obligación es causada por un componente de depósito. Si las políticas contables del cedente le permitieran reconocer la compensación como un ingreso, sin reconocer la obligación resultante, la disociación será obligatoria.
12 Para proceder a la disociación de un contrato, la aseguradora:
(a) aplicará esta NIIF al componente de seguro.
(b) aplicará la NIIF 9 al componente de depósito.
RECONOCIMIENTO Y MEDICIÓN
Exención temporal del cumplimiento de otras NIIF
13 En los párrafos 10 a 12 de la NIC 8 Políticas Contables, Cambios en las
Estimaciones Contables y Errores se especifican los criterios que la entidad utilizará para desarrollar una política contable cuando no exista ninguna NIIF que sea específicamente aplicable a una partida. No obstante, la presente NIIF exime a la aseguradora de aplicar dichos criterios en sus políticas contables relativas a: 
(a) los contratos de seguro que emita (incluyendo tanto los costos de adquisición como los activos intangibles relacionados con ellos, tales como los que se describen en los párrafos 31 y 32); y
(b) los contratos de reaseguro de los que sea tenedora.
14 No obstante, la presente NIIF no exime a la aseguradora de cumplir con ciertas
implicaciones de los criterios establecidos en los párrafos 10 a 12 de la NIC 8. Específicamente, la aseguradora:
(a) No reconocerá como un pasivo las provisiones por reclamaciones futuras cuando estas se originen en contratos de seguro inexistentes al final del periodo sobre el que se informa (tales como las provisiones por catástrofes o de estabilización).
(b) Llevará a cabo la prueba de adecuación de los pasivos que se describe en los párrafos 15 a 19.
(c) Eliminará un pasivo por contrato de seguro (o una parte del mismo) de su estado de situación financiera cuando, y sólo cuando, se extinga—es decir, cuando la obligación especificada en el contrato sea liquidada o cancelada, o haya caducado.
(d) No compensará:
(i) activos por contratos de reaseguro con los pasivos por seguro conexos; o
(ii) gastos o ingresos de contratos de reaseguro con los ingresos o gastos, respectivamente, de los contratos de seguro conexos.
(e) Considerará si se han deteriorado sus activos por reaseguros (véase el párrafo 20).
PRUEBA DE ADECUACIÓN DE LOS PASIVOS
15 Una aseguradora evaluará, al final del periodo sobre el que se informa, la adecuación de los pasivos por seguros que haya reconocido, utilizando las estimaciones actuales de los flujos de efectivo futuros procedentes de sus contratos de seguro. Si la evaluación mostrase que el importe en libros de sus pasivos por contratos de seguro (menos los costos de adquisición diferidos y los activos intangibles conexos, tales como los que se analizan en los párrafos 31 y 32) no es adecuado, considerando los flujos de efectivo futuros estimados, el importe total de la deficiencia se reconocerá en resultados.
16 Si la aseguradora aplica una prueba de adecuación de los pasivos que cumple los requisitos mínimos especificados, esta NIIF no impone requerimientos adicionales.
Los citados requisitos mínimos serán los siguientes:
(a) La prueba considera las estimaciones actuales de todos los flujos de efectivo
contractuales, y de los flujos de efectivo conexos, tales como los costos de tramitación de las reclamaciones, así como los flujos de efectivo que procedan de las opciones y garantías implícitas.
(b) Si la prueba muestra que el pasivo es inadecuado, el importe total de la diferencia se reconocerá en el resultado del periodo.
17 Si las políticas contables seguidas por la aseguradora no requiriesen la práctica de una prueba de adecuación de los pasivos que cumpla las condiciones mínimas del párrafo 16, dicha aseguradora:
(a) Determinará el importe en libros de los pasivos por seguros1 que sean
relevantes menos el importe en libros de:
(i) Los costos de adquisición conexos que se han diferido; y
(ii) Los activos intangibles conexos, como por ejemplo los adquiridos en una combinación de negocios o una transferencia de cartera (véase los párrafos 31 y 32). No obstante, los activos por reaseguro conexos no se tomarán en consideración, puesto que la aseguradora los contabilizará por separado (véase el párrafo 20).
(b) Determinará si el importe descrito en (a) es menor que el importe en libros que se requeriría en caso de que los pasivos por contratos de seguro relevantes estuvieran dentro del alcance de la NIC 37. En caso de que así fuera, la aseguradora reconocerá la diferencia total en el resultado del periodo, y minorará el importe en libros de los costos de adquisición conexos que se han diferido o los activos intangibles conexos, o aumentará el importe en libros de los pasivos por contratos de seguro relevantes.
18 Si la prueba de adecuación de los pasivos de la aseguradora cumpliese los requisitos mínimos del párrafo 16, se aplicará con el nivel de agregación especificado en esta prueba. Si, por el contrario, la prueba de adecuación de los pasivos no cumpliese dichos requisitos mínimos, la comparación descrita en el párrafo 17 se hará considerando el nivel de agregación de una cartera de contratos que estén sujetos, genéricamente, a riesgos similares y sean gestionados conjuntamente como una cartera única.
19 El importe descrito en el apartado (b) del párrafo 17 (esto es, el resultado de aplicar la NIC 37) reflejará los márgenes de inversión futuros (véanse los párrafos 27 a 29) si, y sólo si, el importe descrito en el apartado (a) del párrafo 17 también reflejase dichos márgenes.
DETERIORO DE ACTIVOS POR CONTRATOS DE REASEGURO
20 Si se ha deteriorado un activo por contrato de reaseguro cedido, el cedente reducirá su importe en libros, y reconocerá en resultados una pérdida por deterioro. Un activo por reaseguro tiene deterioro sí, y sólo si:
(a) Existe evidencia objetiva, a consecuencia de un evento que haya ocurrido después del reconocimiento inicial del activo por reaseguro, de que el cedente puede no recibir todos los importes que se le adeuden en función de los términos del contrato; y
(b) ese evento tenga un efecto que se puede medir con fiabilidad sobre los importes que el cedente vaya a recibir de la entidad reaseguradora
1 Los pasivos por seguros que sean relevantes (considerados junto a los costos de adquisición diferidos y los activos intangibles que se relacionen con ellos) son aquéllos para los que las políticas contables de la aseguradora no requieren una prueba de adecuación de los pasivos, que cumpla los requisitos mínimos del párrafo 16.
CAMBIOS EN LAS POLÍTICAS CONTABLES
21 Los párrafos 22 a 30 se aplicarán tanto a los cambios realizados por una entidad
aseguradora que ya apliqué las NIIF, como a los que realice una aseguradora que esté adoptando por primera vez las NIIF.
22 Una entidad aseguradora puede cambiar sus políticas contables para los contratos de seguro si, y sólo si, el cambio hiciese a los estados financieros más relevantes, pero no menos fiables, para las necesidades de toma de decisiones económicas de los usuarios, o bien más fiables, pero no menos relevantes para cubrir dichas necesidades. La aseguradora juzgará la relevancia y la fiabilidad según los criterios de la NIC 8.
23 Para justificar el cambio en sus políticas contables sobre contratos de seguro, la aseguradora mostrará que el cambio acerca más sus estados financieros a los criterios de la NIC 8, si bien el cambio no precisa cumplir con todos esos criterios. Se discuten a continuación los siguientes temas específicos:
(a) tasas de interés actuales (párrafo 24);
(b) continuidad de las prácticas existentes (párrafo 25);
(c) prudencia (párrafo 26);
(d) márgenes de inversión futuros (párrafos 27 a 29); y
(e) contabilidad tácita (párrafo 30).
TASAS DE INTERÉS ACTUALES DE MERCADO
24 Se permite, pero no se requiere, que la aseguradora cambie sus políticas contables y recalcule los pasivos designados2 causados por contratos de seguro, con el fin de reflejar las tasas de interés de mercado vigentes, reconociendo en resultados los cambios en dichos pasivos. En ese momento, puede también introducir políticas contables que requieran de otras estimaciones e hipótesis actuales para los pasivos designados. La elección descrita en este párrafo permite a la aseguradora cambiar sus políticas contables, para los pasivos designados, sin tener que aplicar estas políticas de forma uniforme a todos los pasivos similares, como hubiera requerido la NIC 8. Si una aseguradora designase algunos pasivos para aplicar este tratamiento opcional, continuará aplicando las tasas de interés de mercado actuales (y, si es el caso, las otras estimaciones e hipótesis actuales) de forma uniforme a dichos pasivos en todos los periodos hasta que se extingan.
CONTINUIDAD DE LAS PRÁCTICAS EXISTENTES
25 La aseguradora puede continuar con las prácticas que se enumeran a continuación, pero introducir de nuevo de cualquiera de ellas va en contra del párrafo 22:
(a) Medir los pasivos por seguro sin proceder a descontar los importes.
(b) Medir los derechos contractuales relativos a futuras comisiones de gestión de inversiones por un importe que exceda su valor razonable, obtenido por comparación con las comisiones que actualmente cargan otros participantes en el mercado por servicios similares. Es probable que, al inicio de esos derechos contractuales, su valor razonable sea igual a los costos pagados por originarlos, salvo si las futuras comisiones por gestión de inversiones y los costos conexos no están en línea con los comparables en el mercado.
2 En este párrafo, los pasivos por contratos de seguro comprenden tanto los costos de adquisición diferidos como los activos intangibles conexos, tal como se discute en los párrafos 31 y 32.
(c) Utilizar políticas contables no uniformes para los contratos de seguro (así como para los costos de adquisición diferidos y los activos intangibles conexos) de las subsidiarias, salvo lo permitido por el párrafo 24. Si esas políticas contables no fueran uniformes, la aseguradora podrá cambiarlas, siempre que del cambio no resulten políticas contables más dispersas, y se satisfagan el resto de los requerimientos de esta NIIF.
PRUDENCIA
26 La aseguradora no necesita cambiar sus políticas contables para los contratos de seguro, con el fin de eliminar la prudencia excesiva. No obstante, si la aseguradora ya valora sus contratos de seguro con suficiente prudencia, no deberá introducir aún más prudencia.
MÁRGENES DE INVERSIÓN FUTUROS
27 La aseguradora no necesita cambiar sus políticas contables para contratos de seguro con el fin de eliminar márgenes de inversión futuros. No obstante, existe una presunción refutable de que los estados financieros de la aseguradora se volverían menos relevantes y menos fiables si se introdujese una política contable que reflejase márgenes de inversión futuros en la medición de los contratos de seguro, salvo que dichos márgenes afecten a pagos contractuales. Los dos ejemplos siguientes ilustran políticas contables que reflejan esos márgenes:
(a) utilizar un tipo de descuento que refleje el rendimiento esperado de los activos
de la aseguradora; o
(b) proyectar los rendimientos de esos activos según una tasa de rentabilidad estimada, descontando luego a un tipo diferente los rendimientos proyectados, e
incluyendo el resultado en la medición del pasivo.
28 Una aseguradora puede obviar la presunción refutable descrita en el párrafo 27 si, y sólo si, los demás componentes de un determinado cambio en las políticas contables aumentan la relevancia y fiabilidad de sus estados financieros, en una medida suficiente como para compensar las pérdidas de relevancia y fiabilidad que supone la inclusión de los márgenes de inversión futuros. Por ejemplo, puede suponerse que las políticas contables de una aseguradora para contratos de seguro comprenden un conjunto de suposiciones excesivamente prudentes establecidas desde el comienzo, un tipo de descuento prescrito por el regulador sin referencia directa a las condiciones del mercado, y no consideran algunas opciones y garantías implícitas en los contratos. La aseguradora podría elaborar unos estados financieros más relevantes y no menos fiables cambiando a una contabilidad orientada al inversor, que sea ampliamente utilizada e implique:
(a) estimaciones y suposiciones actuales;
(b) un ajuste razonable (pero no excesivamente prudente) para reflejar el riesgo y la incertidumbre;
(c) mediciones que reflejen tanto el valor intrínseco como el valor temporal de las opciones y garantías implícitas en los contratos; y
(d) un tipo de descuento de mercado actual, incluso si ese tipo de descuento refleja el rendimiento estimado de los activos de la aseguradora.
29 En algunos procedimientos de medición, se utiliza el tipo de descuento para determinar el valor presente de un margen de ganancia futuro. Este margen de ganancia se distribuye entonces entre los diferentes periodos mediante una fórmula. En los procedimientos citados, el tipo de descuento afecta sólo indirectamente a la medición del pasivo. En particular, el empleo de un tipo de descuento que sea menos apropiado tiene un efecto limitado o nulo sobre la medición del pasivo al comienzo. No obstante, en otros procedimientos, el tipo de descuento determina de forma directa la medición del pasivo. En este último caso, debido a que la introducción de un tipo de descuento basado en los activos tiene un efecto más significativo, es muy improbable que la aseguradora pueda obviar la presunción refutable del párrafo 27.
CONTABILIDAD TÁCITA
30 En algunos modelos contables, las pérdidas o ganancias realizadas de los activos de la aseguradora tienen un efecto directo en la medición de todas o algunas de las siguientes partidas: (a) sus pasivos por contratos de seguro, (b) los costos de
adquisición diferidos conexos y (c) los activos intangibles también conexos, según se describen estas partidas en los párrafos 31 y 32. Se permite, pero no se requiere, a la aseguradora, cambiar sus políticas contables de forma que la pérdida o ganancia reconocida pero no realizada, en los activos, afecte a dichas mediciones de la misma forma que la pérdida o ganancia realizada. El ajuste correspondiente en el pasivo por contratos de seguro (o en los costos de adquisición diferidos o en los activos intangibles) se reconocerá en otro resultado integral si, y sólo si, las ganancias o pérdidas no realizadas se reconocen en otro resultado integral. Esta práctica se denomina en ocasiones “contabilización tácita”.
CONTRATOS DE SEGURO ADQUIRIDOS EN UNA COMBINACIÓN DE NEGOCIOS O EN UNA TRANSFERENCIA DE CARTERA
31 Para cumplir con la NIIF 3, la aseguradora, en la fecha de adquisición, medirá por su valor razonable los pasivos derivados de contratos de seguro asumidos, así como los activos por seguro que haya adquirido en la combinación de negocios. No obstante, se permite, pero no se obliga, a la aseguradora a utilizar una presentación desagregada, que separe en dos componentes al valor razonable de los contratos de seguro adquiridos:
(a) un pasivo medido de acuerdo con las políticas contables que la aseguradora utilice para los contratos de seguro que emita; y
(b) un activo intangible, que representa la diferencia entre (i) el valor razonable de los derechos adquiridos y obligaciones asumidas por contratos de seguro y (ii) 
el importe descrito en (a). La medición posterior de este activo será uniforme con la medición del pasivo por contratos de seguro conexo.
32 La aseguradora que adquiera una cartera de contratos de seguro podrá utilizar la presentación desagregada descrita en el párrafo 31.
33 Los activos intangibles descritos en los párrafos 31 y 32 están excluidos del alcance de la NIC 36 Deterioro del Valor de los Activos y de la NIC 38. No obstante, la NIC 36 y la NIC 38 serán de aplicación a las listas de clientes y a las relaciones con los clientes que reflejen expectativas de contratos futuros, pero que no formen parte de los derechos ni de las obligaciones contractuales de seguros existentes en la fecha de la combinación de negocios o la transferencia de cartera.
COMPONENTES DE PARTICIPACIÓN DISCRECIONAL
COMPONENTES DE PARTICIPACIÓN DISCRECIONAL EN CONTRATOS DE SEGURO
34 Algunos contratos de seguro contienen un componente de participación discrecional, así como un componente garantizado. El emisor de dichos contratos:
(a) Podrá, aunque no estará obligado a, reconocer el elemento garantizado de forma separada del componente de participación discrecional. Si el emisor no los reconociera por separado, clasificará el contrato en su conjunto como un pasivo. Si el emisor los clasificase por separado, considerará el elemento garantizado como un pasivo.
(b) Clasificará, si reconociese el componente de participación discrecional por separado del elemento garantizado, al mismo como un pasivo o como un componente separado del patrimonio. En esta NIIF no se especifica cómo puede determinar el emisor si dicho componente es un pasivo o forma parte del patrimonio. El emisor podrá también desagregar este componente en partidas de pasivo y patrimonio, en cuyo caso utilizará una política contable uniforme con la desagregación efectuada. El emisor no clasificará este componente dentro de una categoría intermedia que no sea ni pasivo ni patrimonio.
(c) Podrá reconocer todas las primas recibidas como ingreso de actividades ordinarias, sin separar ninguna parte de las mismas que esté relacionada con el componente de patrimonio. Los cambios correspondientes en el elemento garantizado y en la parte del componente de participación discrecional clasificada como pasivo, se reconocerán en el resultado del periodo. Si la totalidad o una parte del componente de participación discrecional se clasificasen como patrimonio, una porción de los citados resultados puede atribuirse a dicho componente (de la misma forma que una parte puede atribuirse a las participaciones no controladoras). El emisor reconocerá la parte de resultados atribuible al componente de patrimonio de la participación discrecional, como una distribución de resultados, no como gasto o ingreso (véase la NIC 1 Presentación de Estados Financieros).
(d) Aplicará la NIIF 9, si el contrato contiene un derivado implícito que esté dentro del alcance de la NIIF 9, a ese derivado implícito.
(e) Continuará aplicando, en todos los aspectos no tratados en los párrafos 14 a 20 y en los apartados (a) hasta (d) del párrafo 34, sus políticas contables actuales respecto a dichos contratos, a menos que cambie dichas políticas contables de manera que cumpla con lo establecido en los párrafos 21 a 30.
COMPONENTES DE PARTICIPACIÓN DISCRECIONAL EN INSTRUMENTOS FINANCIEROS
35 Los requerimientos establecidos en el párrafo 34 también se aplicarán a los instrumentos financieros que contengan un componente de participación discrecional.
Además:
(a) Si el emisor clasificase la totalidad del componente de participación discrecional como un pasivo, aplicará la prueba de adecuación de los pasivos, establecida en los párrafos 15 a 19, al contrato en su conjunto (esto es, tanto al elemento garantizado como al componente de participación discrecional). El emisor no necesitará determinar el importe que resultaría de aplicar la NIIF 9 al elemento garantizado.
(b) Si el emisor clasificase la totalidad o una parte de este componente como una partida separada de patrimonio, el pasivo reconocido por el contrato en su conjunto no será menor que el importe que resultaría de aplicar la NIIF 9 al elemento garantizado. Este importe incluirá el valor intrínseco de una opción de rescate del contrato, pero no tendrá que incluir necesariamente su valor temporal si el párrafo 9 exime a la citada opción de ser medida por su valor razonable. El emisor no necesita revelar el importe que resultaría de aplicar la NIIF 9 al elemento garantizado, ni tampoco presentar este importe por separado. Además, el emisor no necesita determinar dicho importe si el pasivo total reconocido tiene un valor claramente mayor.
(c) Aunque estos contratos son instrumentos financieros, el emisor puede seguir reconociendo las primas recibidas por los mismos como ingresos de actividades ordinarias, y reconocer como gastos los incrementos correspondientes del importe en libros del pasivo.
(d) Aunque estos contratos son instrumentos financieros, el emisor que aplique el apartado (b) del párrafo 20 de la NIIF 7 a contratos con un componente de participación discrecional, revelará el importe total de los gastos por intereses reconocido en el resultado del período, pero no será necesario que lo calcule aplicando el método del interés efectivo.
INFORMACIÓN A REVELAR
EXPLICACIÓN SOBRE LOS IMPORTES RECONOCIDOS
36 Una aseguradora revelará, en sus estados financieros, información que ayude a los usuarios de la misma a identificar y explicar los importes que procedan de sus contratos de seguro.
37 A fin de cumplir con lo establecido en el párrafo 36, una aseguradora revelará la siguiente información:
(a) Sus políticas contables relativas a los contratos de seguro y a los activos, pasivos, gastos e ingresos conexos.
(b) Los activos, pasivos, ingresos y gastos reconocidos (y, en caso de que presente el estado de flujos de efectivo por el método directo, los flujos de efectivo) que procedan de contratos de seguro. Además, si la aseguradora es también cedente, revelará:
(i) las pérdidas y ganancias reconocidas en el resultado del periodo por reaseguro cedido; y
(ii) si el cedente difiriese y amortizase pérdidas y ganancias procedentes de compras de reaseguro, la amortización del periodo, así como los importes que permanezcan sin amortizar al inicio y al final del mismo.
(c) El procedimiento utilizado para determinar las suposiciones que tengan un mayor efecto sobre la medición de los importes reconocidos mencionados en el apartado (b). Cuando sea posible, la aseguradora dará también información cuantitativa respecto a dichas suposiciones.
(d) El efecto de los cambios en las suposiciones utilizadas para medir los activos y los pasivos por contratos de seguro, mostrando por separado el efecto de cada uno de los cambios que hayan tenido un efecto significativo en los estados financieros.
(e) Conciliaciones de los cambios en los pasivos y activos por contratos de reaseguro y, en los costos de adquisición conexos que se hayan diferido.
NATURALEZA Y ALCANCE DE LOS RIESGOS QUE SURJAN DE LOS CONTRATOS DE SEGURO
38 Una aseguradora revelará información que permita que los usuarios de sus estados financieros evalúen la naturaleza y el alcance de los riesgos que surjan de los contratos de seguro.
39 A fin de cumplir con lo establecido en el párrafo 38, una aseguradora revelará la siguiente información:
(a) Sus objetivos, políticas y procesos para gestionar riesgos que surjan de los
contratos de seguro, así como los métodos usados en dicha gestión de riesgos.
(b) [eliminado]
(c) Información sobre el riesgo de seguro (tanto antes como después de reducir el
mismo a través del reaseguro), incluyendo información referente a:
(i) La sensibilidad al riesgo de seguro (véase párrafo 39A).
(ii) Las concentraciones del riesgo de seguro, incluyendo una descripción de cómo son determinadas por la dirección, así como una descripción de las características compartidas que identifican cada concentración (por ejemplo, el tipo de evento asegurado, el área geográfica o la moneda)
(iii) Las reclamaciones recibidas comparadas con las estimaciones previas (esto es, la evolución de las reclamaciones). Las revelaciones sobre la evolución de las reclamaciones se referirán al intervalo de tiempo desde que surgió la primera reclamación relativamente importante para la que todavía existe incertidumbre respecto al importe y calendario de pagos pendientes, sin retrotraerse más de diez años. La aseguradora no tiene que revelar esta información para reclamaciones en que la incertidumbre sobre la suma y calendario de los pagos de las prestaciones se resuelva, normalmente, en un año.
(d) información respecto al riesgo de crédito, al riesgo de liquidez y al riesgo de mercado que sería obligatorio proporcionar, según los párrafos 31 a 42 de la NIIF 7, si los contratos de seguro estuvieran dentro del alcance de la NIIF 7.
Sin embargo:
(i) No es necesario que un asegurador facilite el análisis de vencimientos requerido en el párrafo 39(a) y (b) de la NIIF 7 si revela, en su lugar, información sobre el calendario estimado de las salidas netas de flujos de efectivo procedentes de los pasivos por seguros reconocidos. Esta información puede tomar la forma de un análisis, según el calendario estimado, de los importes reconocidos en el estado de situación financiera.
(ii) Si una aseguradora utilizase un método alternativo para gestionar la sensibilidad a las condiciones de mercado, como por ejemplo un análisis del valor implícito, podrá utilizar dicho análisis de sensibilidad para cumplir con el requerimiento del apartado (a) del párrafo 40 de la NIIF 7.
Esta aseguradora revelará también la información requerida por el párrafo 41 de la NIIF 7.
(e) Información acerca de la exposición al riesgo de mercado procedente de derivados implícitos en un contrato de seguro que sea su contrato anfitrión, cuando la aseguradora no esté obligada a medir por su valor razonable los derivados implícitos, ni tampoco haya optado por hacerlo.
39A Para cumplir con lo dispuesto en el párrafo 39(c)(i), una aseguradora podrá optar por revelar el contenido de los apartados (a) o (b) mediante:
(a) Un análisis de sensibilidad que muestre cómo podría haberse visto afectado el resultado del periodo y el patrimonio debido a variaciones de la variable pertinente de riesgo, cuya ocurrencia fuera razonablemente posible al final del periodo sobre el que se informa; los métodos e hipótesis utilizados al elaborar el análisis de sensibilidad; así como cualquier variación en estos métodos e hipótesis desde el ejercicio anterior. No obstante, si una aseguradora utilizará un método alternativo para gestionar la sensibilidad a las condiciones de mercado, como el análisis del valor implícito, podría cumplir este requisito revelando los detalles de este análisis de sensibilidad alternativo, así como la información requerida por el párrafo 41 de la NIIF 7.
(b) Información cualitativa acerca de la sensibilidad, e información sobre los plazos y condiciones de los contratos de seguro que tengan un efecto significativo sobre el importe, calendario e incertidumbre de los flujos de efectivo de la aseguradora.
'}])