niifs = Niif.create([[name:'Combinación de Negocios', number: 3 , text:'OBJETIVO
1 El objetivo de esta NIIF es mejorar la relevancia, la fiabilidad y la comparabilidad de la información sobre combinaciones de negocios y sus efectos, que una entidad que informa proporciona a través de su estado financiero.
Para lograrlo, esta NIIF establece principios y requerimientos sobre la forma en que la entidad adquirente:
(a) reconocerá y medirá en sus estados financieros los activos identificables adquiridos, los pasivos asumidos y cualquier participación no controladora en la entidad adquirida;
(b) reconocerá y medirá la plusvalía adquirida en la combinación de negocios o una ganancia procedente de una compra en condiciones muy ventajosas; y
(c) determinará qué información revelará para permitir que los usuarios de los estados financieros evalúen la naturaleza y los efectos financieros de la combinación de negocios.
ALCANCE
2 Esta NIIF se aplicará a una transacción u otro suceso que cumpla la definición de una combinación de negocios. Esta NIIF no se aplicará a:
(a) la contabilización de la formación de un acuerdo conjunto en los estados financieros del acuerdo conjunto mismo.
(b) la adquisición de un activo o de un grupo de activos que no constituya un negocio. En estos casos, la entidad adquirente identificará y reconocerá los activos identificables individuales que se adquirieron (incluyendo los que cumplan con la definición y los criterios de reconocimiento de los activos intangibles incluidos en la NIC 38 Activos Intangibles) y los pasivos asumidos. El costo del grupo deberá distribuirse entre los activos individualmente identificables y los pasivos sobre la base de sus valores razonables relativos en la fecha de la compra. Esta transacción o suceso no dará lugar a plusvalía.
(c) una combinación de entidades o negocios bajo control común (los párrafos B1 a B4 proporcionan las guías de aplicación al respecto).
2ª Los requerimientos de esta Norma no se aplicarán a la adquisición por una entidad de inversión, tal como se define en la NIIF 10 Estados Financieros Consolidados, de una inversión en una subsidiaria que se requiere medir al valor razonable con cambios en resultados.
IDENTIFICACIÓN DE UNA COMBINACIÓN DE NEGOCIOS
3 Una entidad determinará si una transacción u otro suceso es una combinación de negocios mediante la aplicación de la definición de esta NIIF, que requiere que los activos adquiridos y los pasivos asumidos constituyan un negocio. Cuando los activos adquiridos no sean un negocio, la entidad que informa contabilizará la transacción o el otro suceso como la adquisición de un activo. Los párrafos B5 a B12D proporcionan guías sobre la identificación de una combinación de negocios y la definición de un negocio.
EL MÉTODO DE LA ADQUISICIÓN
4 Una entidad contabilizará cada combinación de negocios mediante la aplicación del método de la adquisición.
5 La aplicación del método de la adquisición requiere:
(a) identificación de la adquirente;
(b) determinación de la fecha de adquisición;
(c) reconocimiento y medición de los activos identificables adquiridos, de
los pasivos asumidos y cualquier participación no controladora en la adquirida; y
(d) reconocimiento y medición de la plusvalía o ganancia por compra en términos muy ventajosos.
IDENTIFICACIÓN DE LA ADQUIRENTE
6 En cada combinación de negocios, una de las entidades que se combinan deberá identificarse como la adquirente.
7 Para identificar la adquirente —la entidad que obtiene el control de otra entidad, es decir, la adquirida— deberán utilizarse las guías de la NIIF 10. Si ha ocurrido una combinación de negocios, pero la aplicación de las guías de la NIIF 10 no indica claramente cuál de las entidades que se combinan es la adquirente, para llevar a cabo esa determinación deberán considerarse los factores incluidos en los párrafos B14 a B18.
DETERMINACIÓN DE LA FECHA DE ADQUISICIÓN
8 La adquirente identificará la fecha de adquisición, que es aquélla en la que se obtiene el control de la adquirida.
9 La fecha en la cual la adquirente obtiene el control de la adquirida es generalmente aquélla en la que la adquirente transfiere legalmente la contraprestación, adquiere los activos y asume los pasivos de la adquirida—la fecha de cierre. Sin embargo, la adquirente puede obtener el control en una fecha anterior o posterior a la fecha de cierre. Por ejemplo, la fecha de adquisición precederá a la fecha de cierre si un acuerdo escrito prevé que la adquirente obtenga el control de la adquirida en una fecha anterior a la fecha de cierre. Una adquirente considerará todos los hechos y circunstancias pertinentes.
RECONOCIMIENTO Y MEDICIÓN DE LOS ACTIVOS IDENTIFICABLES ADQUIRIDOS, LAS OBLIGACIONES ASUMIDAS Y CUALQUIER PARTICIPACIÓN NO CONTROLADORA EN LA ENTIDAD ADQUIRIDA
PRINCIPIO DE RECONOCIMIENTO
10 A la fecha de adquisición, la adquirente reconocerá, por separado de la plusvalía, los activos identificables adquiridos, los pasivos asumidos y cualquier participación no controladora en la adquirida. El reconocimiento de los activos identificables adquiridos y de los pasivos asumidos estará sujeto a las condiciones especificadas en los párrafos 11 y 12.
CONDICIONES DE RECONOCIMIENTO
11 Para cumplir las condiciones de reconocimiento como parte de la aplicación del método de la adquisición, los activos identificables adquiridos y los pasivos asumidos deben satisfacer, a la fecha de la adquisición, las definiciones de activos y pasivos del Marco Conceptual para la Preparación y Presentación de los Estados Financieros1 en la fecha de adquisición. Por ejemplo, a la fecha de la adquisición no son pasivos los costos en que la adquirente espera incurrir en el futuro, pero no está obligada a tener, para efectuar su plan de abandonar una actividad de una adquirida o para terminar el empleo de empleados de la adquirida o para reubicarlos. Por ello, la adquirente no reconocerá esos costos como parte de la aplicación del método de la adquisición. En su lugar, la adquirente reconocerá esos costos en sus estados financieros posteriores a la combinación de acuerdo con otras NIIF.
12 Además, para cumplir las condiciones para el reconocimiento como parte de la aplicación del método de la adquisición, los activos identificables adquiridos y los pasivos asumidos deben ser parte de lo que la adquirente y la adquirida (o sus anteriores propietarios) intercambiaron en la transacción de la combinación de negocios y no el resultado de transacciones separadas. La adquirente aplicará las guías de los párrafos 51 a 53 para determinar qué activos adquiridos o pasivos asumidos son parte del intercambio por la adquirida y cuáles, si los hubiera, son el resultado de transacciones separadas a ser contabilizadas de acuerdo con su naturaleza y las NIIF aplicables.
13 La aplicación por parte de la adquirente del principio y de las condiciones de reconocimiento puede dar lugar a la contabilización de algunos activos y pasivos que la adquirida no haya reconocido previamente como tales en sus estados financieros. Por ejemplo, la adquirente reconocerá los activos intangibles identificables adquiridos, tales como un nombre comercial, una patente o una relación con un cliente, que la adquirida no reconoció como activos en sus estados financieros porque los desarrolló internamente y cargó los costos relacionados como gastos.
1 Esta Norma requiere que las adquirentes apliquen las definiciones de un activo y un pasivo y las guías de apoyo del Marco Conceptual para la Preparación y Presentación de los Estados Financieros del IASC adoptado por el IASB en 2001 en lugar del Marco Conceptual para la Información Financiera emitido en 2018. [Editor’s note: Un extracto del Marco Conceptual para la Preparación y Presentación de los Estados Financieros del IASC, adoptado por el Consejo en 2001, está disponible en la página dedicada a la NIIF 3 en la sección “Supporting Implementation” de la página web de la Fundación, bajo la sección “Supporting Implementation by IFRS Standard”.]
14 Los párrafos B31 a B40 proporcionan guías sobre el reconocimiento de activos intangibles. Los párrafos 22 a 28B especifican los tipos de activos identificables y de pasivos que incluyen partidas para las que esta NIIF proporciona excepciones limitadas del principio y condiciones de reconocimiento.
Clasificación y designación de activos identificables adquiridos y pasivos asumidos en una combinación de negocios
15 A la fecha de la adquisición, la adquirente clasificará o designará los activos identificables adquiridos y los pasivos asumidos según sea necesario para la aplicación posterior de otras NIIF. La adquirente efectuará esas clasificaciones o designaciones sobre la base de los acuerdos contractuales, de las condiciones económicas, de sus políticas contables o de operación y de otras condiciones pertinentes tal como existan en la fecha de la adquisición.
16 En algunas situaciones, las NIIF proporcionarán diferentes formas de contabilización dependiendo de la forma en que una entidad clasifique o designe un activo o pasivo concreto. Ejemplos de clasificaciones o designaciones que la adquirente hará sobre la base de las correspondientes condiciones tal como existían en la fecha de la adquisición incluyen, pero no se limitan, a:
(a) la clasificación de activos y pasivos financieros concretos como medidos a valor razonable con cambios en resultados o a costo amortizado, o como un activo financiero medido a valor razonable con cambios en otro resultado integral de acuerdo con la NIIF 9 Instrumentos Financieros;
(b) la designación de un instrumento derivado como un instrumento de cobertura de acuerdo con la NIIF 9; y
(c) la evaluación de si un derivado implícito debe separarse del contrato anfitrión de acuerdo con la NIIF 9 (que es una cuestión de “clasificación”, según el uso dado por esta NIIF a ese término).
17 Esta NIIF estipula una excepción al principio incluido en el párrafo 15:
(a) la clasificación de un contrato de arrendamiento en el que la adquirida es un arrendador como un arrendamiento operativo o un arrendamiento financiero de acuerdo con la NIIF 16 Arrendamientos.
(b) [eliminado]
La adquirente clasificará esos contratos sobre la base de las condiciones contractuales y de otros factores al comienzo del contrato (o, si las condiciones del contrato han sido modificadas de una manera que cambiaría su clasificación, a la fecha de esa modificación, que puede ser la de adquisición).
PRINCIPIO DE MEDICIÓN
18 La adquirente medirá los activos identificables adquiridos y los pasivos asumidos a sus valores razonables en la fecha de su adquisición.
19 Para cada combinación de negocios, la adquirente medirá en la fecha de adquisición los componentes de las participaciones no controladoras en la adquirida que son participaciones en la propiedad actuales y que otorgan a sus tenedores el derecho a una participación proporcional en los activos netos de la entidad en el caso de liquidación:
(a) valor razonable; o
(b) a la participación proporcional de los instrumentos de propiedad actuales en los importes reconocidos de los activos netos identificables de la adquirida.
Todos los demás componentes de las participaciones no controladoras se medirán al valor razonable en sus fechas de adquisición, a menos que se requiera otra base de medición por las NIIF.
20 Los párrafos 24 a 31A especifican los tipos de activos y pasivos identificables que incluyen partidas para las que esta NIIF proporciona excepciones limitadas del principio de medición.
EXCEPCIONES A LOS PRINCIPIOS DE RECONOCIMIENTO O MEDICIÓN
21 Esta NIIF proporciona excepciones limitadas a sus principios de reconocimiento y medición. Los párrafos 22 a 31A especifican tanto las partidas concretas para las que se establecen excepciones como la naturaleza de éstas. La adquirente contabilizará esas partidas aplicando los requerimientos de los párrafos 22 a 31A, lo que hará que algunas partidas sean:
(a) contabilizadas ya sea aplicando condiciones de reconocimiento adicionales a las de los párrafos 11 y 12 o aplicando los requerimientos de otras NIIF, lo que dará resultados diferentes a los obtenidos mediante la aplicación de las condiciones y del principio de reconocimiento.
(b) medidas por importes distintos de sus valores razonables a la fecha de adquisición.
Excepción al principio de reconocimiento
PASIVOS CONTINGENTES
22 La NIC 37 Provisiones, Pasivos Contingentes y Activos Contingentes define un pasivo contingente como:
(a) una obligación posible, surgida a raíz de sucesos pasados y cuya existencia ha de ser confirmada sólo por la ocurrencia o la falta de ocurrencia de uno o más hechos futuros sucesos inciertos que no están enteramente bajo el control de la entidad; o
(b) una obligación presente, surgida a raíz de sucesos pasados, que no se ha reconocido contablemente porque:
(i) no es probable que para satisfacerla se vaya a requerir una salida de recursos que incorporen beneficios económicos; o
(ii) el importe de la obligación no pueda ser medido con la suficiente fiabilidad.
23 El requerimiento de la NIC 37 no se aplicará para determinar qué pasivos contingentes se han de reconocer en la fecha de la adquisición. En su lugar la adquirente reconocerá en la fecha de la adquisición un pasivo contingente asumido en una combinación de negocios si es una obligación presente que surja de sucesos pasados y su valor razonable pueda medirse con fiabilidad.
Por ello, en contra de la NIC 37, la adquirente reconocerá un pasivo contingente asumido en una combinación de negocios en la fecha de la adquisición, incluso cuando no sea probable que para cancelar la obligación vaya a requerirse una salida de recursos que incorporen beneficios económicos. El párrafo 56 proporciona guías sobre la contabilización posterior de pasivos contingentes.
Excepciones a ambos principios de reconocimiento y medición
IMPUESTO A LAS GANANCIAS
24 La adquirente reconocerá y medirá un activo o un pasivo por impuestos diferidos que surjan de los activos adquiridos y de los pasivos asumidos en una combinación de negocios de acuerdo con la NIC 12 Impuesto a las Ganancias.
25 La adquirente contabilizará los efectos fiscales potenciales de las diferencias temporarias y de las compensaciones tributarias de una adquirida que existan en la fecha de la adquisición y que surjan como resultado de ésta de acuerdo con la NIC 12.
BENEFICIOS A LOS EMPLEADOS
26 La adquirente reconocerá y medirá un pasivo (o un activo, si lo hubiera) relacionado con acuerdos de beneficios a los empleados de la adquirida de acuerdo con la NIC 19 Beneficios a los Empleados.
ACTIVOS DE INDEMNIZACIÓN
27 En una combinación de negocios, el vendedor puede indemnizar contractualmente a la adquirente por el resultado de una contingencia o de una incertidumbre relacionada con el total o con parte de un determinado activo o pasivo. Por ejemplo, el vendedor puede indemnizar a la adquirente por pérdidas por encima de un determinado importe de un pasivo que surja de una contingencia en particular; en otras palabras, el vendedor garantizará que el pasivo de la adquirente no excederá un determinado importe. Como resultado, la adquirente obtendrá un activo de indemnización. La adquirente reconocerá un activo de indemnización al mismo tiempo que reconozca la partida de indemnización y lo medirá sobre la misma base que ésta, sujeto a la necesidad de establecer una corrección de valor por importes incobrables. Por ello, si la indemnización está relacionada con un activo o pasivo que se reconoce a la fecha de la adquisición y se mide por su valor razonable a esa fecha, la adquirente reconocerá el activo de indemnización a la fecha de la adquisición, medido a su valor razonable de su fecha de adquisición. En un activo de indemnización medido a valor razonable, los efectos de la incertidumbre respecto a los flujos de efectivo futuros debidos a consideraciones de cobrabilidad están incluidos en la medida del valor razonable y no es necesaria una corrección de valor por separado (el párrafo B41 proporciona guías de aplicación relacionadas).
28 En algunas circunstancias, la indemnización puede estar relacionada con un activo o con un pasivo que es una excepción a los principios de reconocimiento o medición. Por ejemplo, una indemnización puede estar relacionada con un pasivo contingente que no se reconoce a la fecha de la adquisición porque su valor razonable a esa fecha no puede medirse con fiabilidad. De forma alternativa, una indemnización puede estar relacionada con un activo o un pasivo (por ejemplo, uno que proceda de un beneficio a empleados) que se mida sobre una base distinta al valor razonable en la fecha de la adquisición.
En estas circunstancias, el activo de indemnización deberá reconocerse y medirse utilizando supuestos coherentes con los que se utilicen para medir la partida indemnizada, sujeto a la evaluación por la administración de la cobrabilidad del activo de indemnización y de cualquier limitación contractual sobre el importe indemnizado. El párrafo 57 proporciona guías sobre la contabilización posterior de un activo de indemnización.
ARRENDAMIENTOS EN EL QUE LA ADQUIRIDA ES EL ARRENDATARIO
28ª La adquirente reconocerá el activo por derecho de uso y los pasivos por arrendamiento para los arrendamientos identificados de acuerdo con la NIIF 16 en los que la adquirida es el arrendatario. No se requiere que la adquirente reconozca los activos por derecho de uso y los pasivos por arrendamiento para:
(a) arrendamientos para los que el plazo del arrendamiento (como se define en la NIIF 16termine dentro de 12 meses a partir de la fecha de adquisición; o
(b) arrendamientos cuyo activo subyacente es de bajo valor (como se describe en los párrafos B3 a B8 de la NIIF 16).
28b La adquirente medirá el pasivo por arrendamiento al valor presente de los pagos por arrendamiento restantes (como se define en la NIIF 16) como si el arrendamiento adquirido fuera un nuevo arrendamiento en la fecha de adquisición. La adquirente medirá el activo por derecho de uso al mismo importe que el pasivo por arrendamiento, ajustado para reflejar los términos favorables o desfavorables del arrendamiento en comparación con los términos del mercado.
Excepciones al principio de medición
DERECHOS READQUIRIDOS
29 La adquirente medirá el valor de un derecho readquirido reconocido como un activo intangible basándose en el término contractual restante del contrato relacionado, independientemente de si los participantes del mercado considerarían renovaciones contractuales potenciales para medir el valor razonable. Los párrafos B35 y B36 proporcionan guías de aplicación al respecto.
TRANSACCIONES CON PAGOS BASADOS EN ACCIONES
30 La adquirente medirá un pasivo o un instrumento de patrimonio relacionado con transacciones con pagos basados en acciones de la adquirida o la sustitución de las transacciones con pagos basados en acciones de la adquirida por transacciones con pagos basados en acciones de la adquirente de acuerdo con el método establecido en la NIIF 2 Pagos Basados en Acciones en la fecha de adquisición. (Esta NIIF se refiere al resultado de ese método como la “medida basada en el mercado” de la transacción con pagos basados en acciones).
ACTIVOS MANTENIDOS PARA LA VENTA
31 La adquirente medirá un activo no corriente adquirido (o un grupo de activos para su disposición) que se clasifique como mantenido para la venta a la fecha de la adquisición de acuerdo con la NIIF 5 Activos no Corrientes Mantenidos para la Venta y Operaciones Discontinuadas, al valor razonable menos los costos de venderlo de acuerdo con los párrafos 15 a 18 de dicha NIIF.
CONTRATOS DE SEGURO
31ª La adquirente medirá un grupo de contratos dentro del alcance de la NIIF 17
Contratos de Seguro adquirido en una combinación de negocios como un pasivo o activo de acuerdo con los párrafos 39 y B93 a B95 de la NIIF 17, en la fecha de la adquisición.
RECONOCIMIENTO Y MEDICIÓN DE LA PLUSVALÍA O UNA GANANCIA POR UNA COMPRA EN TÉRMINOS MUY VENTAJOSOS
32 La adquirente reconocerá una plusvalía en la fecha de la adquisición medida como el exceso del apartado (a) sobre el (b) siguientes:
(a) Suma de:
(i) la contraprestación transferida medida de acuerdo con esta NIIF, que, generalmente, requiere que sea el valor razonable en la fecha de la adquisición (véase el párrafo 37);
(ii) el importe de cualquier participación no controladora en la adquirida medida de acuerdo con esta NIIF; y
(iii) en una combinación de negocios llevada a cabo por etapas (véanse los párrafos 41 y 42), el valor razonable en la fecha de adquisición de la participación anteriormente tenida por el adquirente en el patrimonio de la adquirida.
(b) el neto de los importes en la fecha de la adquisición de los activos identificables adquiridos y de los pasivos asumidos, medidos de acuerdo con esta NIIF.
33 En una combinación de negocios en la que la adquirente y la adquirida (o sus propietarios anteriores) intercambian solo instrumentos de patrimonio, el valor razonable en la fecha de adquisición de los instrumentos de patrimonio de la adquirida podría medirse con mayor fiabilidad que el valor razonable en la fecha de adquisición de las participaciones en el patrimonio de la adquirente. Si es así, la adquirente determinará el importe de la plusvalía utilizando el valor razonable en la fecha de adquisición de los instrumentos de patrimonio de la adquirida en lugar del valor razonable en la fecha de adquisición de las participaciones en el patrimonio transferidas. Para determinar el importe de la plusvalía en una combinación de negocios en la que no se transfiere una contraprestación, la adquirente utilizará el valor razonable de su participación en la adquirida en la fecha de adquisición en lugar del valor razonable en la fecha de adquisición de la contraprestación transferida [párrafo 32(a)(i)]. Los párrafos B46 a B49 proporcionan guías de aplicación relacionadas.
COMPRAS EN TÉRMINOS MUY VENTAJOSOS
34 Ocasionalmente, una adquirente realizará una compra en condiciones muy ventajosas, lo que es una combinación de negocios en la que el importe del párrafo 32(b) excede la suma de los importes especificados en el párrafo 32(a). Si ese exceso se mantiene después de aplicar los requerimientos del párrafo 36, la adquirente reconocerá la ganancia resultante en resultados a la fecha de adquisición. La ganancia se atribuirá a la adquirente.
35 Una compra en condiciones muy ventajosas puede suceder, por ejemplo, en una combinación de negocios que es una venta forzada en la que el vendedor actúa bajo coacción. Sin embargo, las excepciones sobre el reconocimiento o la medición de partidas concretas tratadas en los párrafos 22 a 31A pueden también resultar en el reconocimiento de una ganancia (o cambiar el importe de una ganancia reconocida) por una compra en condiciones muy ventajosas.
36 Antes de reconocer una ganancia por una compra en condiciones muy ventajosas, la adquirente reevaluará si ha identificado correctamente todos los activos adquiridos y todos los pasivos asumidos y reconocerá cualesquiera activos adicionales que sean identificados en esta revisión. La adquirente revisará entonces los procedimientos utilizados para medir los importes cuyo reconocimiento a la fecha de adquisición para todas las partidas siguientes:
(a) los activos identificables adquiridos y los pasivos asumidos;
(b) la participación no controladora en la adquirida, si la hubiera;
(c) para una combinación de negocios realizada por etapas, la participación en el patrimonio de la adquirida previamente poseída por la adquirente; y
(d) la contraprestación transferida.
El objetivo de la revisión es asegurar que las mediciones reflejan adecuadamente la consideración de toda la información disponible en la fecha de la adquisición.
CONTRAPRESTACIÓN TRANSFERIDA
37 La contraprestación transferida en una combinación de negocios deberá medirse a su valor razonable, que deberá calcularse como la suma de los valores razonables en la fecha de adquisición de los activos transferidos por la adquirente, de los pasivos incurridos por ella con los anteriores propietarios de la adquirida y de las participaciones en el patrimonio emitidas por la adquirente. (Sin embargo, toda porción de incentivos con pagos basados en acciones de la adquirente, intercambiada por incentivos mantenidos por los empleados de la adquirida, que esté incluida en la contraprestación transferida en la combinación de negocios deberá medirse de acuerdo con el párrafo 30 y no por el valor razonable.) Son ejemplos de formas potenciales de contraprestación el efectivo, otros activos, un negocio o una subsidiaria de la adquirente, contraprestaciones contingentes, instrumentos de patrimonio ordinarios o preferentes, opciones, certificados de opción para suscribir títulos (warrants) y participaciones de miembros de entidades mutualistas.
38 La contraprestación transferida puede incluir activos o pasivos de la adquirente que tengan un importe en libros que difiera de sus valores razonables en la fecha de adquisición (por ejemplo, activos no monetarios o negocios de la adquirente). Si así fuera, la adquirente medirá nuevamente los activos transferidos o pasivos a sus valores razonables en la fecha de la adquisición y reconocerá las ganancias o pérdidas resultantes, si las hubiera, en resultados. Sin embargo, algunas veces los activos o pasivos transferidos permanecen en la entidad combinada tras la combinación de negocios (por ejemplo, porque los activos o pasivos se transfirieron a la adquirida y no a sus anteriores propietarios), y la adquirente, por ello, retiene el control sobre ellos.
En esa situación, la adquirente medirá esos activos y pasivos por sus importes en libros inmediatamente antes de la fecha de adquisición y no reconocerá una ganancia o pérdida en resultados sobre activos o pasivos que controla tanto antes como después de la combinación de negocios.
Contraprestación contingente
39 La contraprestación que la adquirente transfiere a cambio de la adquirida incluye cualquier activo o pasivo que proceda de un acuerdo de contraprestación contingente (véase el párrafo 37). La adquirente reconocerá a la fecha de adquisición el valor razonable de la contraprestación contingente como parte de la contraprestación transferida a cambio de la adquirida.
40 La adquirente clasificará una obligación de pagar una contraprestación contingente que cumple la definición de un instrumento financiero como pasivo financiero o como patrimonio basándose en las definiciones de instrumentos de patrimonio y de pasivo financiero incluidas en el párrafo 11 de la NIC 32 Instrumentos Financieros: Presentación. La adquirente clasificará como un activo un derecho a la devolución de contraprestaciones previamente transferidas si se cumplen determinadas condiciones.
El párrafo 58 proporciona guías sobre la contabilización posterior de contraprestaciones contingentes.
GUÍAS ADICIONALES PARA LA APLICACIÓN DEL MÉTODO DE LA ADQUISICIÓN A TIPOS PARTICULARES DE COMBINACIONES DE NEGOCIOS
Una combinación de negocios realizada por etapas
41 Algunas veces, una adquirente obtiene el control de una adquirida en la que tenía una participación en el patrimonio inmediatamente antes de la fecha de la adquisición. Por ejemplo, a 31 de diciembre de 20X1, la Entidad A posee un 35 por ciento de participación no controladora en la Entidad B. En esa fecha, la Entidad A compra una participación adicional del 40 por ciento en la Entidad B, lo que le da el control sobre esta entidad. Esta NIIF denomina esta transacción como una combinación de negocios realizada por etapas, a la que también se refiere algunas veces como adquisición por pasos.
42 En una combinación de negocios realizada por etapas, la adquirente medirá nuevamente su participación previamente tenida en el patrimonio de la adquirida por su valor razonable en la fecha de adquisición y reconocerá la ganancia o pérdida resultante, si la hubiera, en el resultado del periodo o en otro resultado integral, según proceda. En periodos anteriores sobre los que se informa, la adquirente pudo haber reconocido en otro resultado integral los cambios en el valor de su participación en el patrimonio de la adquirida. Si así fuera, el importe que fue reconocido en otro resultado integral deberá reconocerse sobre la misma base que se requeriría si la adquirente hubiera dispuesto directamente de la anterior participación mantenida en el patrimonio.
42ª Cuando una parte de un acuerdo conjunto (tal como se define en la NIIF 11
Acuerdos Conjuntos) obtiene el control de un negocio que es una operación conjunta (tal como se define en la NIIF 11), y tenía derechos a los activos y obligaciones por los pasivos relacionados con esa operación conjunta inmediatamente antes de la fecha de adquisición, la transacción es una combinación de negocios realizada por etapas. Por ello, la adquirente aplicará los requerimientos relativos a una combinación de negocios realizada por etapas, incluyendo la nueva medición de la participación anteriormente mantenida en la operación conjunta en la forma descrita en el párrafo 42. Al hacerlo así, la adquirente medirá nuevamente la totalidad de su participación anteriormente mantenida en la operación conjunta.
UNA COMBINACIÓN DE NEGOCIOS REALIZADA SIN LA TRANSFERENCIA DE LA CONTRAPRESTACIÓN
43 Algunas veces, una adquirente obtiene el control de una adquirida sin la transferencia de una contraprestación. Para contabilizar estas combinaciones de negocios se aplica el método de la adquisición. Estas circunstancias incluyen:
(a) La adquirida recompra un número suficiente de sus propias acciones de modo que una inversora existente (la adquirente) obtiene el control.
(b) La caducidad de derechos de veto minoritarios que anteriormente impedían a la adquirente controlar una adquirida en la que la primera tenía la mayoría de los derechos de voto.
(c) La adquirente y la adquirida acuerdan combinar sus negocios solo mediante un contrato. La adquirente no transfiere ninguna contraprestación a cambio del control de una adquirida y no mantiene participaciones en el patrimonio en la adquirida, ni en la fecha de adquisición ni con anterioridad. Ejemplos de combinaciones de negocios realizadas solo mediante un contrato incluyen la unión de dos negocios en un acuerdo de cotización en conjunto o la formación de una sociedad anónima con doble cotización en bolsa.
44 En una combinación de negocios realizada solo mediante un contrato, la adquirente atribuirá a los propietarios de la adquirida el importe de los activos netos de ésta última reconocido de acuerdo con esta NIIF. En otras palabras, las participaciones en el patrimonio de la adquirida tenidas por otras partes distintas de la adquirente son una participación no controladora en los estados financieros de la adquirente posteriores a la adquisición, incluso si el resultado es que todas las participaciones en el patrimonio de la adquirida se atribuyen a participaciones no controladoras.
PERIODO DE MEDICIÓN
45 Si la contabilización inicial de una combinación de negocios está incompleta al final del periodo contable en el que la combinación ocurre, la adquirente informará en sus estados financieros de los importes provisionales de las partidas cuya contabilización está incompleta. Durante el periodo de medición, la adquirente ajustará retroactivamente los importes provisionales reconocidos a la fecha de la adquisición para reflejar la nueva información obtenida sobre hechos y circunstancias que existan en la fecha de la adquisición y que, si hubieran sido conocidas, habrían afectado a la medición de los importes reconocidos en esa fecha.
Durante el periodo de medición la adquirente también reconocerá activos o pasivos adicionales si obtiene nueva información sobre hechos y circunstancias que existían en la fecha de la adquisición y que, si hubieran sido conocidos, habrían resultado en el reconocimiento de esos activos y pasivos a esa fecha. El periodo de medición terminará tan pronto como la adquirente reciba la información que estuviera buscando sobre hechos y circunstancias que existían en la fecha de la adquisición o concluya que no se puede obtener más información. Sin embargo, el periodo de medición no excederá de un año a partir de la fecha de adquisición.
46 El periodo de medición es aquél tras la fecha de adquisición durante el cual la adquirente puede ajustar los importes provisionales reconocidos en una combinación de negocios. El periodo de medición proporciona a la adquirente un plazo razonable para obtener la información necesaria para identificar y medir, en la fecha de la adquisición y con los requerimientos de esta NIIF:
(a) los activos identificables adquiridos, los pasivos asumidos y cualquier participación no controladora en la adquirida;
(b) la contraprestación transferida a la adquirida (o el otro importe utilizado para medir la plusvalía);
(c) en una combinación de negocios realizada en etapas, la participación en el patrimonio de la adquirida anteriormente tenida por la adquirente; y
(d) la plusvalía resultante o la ganancia por una compra realizada en condiciones muy ventajosas.
47 La adquirente considerará todos los factores pertinentes para determinar si la información obtenida tras la fecha de la adquisición debería resultar en un ajuste en los importes provisionales reconocidos o si esa información procede de sucesos ocurridos después de la fecha de la adquisición. Los factores pertinentes incluyen la fecha en que se obtuvo la información adicional y si la adquirente puede identificar una razón para un cambio en los importes provisionales. La información que se obtiene poco después de la fecha de la adquisición tiene mayor probabilidad de reflejar circunstancias existentes en la fecha de la adquisición que la obtenida varios meses después. Por ejemplo, es probable que la venta de un activo a un tercero poco después de la fecha de la adquisición por un importe que difiere significativamente de su valor razonable provisional medido para esa fecha indique un error en el importe provisional, a menos que pueda identificarse un suceso entre un momento y el otro que haya cambiado su valor razonable.
48 La adquirente reconocerá un incremento (disminución) en el importe provisional reconocido para un activo identificable (pasivo) por medio de una disminución (incremento) en la plusvalía. Sin embargo, la nueva información obtenida durante el periodo de medición puede dar lugar, algunas veces, a un ajuste del importe provisional de más de un activo o pasivo. Por ejemplo, la adquirente puede haber asumido un pasivo para pagar daños relacionados con un accidente en una de las instalaciones de la adquirida, total o parcialmente cubierta por la póliza de seguros de responsabilidad de la adquirida. Si la adquirente obtiene nueva información durante el periodo de medición sobre el valor razonable en la fecha de adquisición de ese pasivo, el ajuste de la plusvalía que proceda de un cambio en el importe provisional reconocido para el pasivo sería compensado (en todo o en parte) por el ajuste que corresponda de la plusvalía que proceda de un cambio en el importe provisional reconocido por el derecho por cobrar de la aseguradora por la reclamación.
49 Durante el periodo de medición, la adquirente reconocerá ajustes del importe provisional como si la contabilización de la combinación de negocios hubiera sido completada en la fecha de la adquisición. Así, la adquirente revisará en la medida en que sea necesario, la información comparativa presentada en los estados financieros de periodos anteriores, lo que incluye la realización de cambios en la depreciación, amortización u otros con efectos sobre el resultado reconocidos para completar la contabilización inicial.
50 Tras el periodo de medición, la adquirente sólo revisará la contabilidad de una combinación de negocios para corregir un error de acuerdo con la NIC 8 Políticas Contables, Cambios en las Estimaciones Contables y Errores.
DETERMINACIÓN DE LO QUE ES PARTE DE LA TRANSACCIÓN DE COMBINACIÓN DE NEGOCIOS
51 La adquirente y la adquirida pueden tener una relación preexistente u otro acuerdo antes de las negociaciones para el comienzo de la combinación de negocios, o pueden llevar a cabo un acuerdo durante las negociaciones que esté separado de la combinación de negocios. En cualquiera de las dos situaciones, la adquirente identificará todos los importes que no formen parte de lo que la adquirente y la adquirida (o sus anteriores propietarios) intercambian en la combinación de negocios, es decir, importes que no son parte del intercambio por la adquirida. La adquirente sólo reconocerá como parte de la aplicación del método de la adquisición la contraprestación transferida por la adquirida y los activos adquiridos y pasivos asumidos en el intercambio por la adquirida. Las transacciones separadas deberán contabilizarse de acuerdo con las NIIF que correspondan.
52 Es probable que una transacción realizada por la adquirente o en nombre de ella o principalmente en beneficio de está o de la entidad combinada, y no fundamentalmente en beneficio de la adquirida (o sus anteriores propietarios) antes de la combinación, sea una transacción separada. Los siguientes son ejemplos de transacciones separadas a las que no se les debe aplicar el método de la adquisición:
(a) una transacción que, de hecho, cancela relaciones preexistentes entre la adquirente y la adquirida;
(b) una transacción que remunera a los empleados o a los anteriores propietarios de la adquirida por servicios futuros; y
(c) una transacción que reembolsa a la adquirida o a sus anteriores propietarios por el pago de los costos de la adquirente relacionados con la adquisición.
Los párrafos B50 a B62 proporcionan guías de aplicación relacionadas.
COSTOS RELACIONADOS CON LA ADQUISICIÓN
53 Son costos relacionados con la adquisición aquellos en que incurre la adquirente para llevar a cabo una combinación de negocios. Estos costos incluyen los honorarios de búsqueda; asesoramiento, jurídicos, contables, de valoración y otros honorarios profesionales o de consultoría; costos generales de administración, incluyendo los de mantener un departamento interno de adquisiciones; y costos de registro y emisión de títulos de deuda y de patrimonio. La adquirente contabilizará los costos relacionados con la adquisición como gastos en los periodos en que los costos se hayan incurrido y los servicios se hayan recibido, con una excepción. Los costos de emisión de deuda o títulos de patrimonio se reconocerán de acuerdo con la NIC 32 y la NIIF 9.
MEDICIÓN POSTERIOR Y CONTABILIZACIÓN
54 En general, una adquirente medirá y contabilizará posteriormente los activos adquiridos, los pasivos asumidos o incurridos y los instrumentos de patrimonio emitidos en una combinación de negocios de acuerdo con otras NIIF aplicables a esas partidas, dependiendo de su naturaleza. Sin embargo, esta NIIF proporciona guías sobre la medición y contabilización de los siguientes activos adquiridos, pasivos asumidos o incurridos e instrumentos de patrimonio emitidos en una combinación de negocios:
(a) derechos readquiridos;
(b) pasivos contingentes reconocidos en la fecha de la adquisición;
(c) activos de indemnización; y
(d) contraprestación contingente.
El párrafo B63 proporciona guías de aplicación al respecto.
DERECHOS READQUIRIDOS
55 Un derecho readquirido reconocido como un activo intangible deberá amortizarse a lo largo del periodo de vigencia del contrato restante en el que se concedió el derecho. Una adquirente que posteriormente venda a un tercero un derecho readquirido incluirá el importe en libros del activo intangible al determinar la ganancia o pérdida de la venta.
PASIVOS CONTINGENTES
56 Tras el reconocimiento inicial y hasta que el pasivo se liquide, cancele o expire, la adquirente medirá un pasivo contingente reconocido en una combinación de negocios al mayor de:
(a) el importe que se reconocería de acuerdo con la NIC 37; y
(b) el importe reconocido inicialmente menos, en su caso, el importe de ingresos acumulados reconocidos de acuerdo con los principios de la NIIF 15 Ingresos de Actividades Ordinarias procedentes de Contratos con Clientes.
Este requerimiento no se aplicará a contratos contabilizados de acuerdo con la NIIF 9.
ACTIVOS DE INDEMNIZACIÓN
57 Al final de cada periodo posterior sobre el que se informe, la adquirente medirá un activo de indemnización que fue reconocido en la fecha de adquisición sobre la misma base que el pasivo o activo indemnizado, sujeto a cualesquiera limitaciones contractuales sobre su importe y, para un activo de indemnización que no se mida posteriormente por su valor razonable, a la evaluación de la administración sobre su cobrabilidad. La adquirente dará de baja en cuentas el activo de indemnización únicamente cuando lo cobre, lo venda o pierda de cualquier otra forma el derecho sobre él.
CONTRAPRESTACIÓN CONTINGENTE
58 Algunos cambios en el valor razonable de una contraprestación contingente que la adquirente reconozca después de la fecha de la adquisición pueden resultar de información adicional que la adquirente obtenga después de esa fecha sobre hechos y circunstancias que existían en la fecha de la adquisición. Estos cambios son ajustes del periodo de medición de acuerdo con los párrafos 45 a 49. Sin embargo, los cambios que procedan de sucesos ocurridos tras la fecha de la adquisición, tales como cumplir un objetivo de ganancias, alcanzar un precio por acción determinado o alcanzar un hito en un proyecto de investigación y desarrollo, no son ajustes del periodo de medición. La adquirente contabilizará los cambios en el valor razonable de una contraprestación contingente que no sean ajustes del periodo de medición de la forma siguiente:
(a) Las contraprestaciones contingentes clasificadas como patrimonio no deberán medirse nuevamente y su liquidación posterior deberá contabilizarse dentro del patrimonio.
(b) Otras contraprestaciones contingentes que:
(i) Se encuentren dentro del alcance de la NIIF 9, deberán medirse por su valor razonable, en la fecha de presentación y los
cambios en el valor razonable se reconocerán en el resultado del periodo de acuerdo con la NIIF 9.
(ii) No se encuentren dentro del alcance de la NIIF 9, deberán medirse por su valor razonable, en la fecha de presentación y los cambios en el valor razonable se reconocerán en el resultado del periodo.
INFORMACIÓN A REVELAR
59 La adquirente revelará información que permita que los usuarios de sus estados financieros evalúen la naturaleza y efectos financieros de una combinación de negocios que haya efectuado, ya sea:
(a) durante el periodo corriente sobre el que se informa; o
(b) después del final del periodo contable pero antes de que los estados financieros hayan sido autorizados para su emisión.
60 Para cumplir con el objetivo del párrafo 59, la adquirente revelará la información especificada en los párrafos B64 a B66.
61 La adquirente revelará información que permita que los usuarios de sus estados financieros evalúen los efectos financieros de los ajustes reconocidos en el periodo corriente sobre el que se informa que estén relacionados con las combinaciones de negocios que tuvieron lugar en el mismo o en periodos anteriores.
Para cumplir con el objetivo del párrafo 61, la adquirente revelará la información especificada en el párrafo B67.
Si la información a revelar específicamente requerida por esta y otras NIIF no cumple los objetivos establecidos en los párrafos 59 a 61, la adquirente revelará cualquier información adicional que sea necesaria para cumplir esos objetivos. 
']])