puts 'Niif5'

niif = Niif.create( number:5, name:'Activos No Corrientes Mantenidos Para La Venta Y Operaciones Discontinuadas')

puts "Se creó #{niif.name}"

niif.contents.create!(text: 'Objetivo', label: 3, order: 1)
niif.contents.create!(text:'El objetivo de esta NIIF es especificar el tratamiento contable de los activos mantenidos para la venta, así como la presentación e información a revelar sobre las operaciones discontinuadas. En particular, la NIIF requiere que: (a) los activos que cumplan los criterios para ser clasificados como mantenidos para la venta sean valorados al menor valor entre su importe en libros y su valor razonable menos los costos de venta, así como que cese la depreciación de dichos activos; y (b) los activos que cumplan los criterios para ser clasificados como mantenidos para la venta se presenten de forma separada en el estado de situación financiera y que los resultados de las operaciones discontinuadas se presenten por separado en el estado del resultado integral.', number: '1', order: 2)

niif.contents.create!(text: 'Alcance', label: 3, order: 3)
niif.contents.create!(text:'Los requerimientos de clasificación y presentación de esta NIIF se aplicarán a todos los activos no corrientes reconocidos1 y a todos los grupos de disposición de una entidad. Los requerimientos de medición de esta NIIF se aplicarán a todos los activos no corrientes reconocidos y a los grupos de activos para su disposición (establecidos en el párrafo 4), excepto a aquellos activos enumerados en el párrafo 5, que continuarán midiéndose de acuerdo con la Norma que se indica en el mismo.', number: '2', order: 4)
niif.contents.create!(text:'Los activos clasificados como no corrientes de acuerdo con la NIC 1 Presentación de Estados Financieros no se reclasificarán como activos corrientes hasta que cumplan los criterios para ser clasificados como mantenidos para la venta de acuerdo con esta NIIF. Los activos de una clase que una entidad normalmente consideraría como no corrientes pero que exclusivamente se adquieren con la finalidad de revenderlos, no se clasificarán como corrientes a menos que cumplan los criterios para ser clasificados como mantenidos para la venta de acuerdo con esta NIIF.', number: '3', order: 5)
niif.contents.create!(text:'En ocasiones, una entidad dispone de un grupo de activos, posiblemente con algunos pasivos directamente asociados, de forma conjunta y en una sola transacción. Un grupo de activos para su disposición puede ser un grupo de unidades generadoras de efectivo, una única unidad generadora de efectivo, o parte de una unidad generadora de efectivo.2 El grupo puede incluir cualesquiera activos y pasivos de la entidad, incluyendo activos corrientes, pasivos corrientes y activos excluidos por el párrafo 5 de los requerimientos de medición de esta NIIF. Si un activo no corriente, dentro del alcance de los requisitos de medición de esta NIIF, formase parte de un grupo de activos para su disposición, los requerimientos de medición de esta NIIF se aplicarán al grupo como un todo, de tal forma que dicho grupo se medirá por el menor valor entre su importe en libros y su valor razonable menos los costos de venta. Los requerimientos de medición de activos y pasivos individuales, dentro del grupo de activos para su disposición, se establecen en los párrafos 18, 19 y 23. ', number: '4', order: 6)
niif.contents.create!(text: '1 Para activos clasificados de acuerdo con la presentación en función del grado de liquidez, los activos no corrientes son aquéllos que incluyen importes que se esperen recuperar en más de doce meses después del periodo sobre el que se informa. El párrafo 3 se aplica a la clasificación de estos activos .', label: 7, order: 7)
niif.contents.create!(text:'Los criterios de medición de esta NIIF3 no son aplicables a los siguientes activos, que quedan cubiertos por las NIIF indicadas en cada caso, independientemente de que sean activos individuales o que formen parte de un grupo de activos para su disposición: 
(a) activos por impuestos diferidos (NIC 12 Impuesto a las Ganancias). 
(b) activos procedentes de beneficios a los empleados (NIC 19 Beneficios a los Empleados). 
(c) activos financieros dentro del alcance de la NIIF 9 Instrumentos Financieros. 
(d) activos no corrientes contabilizados de acuerdo con el modelo de valor razonable de la NIC 40 Propiedades de Inversión. 
(e) activos no corrientes medidos por su valor razonable menos los costos de venta de acuerdo con la NIC 41 Agricultura. 
(f) grupos de contratos de seguro dentro del alcance de la NIIF 17 Contratos de Seguros.', number: '5', order: 8)
niif.contents.create!(text:'Los requerimientos de clasificación, presentación y medición de esta NIIF aplicables a un activo no corriente (o grupo de activos para su disposición), que se clasifique como mantenido para la venta, se aplicarán también a un activo no corriente (o grupo de activos para su disposición) que se clasifique como mantenido para distribuir a los propietarios, cuando actúan como tales (mantenido para distribuir a los propietarios).', number: '5a', order: 9)
niif.contents.create!(text:'Esta NIIF especifica la información a revelar con respecto a los activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta u operaciones discontinuadas. La información a revelar en otras NIIF no se aplicará a estos activos (o grupos de activos para su disposición) a menos que esas NIIF requieran:  (a) información a revelar específica con respecto a activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta u operaciones discontinuadas; o 
(b) información a revelar sobre la medición de activos y pasivos dentro de un grupo de activos para su disposición que no están dentro del alcance de los requerimientos de medición de la NIIF 5 y dicha información a revelar no se está proporcionando en las otras notas de los estados financieros. 
Para cumplir con los requerimientos generales de la NIC 1, en particular con los párrafos 15 y 125 de dicha norma, puede ser necesario revelar información adicional sobre activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta u operaciones discontinuadas.', number: '5b', order: 10)
niif.contents.create!(text: '2 No obstante, en cuanto se espere que los flujos de efectivo de un activo o grupo de activos surjan de la venta en lugar de su uso continuado, éstos pueden llegar a ser menos dependientes de los flujos de efectivo surgidos de otros activos, y de esta forma un grupo de activos para su disposición, que fue parte de una unidad generadora de efectivo, podría convertirse en una unidad generadora de efectivo separada. 
3 Distintos de los párrafos 18 y 19, los cuales requieren que los activos en cuestión se midan de acuerdo con otras NIIF aplicables.', label: 7, order: 11)

niif.contents.create!(text: 'Clasificación De Activos No Corrientes (O Grupo De Activos Para Su Disposición) Como Mantenidos Para La Venta O Como Mantenidos Para Distribuir A Los Propietarios', label: 3, order: 12)
niif.contents.create!(text:'Una entidad clasificará a un activo no corriente (o un grupo de activos para su disposición) como mantenido para la venta, si su importe en libros se recuperará fundamentalmente a través de una transacción de venta, en lugar de por su uso continuado.', number: '6', order: 13)
niif.contents.create!(text:'Para aplicar la clasificación anterior, el activo (o el grupo de activos para su disposición) debe estar disponible, en sus condiciones actuales, para su venta inmediata, sujeto exclusivamente a los términos usuales y habituales para la venta de estos activos (o grupos de activos para su disposición), y su venta debe ser altamente probable.', number: '7', order: 14)
niif.contents.create!(text:'Para que la venta sea altamente probable, el nivel apropiado de la gerencia debe estar comprometido con un plan para vender el activo (o grupo de activos para su disposición), y debe haberse iniciado de forma activa un programa para encontrar un comprador y completar dicho plan. Además, la venta del activo (o grupo de activos para su disposición) debe negociarse activamente a un precio razonable, en relación con su valor razonable actual. Asimismo, debe esperarse que la venta cumpla las condiciones para su reconocimiento como venta finalizada dentro del año siguiente a la fecha de clasificación, con las excepciones permitidas en el párrafo 9, y además las actividades requeridas para completar el plan deberían indicar que es improbable que se realicen cambios significativos en el plan o que el mismo vaya a ser cancelado. La probabilidad de aprobación por los accionistas (si es requerido por la jurisdicción) deberá considerarse como parte de la evaluación de si la venta es altamente probable.', number: '8', order: 15)
niif.contents.create!(text:'Una entidad que esté comprometida en un plan de venta, que implique la pérdida de control de una subsidiaria, clasificará todos los activos y pasivos de esa subsidiaria como mantenidos para la venta, cuando se cumplan los criterios establecidos en los párrafos 6 a 8, independientemente de que la entidad retenga después de la venta una participación no controladora en su anterior subsidiaria.', number: '8a', order: 16)
niif.contents.create!(text:'Existen hechos y circunstancias que podrían alargar el periodo para completar la venta más allá de un año. Una ampliación del periodo exigido para completar una venta no impide que el activo (o grupo de activos para su disposición) sea clasificado como mantenido para la venta, si el retraso viene causado por hechos o circunstancias fuera del control de la entidad, y existan evidencias suficientes de que la entidad se mantiene comprometida con su plan para vender el activo (o grupo de activos para su disposición). Este sería el caso en que se cumplan los criterios contenidos en el Apéndice B.', number: '9', order: 17)
niif.contents.create!(text:'Las transacciones de venta incluyen las permutas de activos no corrientes por otros activos no corrientes, cuando éstas tengan carácter comercial, de acuerdo con la NIC 16 Propiedades, Planta y Equipo.', number: '10', order: 18)
niif.contents.create!(text:'Cuando una entidad adquiera un activo no corriente (o grupo de activos para su disposición) exclusivamente con el propósito de su posterior venta, clasificará dicho activo no corriente (o grupo de activos para su disposición) como mantenido para la venta, en la fecha de adquisición, sólo si se cumple el requisito de un año del párrafo 8 (con las excepciones permitidas en el párrafo 9) y sea altamente probable que cualquier otro requisito de los contenidos en los párrafos 7 y 8, que no se cumpla en esa fecha, sea cumplido dentro de un corto periodo tras la adquisición (por lo general, en los tres meses siguientes).', number: '11', order: 19)
niif.contents.create!(text:'Si se cumplen los criterios de los párrafos 7 y 8 después del final del periodo sobre el que se informa, una entidad no clasificará un activo no corriente (o grupo de activos para su disposición) como mantenido para la venta en los estados financieros que emita. No obstante, cuando esos criterios se cumplan después del final del periodo sobre el que se informa, pero antes de la autorización para la emisión de los estados financieros, la entidad revelará en las notas la información especificada en los apartados (a), (b) y (d) del párrafo 41.', number: '12', order: 20)
niif.contents.create!(text:'Cuando la entidad se comprometa a distribuir el activo (o grupo de activos para su disposición) a los propietarios, dicho activo no corriente (o grupo de activos para su disposición) se clasificará como mantenido para distribuir a los propietarios. Para que éste sea el caso, los activos deben estar disponibles para la distribución inmediata en sus actuales condiciones, y la distribución debe ser altamente probable. Para que la distribución sea altamente probable, deben haberse iniciado las actividades para completar la distribución y debe esperarse que estén completadas en un año a partir de la fecha de clasificación. Las actividades requeridas para completar la distribución deberían indicar que es improbable que puedan realizarse cambios significativos en la distribución o que ésta pueda cancelarse. La probabilidad de aprobación por los accionistas (si es requerido por la jurisdicción) deberá considerarse como parte de la evaluación de si la distribución es altamente probable.', number: '12a', order: 21)

niif.contents.create!(text: 'Activos No Corrientes Que Van A Ser Abandonados', label: 3, order: 22)
niif.contents.create!(text:'Una entidad no clasificará como mantenido para la venta Un activo no corriente (o a un grupo de activos para su disposición) que vaya a ser abandonado. Esto es debido a que su importe en libros va a ser recuperado principalmente a través de su uso continuado. Sin embargo, si el grupo de activos para su disposición que va a ser abandonado cumpliese los criterios de los apartados (a) a (c) del párrafo 32, la entidad presentará los resultados y flujos de efectivo del grupo de activos para su disposición como una operación discontinuada, de acuerdo con los párrafos 33 y 34, en la fecha en que deja de utilizarlo. Los activos no corrientes (o grupos de activos para su disposición) que van a ser abandonados comprenderán tanto activos no corrientes (o grupos de activos para su disposición) que vayan a utilizarse hasta el final de su vida económica, como activos no corrientes (o grupos de activos para su disposición) que vayan a cerrarse definitivamente en lugar de ser vendidos.', number: '13', order: 23)
niif.contents.create!(text:'La entidad no contabilizará un activo no corriente, que vaya a estar temporalmente fuera de uso, como si hubiera sido abandonado.', number: '14', order: 24)

niif.contents.create!(text: 'Medición De Activos No Corrientes (O Grupos De Activos Para Su Disposición) Clasificados Como Mantenidos Para La Venta Medición De Un Activo No Corriente (O Grupo De Activos Para Su Disposición)', label: 3, order: 25)
niif.contents.create!(text:'Una entidad medirá los activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta, al menor de su importe en libros o su valor razonable menos los costos de venta.', number: '15', order: 26)
niif.contents.create!(text:'Una entidad medirá los activos no corrientes (o grupo de activos para su disposición) clasificados como mantenidos para distribuir a los propietarios, al menor valor entre su importe en libros y su valor razonable menos los costos de la distribución.4', number: '15a', order: 27)
niif.contents.create!(text:'Si un activo (o grupo de activos para su disposición) adquirido recientemente cumple los criterios para ser clasificado como mantenido para la venta (véase el párrafo 11), la aplicación del párrafo 15 conducirá a que el activo (o grupo de activos para su disposición) se mida, en el momento de su reconocimiento inicial, al menor valor entre su importe en libros si no se hubiese clasificado de esta manera (por ejemplo, el costo) y su valor razonable menos los costos de venta. En consecuencia, si el activo (o grupo de activos para su disposición) se hubiera adquirido como parte de una combinación de negocios, se medirá por su valor razonable menos los costos de venta.', number: '16', order: 28)
niif.contents.create!(text:'Cuando se espere que la venta se produzca más allá del periodo de un año, la entidad medirá los costos de venta por su valor actual. Cualquier incremento en el valor actual de esos costos de venta, que surja por el transcurso del tiempo, se presentará en el estado de resultados como un costo financiero.', number: '17', order: 29)


niif.contents.create!(text: '4 Los costos de distribución son los costos incrementales directamente atribuibles a ésta, excluyendo los costos financieros y el gasto por impuestos a las ganancias.', label: 7, order: 30)
niif.contents.create!(text:'Inmediatamente antes de la clasificación inicial del activo (o grupo de activos para su disposición) como mantenido para la venta, el importe en libros del activo (o de todos los activos y pasivos del grupo) se medirá de acuerdo con las NIIF que sean de aplicación.', number: '18', order: 31)
niif.contents.create!(text:'Al proceder a medir un grupo de activos para su disposición con posterioridad al reconocimiento inicial, el importe en libros de cualquier activo y pasivo que no entren dentro del alcance de los requisitos de medición establecidos en esta NIIF, pero que estén incluidos en un grupo de activos para su disposición clasificado como mantenido para la venta, se determinará de acuerdo con las NIIF aplicables, antes de volver a medir el valor razonable menos los costos de venta del grupo de activos para su disposición.', number: '19', order: 32)

niif.contents.create!(text: 'Reconocimiento Y Reversión De Las Pérdidas Por Deterioro ', label: 3, order: 33)
niif.contents.create!(text:'La entidad reconocerá una pérdida por deterioro debida a las reducciones iniciales o posteriores del valor del activo (o grupo de activos para su disposición) hasta el valor razonable menos los costos de venta, siempre que no se haya reconocido según el párrafo 19. ', number: '20', order: 34)
niif.contents.create!(text:'La entidad reconocerá una ganancia por cualquier incremento posterior derivado de la medición del valor razonable menos los costos de venta de un activo, aunque sin superar la pérdida por deterioro acumulada que haya sido reconocida, ya sea de acuerdo con esta NIIF o previamente, de acuerdo con la NIC 36 Deterioro del Valor de los Activos.', number: '21', order: 35)
niif.contents.create!(text:'La entidad reconocerá una ganancia por cualquier incremento posterior en el valor razonable menos los costos de venta de un grupo de activos para su disposición: (a) en la medida que no haya sido reconocido de acuerdo con el párrafo 19; pero (b) no por encima de la pérdida por deterioro de valor acumulada que ha sido reconocida, de acuerdo con esta NIIF o con anterioridad de acuerdo con la NIC 36, sobre los activos no corrientes que están dentro del alcance de los requerimientos de medición de esta NIIF.', number: '22', order: 36)
niif.contents.create!(text:'La pérdida por deterioro de valor (o cualquier ganancia posterior) reconocida para un grupo de activos para su disposición reducirá (o incrementará) el importe en libros de los activos no corrientes del grupo que estén dentro del alcance de los requerimientos de medición de esta NIIF, en el orden de asignación establecido en los párrafos 104(a) y (b) y 122 de la NIC 36 (revisada en 2004).', number: '23', order: 37)
niif.contents.create!(text:'La pérdida o ganancia no reconocida previamente a la fecha de la venta de un activo no corriente (o grupo de activos para su disposición), se reconocerá en la fecha en el que se produzca su baja en cuentas. Los requerimientos que se refieren a la baja en cuentas están establecidos en: (a) los párrafos 67 a 72 de la NIC 16 (revisada en 2003) para las propiedades, planta y equipo, y 
(b) Los párrafos 112 a 117 de la NIC 38 Activos Intangibles (revisada en 2004) para este tipo de activos.', number: '24', order: 38)
niif.contents.create!(text:'La entidad no depreciará (o amortizará) el activo no corriente mientras esté clasificado como mantenido para la venta, o mientras forme parte de un grupo de activos para su disposición clasificado como mantenido para la venta. No obstante, continuarán reconociéndose tanto los intereses como otros gastos atribuibles a los pasivos de un grupo de activos para su disposición que se haya clasificado como mantenido para la venta.', number: '25', order: 39)

niif.contents.create!(text: 'Cambios En Un Plan De Venta O En Un Plan De Distribución A Los Propietarios', label: 3, order: 40)
niif.contents.create!(text:'Si una entidad ha clasificado un activo (o grupo de activos para su disposición) como mantenido para la venta o como mantenido para su distribución a los propietarios, pero dejan de cumplirse los criterios de los párrafos 7 a 9 (para el mantenido para la venta) o del párrafo 12A (para el mantenido para su distribución a los propietarios), la entidad dejará de clasificar el activo (o grupo de activos para su disposición) como mantenido para la venta o mantenido para su distribución a los propietarios (respectivamente). En estos casos, una entidad seguirá las guías de los párrafos 27 a 29 para contabilizar este cambio excepto cuando aplique el párrafo 26A.', number: '26a', order: 41)
niif.contents.create!(text:'Si una entidad reclasifica un activo (o grupo de activos para su disposición) directamente de mantenido para la venta a mantenido para la distribución a los propietarios, o directamente de mantenido para la distribución a los propietarios ha mantenido para la venta, el cambio en la clasificación se considera una continuación del plan de disposición original. La entidad: 
(a) No seguirá las guías de los párrafos 27 a 29 para contabilizar este cambio. La entidad aplicará los requerimientos de clasificación, presentación y medición de esta NIIF que sean aplicables al nuevo método de disposición. 
(b) Medirá el activo no corriente (o grupo de activos para su disposición) siguiendo los requerimientos del párrafo 15 (si se reclasifica como mantenido para la venta) o 15A (si se reclasifica como mantenido para la distribución a los propietarios) y reconocerá cualquier reducción o incremento en el valor razonable menos los costos de venta/costos de distribución del activo no corriente (o grupo de activos para su disposición) siguiendo los requerimientos de los párrafos 20 a 25. 
(c) No cambiará la fecha de clasificación de acuerdo con los párrafos 8 y 12A. Esto no impide una ampliación del periodo requerido para completar una venta o una distribución a los propietarios si se cumplen las condiciones del párrafo 9.', number: '26a', order: 42)
niif.contents.create!(text:'Una entidad medirá los activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta, o como mantenido para su distribución a los propietarios, (o que deje de formar parte de un grupo de activos para su disposición clasificado como mantenido para la venta o mantenido para su distribución a los propietarios) al menor de: 
(a) su importe en libros antes de que el activo (o grupo de activos para su disposición) fuera clasificado como mantenido para la venta o como mantenido para la distribución a los propietarios ajustado por cualquier depreciación, amortización o revaluación que se hubiera reconocido si el activo (o grupo de activos para su disposición) no se hubiera clasificado como mantenido para la venta o como mantenido para la distribución a los propietarios, y 
(b) su importe recuperable en la fecha de la decisión posterior de no venderlo o distribuirlo.5', number: '27', order: 43)
niif.contents.create!(text:'La entidad incluirá cualquier ajuste requerido al importe en libros de un activo no corriente, que deje de estar clasificado como mantenido para la venta o para su distribución a los propietarios, en el resultado del periodo,6 dentro de los resultados de las operaciones continuadas, en el periodo en que dejen de cumplirse los criterios de los párrafos 7 a 9 o 12A. Si el grupo de activos para su disposición o activo no corriente que deja de ser clasificado como mantenido para la venta o como mantenido para la distribución a los propietarios es una subsidiaria, operación conjunta, negocio conjunto, asociada o parte de una participación en un negocio conjunto o en una asociada, se modificarán, en consecuencia, los estados financieros de los periodos desde la clasificación como mantenido para la venta o como mantenido para la distribución a los propietarios. La entidad presentará ese ajuste en la misma partida del estado del resultado integral utilizada para presentar la pérdida o ganancia, si procede, reconocida de acuerdo con el párrafo 37.', number: '28', order: 44)
niif.contents.create!(text:'Si una entidad retirase un determinado activo individual o un pasivo, de un grupo de activos para su disposición clasificado como mantenido para la venta, los restantes activos y pasivos del grupo continuarán midiéndose como un grupo de activos para su disposición sólo si éste cumpliese los requisitos establecidos en los párrafos 7 a 9. Si una entidad retirase un determinado activo individual o un pasivo, de un grupo de activos para su disposición clasificado como mantenido para la distribución a los propietarios, los restantes activos y pasivos del grupo de activos para su disposición a distribuir continuarán midiéndose como un grupo solo si éste cumpliese los criterios establecidos en el párrafo 12A. En otro caso, los restantes activos no corrientes del grupo que individualmente cumplan los criterios para ser clasificados como mantenidos para la venta (o como mantenidos para la distribución a los propietarios) se medirán individualmente por el menor valor entre sus importes en libros y su valor razonable menos los costos de venta (o costos de distribución) en esa fecha. Cualquier activo no corriente que no cumpla los criterios de mantenido para la venta dejará de ser clasificado como mantenido para la venta, de acuerdo con el párrafo 26. Cualquier activo no corriente que no cumpla los criterios de mantenido para la distribución a los propietarios dejará de ser clasificado como tal, de acuerdo con el párrafo 26.', number: '29' , order: 43)

niif.contents.create!(text: '5 Si el activo no corriente es parte de la unidad generadora de efectivo, su importe recuperable es el importe en libros que habría sido reconocido tras la distribución de cualquier pérdida por deterioro del valor surgida en dicha unidad generadora de efectivo de acuerdo con la NIC 36.', label: 7, order: 44)
niif.contents.create!(text: '6 A menos que el activo sea una propiedad, planta o equipo o un activo intangible, que hubiera sido revaluado de acuerdo con la NIC 16 o la NIC 38 antes de su clasificación como mantenido para la venta, en cuyo caso el ajuste se tratará como un incremento o decremento procedente de la revaluación. ', label: 7, order: 45)

niif.contents.create!(text: 'Presentación E Información A Revelar ', label: 3, order: 46)
niif.contents.create!(text:'Una entidad presentará y revelará información que permita a los usuarios de los estados financieros evaluar los efectos financieros de las operaciones discontinuadas y las disposiciones de los activos no corrientes (o grupos de activos para su disposición).', number: '30', order: 47)

niif.contents.create!(text: 'Presentación De Operaciones Discontinuadas ', label: 3, order: 48)
niif.contents.create!(text:'Un componente de una entidad comprende las operaciones y flujos de efectivo que pueden ser distinguidos claramente del resto de la entidad, tanto desde un punto de vista operativo como a efectos de información financiera. En otras palabras, un componente de una entidad habrá constituido una unidad generadora de efectivo o un grupo de unidades generadoras de efectivo mientras haya estado en uso.', number: '31', order: 49)
niif.contents.create!(text:'Una operación discontinuada es un componente de la entidad que ha sido dispuesto, o bien que ha sido clasificado como mantenido para la venta, y (a) representa una línea de negocio o un área geográfica, que es significativa y puede considerarse separada del resto; 
(b) es parte de un único plan coordinado para disponer de una línea de negocio o de un área geográfica de la operación que sea significativa y pueda considerarse separada del resto; o 
(c) es una entidad subsidiaria adquirida exclusivamente con la finalidad de revenderla.', number: '32', order: 50)
niif.contents.create!(text: 'Una entidad revelará: (a) En el estado del resultado integral, un importe único que comprenda el total de: (i) el resultado después de impuestos de las operaciones discontinuadas y (ii) la ganancia o pérdida después de impuestos reconocida por la medición a valor razonable menos costos de venta, o por la disposición de los activos o grupos para su disposición que constituyan la operación discontinuada. (b) Un desglose del importe recogido en el apartado 
(a) anterior, detallando: (i) los ingresos de actividades ordinarias, los gastos y el resultado antes de impuestos de las operaciones discontinuadas; (ii) el gasto por impuesto a las ganancias relativo al anterior resultado, como requiere el apartado (h) del párrafo 81 de la NIC 12. 
 (iii)el resultado que se haya reconocido por causa de la medición a valor razonable menos los costos de venta, o bien por causa de la disposición de los activos o grupos de activos para su disposición que constituyan la operación discontinuada; y 
(iv) el gasto por impuesto a las ganancias relativo al anterior resultado, como requiere el apartado (h) del párrafo 81 de la NIC 12. 
Este desglose podría presentarse en las notas o en el estado del resultado integral. Si se presentase en el estado del resultado integral, se hará en una sección identificada como relativa a las operaciones discontinuadas, esto es, de forma separada de las operaciones que continúen. El desglose no se requiere para los grupos de activos para su disposición que sean subsidiarias adquiridas recientemente y que cumplan los criterios para ser clasificadas como mantenidas para la venta en el momento de la adquisición (véase el párrafo 11). (c) Los flujos netos de efectivo atribuibles a las actividades de operación, de inversión y financiación de las operaciones discontinuadas. Esta información a revelar podría presentarse en las notas o en los estados financieros. Esta información a revelar no se requiere para los grupos de activos para su disposición que sean subsidiarias adquiridas recientemente, y cumplan los criterios para ser clasificadas en el momento de la adquisición como mantenidas para la venta (véase el párrafo 11). (d) El importe de ingresos por operaciones que continúan y de operaciones discontinuadas atribuibles a los propietarios de la controladora. Estas informaciones a revelar podrían presentarse en las notas o en el estado del resultado integral. ', label: 3,order: 51)
niif.contents.create!(text:'Si una entidad presenta las partidas del resultado del periodo en un estado separado como se describe en el párrafo 10A de la NIC 1 (modificada en 2011), en dicho estado separado se presentará una sección identificada como relacionada con operaciones discontinuadas.', number: '33a', order: 52)
niif.contents.create!(text:'Una entidad presentará la información a revelar del párrafo 33 para todos los periodos anteriores sobre los que informe en los estados financieros, de forma que la información a revelar para esos periodos se refiera a todas las operaciones que tienen el carácter de discontinuadas al final del periodo sobre el que se informa del último periodo presentado.', number: '34', order: 53)
niif.contents.create!(text:'Los ajustes que se efectúen en el periodo corriente a los importes presentados previamente, que se refieran a las operaciones discontinuadas y estén directamente relacionados con la disposición de las mismas en un periodo anterior, se clasificarán de forma separada dentro de la información correspondiente a dichas operaciones discontinuadas. Se revelará la naturaleza e importe de tales ajustes. Ejemplos de circunstancias en las que podrían surgir estos ajustes son: 
(a) La resolución de incertidumbres derivadas de las condiciones de una disposición, tales como la resolución de los ajustes al precio de compra y las indemnizaciones pactadas con el comprador. 
(b) La resolución de incertidumbres que surjan de y estén directamente relacionadas con la operación del componente antes de su disposición, como las obligaciones medioambientales y de garantía que hayan sido retenidas por el vendedor. 
(c) La cancelación de las obligaciones derivadas de un plan de beneficios a los empleados, siempre que la cancelación esté directamente relacionada con la transacción disposición.', number: '35', order: 54)
niif.contents.create!(text:'Si la entidad dejase de clasificar un componente como mantenido para la venta, los resultados de operación relativos al componente que se hayan presentado previamente como procedentes de operaciones discontinuadas, de acuerdo con los párrafos 33 a 35, se reclasificarán e incluirán en los resultados de las operaciones que continúan, para todos los periodos sobre los que se presente información. Se mencionará expresamente que los importes relativos a los periodos anteriores han sido objeto de una nueva presentación.', number: '36', order: 55)
niif.contents.create!(text:'Una entidad que esté comprometida con un plan de venta, que implique la pérdida de control de una subsidiaria, revelará la información requerida en los párrafos 33 a 36, cuando la subsidiaria sea un grupo de activos para su disposición que cumpla la definición de una operación discontinuada de acuerdo con el párrafo 32.', number: '36a', order: 56)

niif.contents.create!(text: 'Ganancias O Pérdidas Relacionadas Con Las Operaciones Que Continúan', label: 3, order: 57)
niif.contents.create!(text:'Cualquier ganancia o pérdida que surja de volver a medir activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta, que no cumplan la definición de operación discontinuada, se incluirán en el resultado de las operaciones que continúan.', number: '37', order: 58)

niif.contents.create!(text: 'Presentación De Un Activo No Corriente O Grupo De Activos Para Su Disposición Clasificado Como Mantenido Para La Venta', label: 3, order: 59)
niif.contents.create!(text:'Una entidad presentará los activos no corrientes clasificados como mantenidos para la venta y los activos correspondientes a un grupo de activos para su disposición clasificado como mantenido para la venta de forma separada del resto de los activos en el estado de situación financiera. Los pasivos que formen parte de un grupo de activos para su disposición clasificado como mantenido para la venta, se presentarán en el estado de situación financiera de forma separada de los otros pasivos. Estos activos y pasivos no se compensarán, ni se presentarán como un único importe. Se revelará información, por separado, de las principales clases de activos y pasivos clasificados como mantenidos para la venta, ya sea en el estado de situación financiera o en las notas, salvo la excepción permitida en el párrafo 39. Una entidad presentará de forma separada los importes acumulados de los ingresos o de los gastos que se hayan reconocido en otro resultado integral y se refieran a los activos no corrientes (o grupos de activos para su disposición) clasificados como mantenidos para la venta.', number: '38', order: 60)
niif.contents.create!(text:'Si el grupo de activos para su disposición es una subsidiaria adquirida recientemente, que cumple los criterios para ser clasificado como mantenido para la venta en el momento de la adquisición (véase el párrafo 11), no se requiere revelar información sobre las principales clases de activos y pasivos.', number: '39', order: 61)
niif.contents.create!(text:'Una entidad no reclasificará ni presentará de nuevo importes ya presentados de activos no corrientes, o de activos y pasivos de grupos de activos para su disposición, que hayan estado clasificados como mantenidos para la venta en el estado de situación financiera en periodos anteriores, a fin de reflejar la misma clasificación que se les haya dado en el estado de situación financiera del último periodo presentado.', number: '40', order: 62)

niif.contents.create!(text: 'Información A Revelar Adicional', label: 3, order: 63)
niif.contents.create!(text:'La entidad revelará en las notas la siguiente información, referida al periodo en el cual el activo no corriente (o grupo de activos para su disposición) haya sido clasificado como mantenido para la venta o vendido: 
(a) una descripción del activo no corriente (o grupo de activos para su disposición); (b) una descripción de los hechos y circunstancias de la venta, o de los que hayan llevado a decidir la venta o disposición esperada, así como la forma y momento esperados para dicha disposición; 
(c) la ganancia o pérdida reconocida de acuerdo con los párrafos 20 a 22 y, si no se presentase de forma separada en el estado del resultado integral, la partida de dicha cuenta donde se incluya ese resultado; 
(d) si fuera aplicable, el segmento dentro del cual se presenta el activo no corriente (o grupo de activos para su disposición), de acuerdo con la NIIF 8 Segmentos de Operación.', number: '41', order: 64)
niif.contents.create!(text:'Si se hubiesen aplicado el párrafo 26 o el 29, la entidad revelará, en el periodo en el que se decida cambiar el plan de venta del activo no corriente (o grupo de activos para su disposición), una descripción de los hechos y circunstancias que hayan llevado a tomar tal decisión, así como el efecto de la misma sobre los resultados de las operaciones, tanto para dicho periodo como para cualquier periodo anterior sobre el que se presente información.', number: '42', order: 65)

niif.contents.create!(text: 'Disposiciones Transitorias', label: 3 , order: 66)
niif.contents.create!(text:'La NIIF será aplicada de forma prospectiva a los activos no corrientes (o grupos de activos para su disposición) que cumplan los criterios para ser clasificados como mantenidos para la venta, así como para las operaciones que cumplan los criterios para ser clasificadas como discontinuadas tras la entrada en vigor de la NIIF. La entidad puede aplicar los requerimientos de esta NIIF a todos los activos no corrientes (o grupos de activos para su disposición) que cumplan los criterios para ser clasificados como mantenidos para la venta, así como para las operaciones que cumplan los criterios para ser clasificadas como  discontinuada, en cualquier fecha anterior a la entrada en vigor de la NIIF, siempre que las valoraciones y demás información necesaria para aplicar la NIIF, sea obtenida en la fecha en que se cumplieron los mencionados criterios.', number: '43', order: 67)

niif.contents.create!(text: 'Apéndice A', label: 3, order: 68)
niif.contents.create!(text: 'Definiciones De Términos', label: 4, order: 69)
niif.contents.create!(text: 'Este Apéndice forma parte integrante de la NIIF. 
unidad generadora de efectivo 
El grupo identificable de activos más pequeño que genera entradas de efectivo que sean, en buena medida, independientes de los flujos de efectivo derivados de otros activos o grupos de activos. 
componente de la entidad 
Las operaciones y flujos de efectivo que pueden ser distinguidos claramente del resto de la entidad, tanto desde un punto de vista de la operación como a efectos de información financiera. 
costos de venta 
Los costos incrementales directamente atribuibles a la disposición de un activo (o grupo de activos para su disposición), excluyendo los costos financieros y los gastos por impuestos a las ganancias. 
activo corriente 
Una entidad clasificará un activo como corriente cuando: 
(a) espera realizar el activo, o tiene la intención de venderlo o consumirlo en su ciclo normal de operación; 
(b) mantiene el activo principalmente con fines de negociación; 
(c) espera realizar el activo dentro de los doce meses siguientes al periodo sobre el que se informa; o
 (d) el activo es efectivo o equivalente al efectivo (como se define en la NIC 7) a menos que éste se encuentre restringido y no pueda ser intercambiado ni utilizado para cancelar un pasivo por un ejercicio mínimo de doce meses después del ejercicio sobre el que se informa. 
operación discontinuada 
Un componente de la entidad que ha sido dispuesto, o bien que ha sido clasificado como mantenido para la venta y: 
(a) representa una línea de negocio o un área geográfica, que es significativa y puede considerarse separada del resto; 
(b) es parte de un único plan coordinado para disponer de una línea de negocio o de un área geográfica de la operación que sea significativa y pueda considerarse separada del resto; o 
(c) es una entidad subsidiaria adquirida exclusivamente con la finalidad de revenderla. 
grupo de activos para su disposición 
Un grupo de activos del que se va a disponer ya sea por venta o por otra vía, de forma conjunta como grupo en una única operación, junto con los pasivos directamente asociados con tales activos que se vayan a transferir en la transacción. El grupo incluirá la plusvalía adquirida en una combinación de negocios, si el grupo es una unidad generadora de efectivo a la que se haya atribuido la plusvalía de acuerdo con los requisitos de los párrafos 80 a 87 de la NIC 36 Deterioro del Valor de los Activos (según la revisión de 2004) o bien si se trata de una operación dentro de esa unidad generadora de efectivo. 
valor razonable 
Valor razonable es el precio que se recibiría por vender un activo o que se pagaría por transferir un pasivo en una transacción ordenada entre participantes del mercado en la fecha de la medición. (Véase la NIIF 13) 
compromiso firme de compra 
Un acuerdo con un tercero no vinculado, que compromete a ambas partes y por lo general es exigible legalmente, que (a) especifica todas las condiciones significativas, incluyendo el precio y el plazo de las transacciones, y (b) incluye una penalización por incumplimiento lo suficientemente significativa para que el cumplimiento del acuerdo sea altamente probable. 
altamente probable 
Con una probabilidad significativamente mayor de que ocurra que de que no ocurra. activo no corriente
Un activo que no cumple la definición de activo corriente. 
probable 
Que tiene más probabilidad de que ocurra que de lo contrario. 
importe recuperable 
El mayor entre el valor razonable menos los costos de venta de un activo y su valor en uso. 
valor en uso 
El valor actual de los flujos futuros estimados de efectivo que se espera se derive del uso continuado de un activo y de su disposición al final de su vida útil.', order: 70)

niif.contents.create!(text: 'Apéndice B', label: 3, order: 71)
niif.contents.create!(text: 'Suplemento De Aplicación', label: 4, order: 72)
niif.contents.create!(text:'Este Apéndice forma parte integrante de la NIIF. 
Extensión del periodo requerido para completar una venta 
Como se recoge en el párrafo 9, una ampliación del periodo requerido para completar una venta no impide que un activo (o grupo de activos para su disposición) se clasifique como mantenido para la venta, si el retraso está causado por hechos o circunstancias fuera del control de la entidad y existen evidencias suficientes de que la entidad sigue comprometida con su plan de venta del activo (o grupo de activos para su disposición). En consecuencia, se eximirá a la entidad de aplicar el requisito de un año, establecido en el párrafo 8, en las siguientes situaciones en las cuales se pongan de manifiesto estos hechos o circunstancias: (a) En la fecha en que la entidad se comprometa con un plan para vender un (o grupo de activos para su disposición), exista una expectativa razonable de que otros terceros (distintos del comprador) impondrán condiciones sobre la transferencia del activo (o grupo de activos para su disposición) que ampliarán el periodo necesario para completar la venta, y: (i) las acciones necesarias para responder a esas condiciones no puedan ser iniciadas hasta después de que se haya obtenido el compromiso firme de compra; y (ii) sea altamente probable un compromiso firme de compra en el plazo de un año. (b) La entidad obtenga un compromiso firme de compra y, como resultado, el comprador u otros terceros hayan impuesto de forma inesperada condiciones sobre la transferencia del activo no corriente (o grupo de activos para su disposición) clasificado previamente como mantenido para la venta, que extenderán el periodo exigido para completar la venta, y: (i) han sido tomadas a tiempo las acciones necesarias para responder a las condiciones impuestas; y (ii) se espera una resolución favorable de los factores que originan el retraso. (c) Durante el periodo inicial de un año, surgen circunstancias que previamente fueron consideradas improbables y, como resultado, el activo no corriente (o grupo de activos para su disposición) previamente clasificado como mantenido para la venta no se ha vendido al final de ese periodo, y: B1 NIIF 5 A276 © IFRS Foundation(i) durante el periodo inicial de un año, la entidad emprendió las acciones necesarias para responder al cambio de las circunstancias, (ii) los activos no corrientes (o grupos de activos para su disposición) están siendo comercializados de forma activa a un precio razonable, dado el cambio en las circunstancias; y (iii) se cumplen los criterios establecidos en los párrafos 7 y 8. NIIF 5 © IFRS Foundation A277Apéndice C Modificaciones a otras NIIF Las modificaciones de este apéndice se aplicarán en los periodos anuales que comiencen a partir del 1 de enero de 2005. Si una entidad aplica esta NIIF para un periodo anterior, estas modificaciones tendrán también vigencia para el mismo.  Las modificaciones contenidas en este apéndice cuando se emitió esta NIIF en 2004 se han incorporado a las NIIF pertinentes publicadas en este volumen.', number: 'b1', order: 73)


